/*
 * 网银支付
 * <p>提供网银支付相关服务（支付下单等功能）</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.netpay;


import com.yeepay.yop.sdk.auth.req.AuthorizationReqRegistry;
import com.yeepay.yop.sdk.auth.req.DefaultAuthorizationReqRegistry;
import com.yeepay.yop.sdk.client.ClientParams;
import com.yeepay.yop.sdk.client.AbstractServiceClientBuilder;

public class NetpayClientBuilder extends AbstractServiceClientBuilder<NetpayClientBuilder, NetpayClientImpl>{

    private static final AuthorizationReqRegistry REGISTRY;

    static {
        REGISTRY = new DefaultAuthorizationReqRegistry();
        REGISTRY.register("order", "YOP-SM2-SM3,YOP-RSA2048-SHA256");
    }

    @Override
    protected AuthorizationReqRegistry authorizationReqRegistry() {
        return REGISTRY;
    }

    @Override
    protected NetpayClientImpl build(ClientParams params) {
        return new NetpayClientImpl(params);
    }

    /**
     * @return Create new instance of builder with all defaults set.
     */
    public static NetpayClientBuilder builder(){
        return new NetpayClientBuilder();
    }

}
