/*
 * 商户结算2.0
 * <p><a href=\"http://wiki.yeepay.com/pages/viewpage.action?pageId=112010456\">http://wiki.yeepay.com/pages/viewpage.action?pageId=112010456</a></p>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.settle;

import com.yeepay.yop.sdk.exception.YopClientException;
import com.yeepay.yop.sdk.model.yos.YosDownloadInputStream;
import com.yeepay.yop.sdk.model.yos.YosDownloadResponse;
import com.yeepay.yop.sdk.service.settle.request.*;
import com.yeepay.yop.sdk.service.settle.response.*;
import com.yeepay.yop.sdk.service.settle.model.BalanceQuerySelfSettleQueryResponseDtoResult;
import java.io.File;
import com.yeepay.yop.sdk.service.settle.model.RecordsQuerySettleRecordQueryResponseDtoResult;
import com.yeepay.yop.sdk.service.settle.model.SelfSettleApplySelfSettleResponseDtoResult;
import com.yeepay.yop.sdk.service.settle.model.SettleCardAddMerchantSettleCardResponseDTOResult;
import com.yeepay.yop.sdk.service.settle.model.SettleCardModifyMerchantSettleCardResponseDTOResult;
import com.yeepay.yop.sdk.service.settle.model.SettleWayModifyRatioModifySettleWayRatioRequestDtoParam;
import com.yeepay.yop.sdk.service.settle.model.SettleWayModifyRatioModifySettleWayRatioResponseDtoResult;
import com.yeepay.yop.sdk.service.settle.model.SettleWayQuerySettleWayQueryYOPResponseDtoResult;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import org.junit.Test;
import org.junit.Ignore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.io.IOException;
import org.apache.commons.io.IOUtils;
/**
 * API tests for SettleClient
 */
@Ignore
public class SettleClientTest {

    private static final Logger LOGGER = LoggerFactory.getLogger(SettleClientTest.class);

    // 该Client线程安全，请使用单例模式，多次请求共用
    private final SettleClient api = SettleClientBuilder.builder().build();


    /**
     * 待结算金额查询
     *
     * 查询商户自助结算下未结算的交易统计信息。
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void balanceQueryTest() throws YopClientException {
        BalanceQueryRequest request = new BalanceQueryRequest();
        request.setParentMerchantNo("parentMerchantNo_example");
        request.setMerchantNo("merchantNo_example");
        request.setOperatePeriod("operatePeriod_example");
        request.setEndTime("2023-05-07 10:49:05");
        BalanceQueryResponse response = api.balanceQuery(request);
        LOGGER.info("result:{}", response.getResult());
        // TODO: test validations
    }

    /**
     * 结算对账文件获取接口
     *
     * 支持商户进行对账文件下载。 受理失败，返回响应错误码；受理成功，返回文件
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void fileGetTest() throws YopClientException {
        FileGetRequest request = new FileGetRequest();
        request.setMerchantNo("merchantNo_example");
        request.setParentMerchantNo("parentMerchantNo_example");
        request.setSettleRequestNo("settleRequestNo_example");
        request.setSettleDate("settleDate_example");
        YosDownloadResponse response = api.fileGet(request);
        // 及时关闭文件流，避免连接泄漏
        YosDownloadInputStream result = null;
        try {
            result = response.getResult();
            saveFile(result);
        } catch (IOException e) {
            LOGGER.error("error when download, ex:", e);
        }  finally {
            if (null != result) {
                try {
                    result.close();
                } catch (IOException e) {
                    LOGGER.error("error when close YosDownloadInputStream, ex:", e);
                }
            }
        }
        // TODO: test validations
    }

    /**
     * 结算记录查询
     *
     *
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void recordsQueryTest() throws YopClientException {
        RecordsQueryRequest request = new RecordsQueryRequest();
        request.setParentMerchantNo("parentMerchantNo_example");
        request.setMerchantNo("merchantNo_example");
        request.setSettleRequestNo("settleRequestNo_example");
        request.setSettleRequestBeginTime("2023-05-07 10:49:05");
        request.setSettleRequestEndTime("2023-05-07 10:49:05");
        RecordsQueryResponse response = api.recordsQuery(request);
        LOGGER.info("result:{}", response.getResult());
        // TODO: test validations
    }

    /**
     * 自助结算申请
     *
     * 支持商户发起自助结算申请。
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void selfSettleApplyTest() throws YopClientException {
        SelfSettleApplyRequest request = new SelfSettleApplyRequest();
        request.setParentMerchantNo("parentMerchantNo_example");
        request.setMerchantNo("merchantNo_example");
        request.setSettleRequestNo("settleRequestNo_example");
        request.setOperatePeriod("operatePeriod_example");
        request.setEndTime("2023-05-07 10:49:05");
        request.setNotifyUrl("notifyUrl_example");
        request.setBankRemark("bankRemark_example");
        SelfSettleApplyResponse response = api.selfSettleApply(request);
        LOGGER.info("result:{}", response.getResult());
        // TODO: test validations
    }

    /**
     * 新增结算卡
     *
     *
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void settleCardAddTest() throws YopClientException {
        SettleCardAddRequest request = new SettleCardAddRequest();
        request.setParentMerchantNo("parentMerchantNo_example");
        request.setMerchantNo("10040062484");
        request.setBankCardNo("bankCardNo_example");
        request.setBankCardType("bankCardType_example");
        request.setBankCode("bankCode_example");
        request.setDefaultSettleCard(true);
        SettleCardAddResponse response = api.settleCardAdd(request);
        LOGGER.info("result:{}", response.getResult());
        // TODO: test validations
    }

    /**
     * 修改结算卡
     *
     *
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void settleCardModifyTest() throws YopClientException {
        SettleCardModifyRequest request = new SettleCardModifyRequest();
        request.setParentMerchantNo("parentMerchantNo_example");
        request.setMerchantNo("10040062484");
        request.setBankCardNo("bankCardNo_example");
        request.setBankCardType("bankCardType_example");
        request.setBankCode("bankCode_example");
        request.setBrancgCode("brancgCode_example");
        request.setDefaultSettleCard(true);
        SettleCardModifyResponse response = api.settleCardModify(request);
        LOGGER.info("result:{}", response.getResult());
        // TODO: test validations
    }

    /**
     * 修改结算方向比例
     *
     *
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void settleWayModifyRatioTest() throws YopClientException {
        SettleWayModifyRatioRequest request = new SettleWayModifyRatioRequest();
        request.setBody(new SettleWayModifyRatioModifySettleWayRatioRequestDtoParam());
        SettleWayModifyRatioResponse response = api.settleWayModifyRatio(request);
        LOGGER.info("result:{}", response.getResult());
        // TODO: test validations
    }

    /**
     * 查询结算账户
     *
     *
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void settleWayQueryTest() throws YopClientException {
        SettleWayQueryRequest request = new SettleWayQueryRequest();
        request.setParentMerchantNo("parentMerchantNo_example");
        request.setMerchantNo("10040062484");
        SettleWayQueryResponse response = api.settleWayQuery(request);
        LOGGER.info("result:{}", response.getResult());
        // TODO: test validations
    }


    private void saveFile(YosDownloadInputStream in) throws IOException {
        //todo save
        LOGGER.debug(IOUtils.toString(in, "UTF-8"));
    }
}
