/*
 * 无卡交易系统
 * <p>中台的无卡交易系统(Card Not Present)，包含调用统一订单OPR下单及无卡支付服务NCPAY支付的流程</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.cnppay;

import com.yeepay.yop.sdk.client.*;
import com.yeepay.yop.sdk.exception.YopClientException;
import com.yeepay.yop.sdk.http.HttpResponseAnalyzerSupport;
import com.yeepay.yop.sdk.http.HttpResponseHandler;
import com.yeepay.yop.sdk.http.handler.DefaultHttpResponseHandler;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;
import com.yeepay.yop.sdk.service.cnppay.request.*;
import com.yeepay.yop.sdk.service.cnppay.response.*;

public class CnppayClientImpl implements CnppayClient {

    private final ClientHandler clientHandler;

    CnppayClientImpl(ClientParams clientParams) {
        this.clientHandler = new ClientHandlerImpl(new ClientHandlerParams().withClientParams(clientParams));
    }

    @Override
    public InstallmentPayRequestResponse installmentPayRequest(InstallmentPayRequestRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<InstallmentPayRequestRequest> requestMarshaller = InstallmentPayRequestRequestMarshaller.getInstance();
        HttpResponseHandler<InstallmentPayRequestResponse> responseHandler =
                new DefaultHttpResponseHandler<InstallmentPayRequestResponse>(InstallmentPayRequestResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<InstallmentPayRequestRequest, InstallmentPayRequestResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public InstallmentQuerybankcfgResponse installmentQuerybankcfg(InstallmentQuerybankcfgRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        if(request.getMerchantNo() == null){
            throw new YopClientException("request.merchantNo is required.");
        }
        RequestMarshaller<InstallmentQuerybankcfgRequest> requestMarshaller = InstallmentQuerybankcfgRequestMarshaller.getInstance();
        HttpResponseHandler<InstallmentQuerybankcfgResponse> responseHandler =
                new DefaultHttpResponseHandler<InstallmentQuerybankcfgResponse>(InstallmentQuerybankcfgResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<InstallmentQuerybankcfgRequest, InstallmentQuerybankcfgResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }

    @Override
    public void shutdown() {
        clientHandler.shutdown();
    }

}
