/*
 * 线下业务
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.offline.response;





import com.yeepay.yop.sdk.model.BaseResponse;

import com.yeepay.yop.sdk.service.offline.model.YopGetShopRspDTO;

public class GetShopResponse extends BaseResponse {
    private static final long serialVersionUID = 1L;

    private YopGetShopRspDTO result;

    public YopGetShopRspDTO getResult() {
        return result;
    }

    public void setResult(YopGetShopRspDTO result) {
        this.result = result;
    }

}
