/*
 * 子商户管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.mer.request;

import com.yeepay.yop.sdk.model.BaseRequest;
public class MerchantInfoModifyRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String requestNo;

    private String merchantNo;

    private String notifyUrl;

    private String merchantSubjectInfo;

    private String merchantCorporationInfo;

    private String merchantContactInfo;

    private String industryCategoryInfo;

    private String businessAddressInfo;

    private String accountInfo;

    private String bankToken;


    /**
     * Get requestNo
     * @return requestNo
     **/
    
    public String getRequestNo() {
        return requestNo;
    }

    public void setRequestNo(String requestNo) {
        this.requestNo = requestNo;
    }

    /**
     * Get merchantNo
     * @return merchantNo
     **/
    
    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    /**
     * Get notifyUrl
     * @return notifyUrl
     **/
    
    public String getNotifyUrl() {
        return notifyUrl;
    }

    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * Get merchantSubjectInfo
     * @return merchantSubjectInfo
     **/
    
    public String getMerchantSubjectInfo() {
        return merchantSubjectInfo;
    }

    public void setMerchantSubjectInfo(String merchantSubjectInfo) {
        this.merchantSubjectInfo = merchantSubjectInfo;
    }

    /**
     * Get merchantCorporationInfo
     * @return merchantCorporationInfo
     **/
    
    public String getMerchantCorporationInfo() {
        return merchantCorporationInfo;
    }

    public void setMerchantCorporationInfo(String merchantCorporationInfo) {
        this.merchantCorporationInfo = merchantCorporationInfo;
    }

    /**
     * Get merchantContactInfo
     * @return merchantContactInfo
     **/
    
    public String getMerchantContactInfo() {
        return merchantContactInfo;
    }

    public void setMerchantContactInfo(String merchantContactInfo) {
        this.merchantContactInfo = merchantContactInfo;
    }

    /**
     * Get industryCategoryInfo
     * @return industryCategoryInfo
     **/
    
    public String getIndustryCategoryInfo() {
        return industryCategoryInfo;
    }

    public void setIndustryCategoryInfo(String industryCategoryInfo) {
        this.industryCategoryInfo = industryCategoryInfo;
    }

    /**
     * Get businessAddressInfo
     * @return businessAddressInfo
     **/
    
    public String getBusinessAddressInfo() {
        return businessAddressInfo;
    }

    public void setBusinessAddressInfo(String businessAddressInfo) {
        this.businessAddressInfo = businessAddressInfo;
    }

    /**
     * Get accountInfo
     * @return accountInfo
     **/
    
    public String getAccountInfo() {
        return accountInfo;
    }

    public void setAccountInfo(String accountInfo) {
        this.accountInfo = accountInfo;
    }

    /**
     * Get bankToken
     * @return bankToken
     **/
    
    public String getBankToken() {
        return bankToken;
    }

    public void setBankToken(String bankToken) {
        this.bankToken = bankToken;
    }

    @Override
    public String getOperationId() {
        return "merchantInfoModify";
    }
}
