/*
 * 子商户管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.mer.request;

import com.yeepay.yop.sdk.YopConstants;
import com.yeepay.yop.sdk.http.Headers;
import com.yeepay.yop.sdk.http.HttpMethodName;
import com.yeepay.yop.sdk.http.YopContentType;
import com.yeepay.yop.sdk.internal.DefaultRequest;
import com.yeepay.yop.sdk.internal.Request;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;
import com.yeepay.yop.sdk.protocol.marshaller.PrimitiveMarshallerUtils;
import java.util.Map;
import java.util.UUID;
import java.util.Iterator;
import org.apache.commons.lang3.BooleanUtils;


public class ProductFeeModifyV2RequestMarshaller implements RequestMarshaller<ProductFeeModifyV2Request> {
    private final String serviceName = "Mer";

    private final String resourcePath = "/rest/v2.0/mer/product/fee/modify";

    private final String contentType = "application/x-www-form-urlencoded";

    private final HttpMethodName httpMethodName = HttpMethodName.POST;


    @Override
    public Request<ProductFeeModifyV2Request> marshall(ProductFeeModifyV2Request request) {
        Request<ProductFeeModifyV2Request> internalRequest = new DefaultRequest<ProductFeeModifyV2Request>(request, serviceName);
        internalRequest.setResourcePath(resourcePath);
        internalRequest.setHttpMethod(httpMethodName);
        if (!internalRequest.getHeaders().containsKey(Headers.YOP_REQUEST_ID)) {
            String requestId = UUID.randomUUID().toString();
            internalRequest.addHeader(Headers.YOP_REQUEST_ID, requestId);
        }
        Map<String, String> customerHeaders = request.getHeaders();
        if (customerHeaders != null) {
            for (String key : customerHeaders.keySet()) {
                internalRequest.addHeader(key, customerHeaders.get(key));
            }
        }
        if (request.getRequestNo() != null) {
            internalRequest.addParameter("requestNo", PrimitiveMarshallerUtils.marshalling(request.getRequestNo(), "String"));
        }
        if (request.getParentMerchantNo() != null) {
            internalRequest.addParameter("parentMerchantNo", PrimitiveMarshallerUtils.marshalling(request.getParentMerchantNo(), "String"));
        }
        if (request.getMerchantNo() != null) {
            internalRequest.addParameter("merchantNo", PrimitiveMarshallerUtils.marshalling(request.getMerchantNo(), "String"));
        }
        if (request.getNotifyUrl() != null) {
            internalRequest.addParameter("notifyUrl", PrimitiveMarshallerUtils.marshalling(request.getNotifyUrl(), "String"));
        }
        if (request.getProductInfo() != null) {
            internalRequest.addParameter("productInfo", PrimitiveMarshallerUtils.marshalling(request.getProductInfo(), "String"));
        }
        if (request.getProductQualificationInfo() != null) {
            internalRequest.addParameter("productQualificationInfo", PrimitiveMarshallerUtils.marshalling(request.getProductQualificationInfo(), "String"));
        }
        if (request.getSettlementAccountInfo() != null) {
            internalRequest.addParameter("settlementAccountInfo", PrimitiveMarshallerUtils.marshalling(request.getSettlementAccountInfo(), "String"));
        }
        if (request.getFunctionService() != null) {
            internalRequest.addParameter("functionService", PrimitiveMarshallerUtils.marshalling(request.getFunctionService(), "String"));
        }
        if (request.getFunctionServiceQualificationInfo() != null) {
            internalRequest.addParameter("functionServiceQualificationInfo", PrimitiveMarshallerUtils.marshalling(request.getFunctionServiceQualificationInfo(), "String"));
        }
        internalRequest.setContentType(YopContentType.FORM_URL_ENCODE);
        internalRequest.addHeader(Headers.CONTENT_TYPE, internalRequest.getContentType().getValue());
        return internalRequest;
    }


    private static class CacheInstanceHolder {
        public static ProductFeeModifyV2RequestMarshaller INSTANCE = new ProductFeeModifyV2RequestMarshaller();

        private CacheInstanceHolder() {
        }
    }

    public static ProductFeeModifyV2RequestMarshaller getInstance() {
        return CacheInstanceHolder.INSTANCE;
    }
}
