/*
 * 标准版
 * <p>标准版</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.std.request;

import com.yeepay.yop.sdk.model.BaseRequest;
public class CertOrderRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String merchantNo;

    private String authType;

    private String requestNo;

    private String idCardNo;

    private String userName;

    private String bankCardNo;

    private String requestTime;

    private String remark;

    private String mobilePhone;

    private String idCardType;

    private String clientSource;

    private String extMap;


    /**
     * Get merchantNo
     * @return merchantNo
     **/
    
    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    /**
     * Get authType
     * @return authType
     **/
    
    public String getAuthType() {
        return authType;
    }

    public void setAuthType(String authType) {
        this.authType = authType;
    }

    /**
     * Get requestNo
     * @return requestNo
     **/
    
    public String getRequestNo() {
        return requestNo;
    }

    public void setRequestNo(String requestNo) {
        this.requestNo = requestNo;
    }

    /**
     * Get idCardNo
     * @return idCardNo
     **/
    
    public String getIdCardNo() {
        return idCardNo;
    }

    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }

    /**
     * Get userName
     * @return userName
     **/
    
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Get bankCardNo
     * @return bankCardNo
     **/
    
    public String getBankCardNo() {
        return bankCardNo;
    }

    public void setBankCardNo(String bankCardNo) {
        this.bankCardNo = bankCardNo;
    }

    /**
     * Get requestTime
     * @return requestTime
     **/
    
    public String getRequestTime() {
        return requestTime;
    }

    public void setRequestTime(String requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * Get remark
     * @return remark
     **/
    
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * Get mobilePhone
     * @return mobilePhone
     **/
    
    public String getMobilePhone() {
        return mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * Get idCardType
     * @return idCardType
     **/
    
    public String getIdCardType() {
        return idCardType;
    }

    public void setIdCardType(String idCardType) {
        this.idCardType = idCardType;
    }

    /**
     * Get clientSource
     * @return clientSource
     **/
    
    public String getClientSource() {
        return clientSource;
    }

    public void setClientSource(String clientSource) {
        this.clientSource = clientSource;
    }

    /**
     * Get extMap
     * @return extMap
     **/
    
    public String getExtMap() {
        return extMap;
    }

    public void setExtMap(String extMap) {
        this.extMap = extMap;
    }

    @Override
    public String getOperationId() {
        return "certOrder";
    }
}
