/*
 * 前置收银台
 * <p>前置收银台</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.frontcashier.request;

import com.yeepay.yop.sdk.model.BaseRequest;
import com.yeepay.yop.sdk.service.frontcashier.model.UpopActivescanQuerypayresultOpenQueryActiveScanPayResultRequestDTOParam;
public class UpopActivescanQuerypayresultRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private UpopActivescanQuerypayresultOpenQueryActiveScanPayResultRequestDTOParam body;


    /**
     * Get body
     * @return body
     **/
    
    public UpopActivescanQuerypayresultOpenQueryActiveScanPayResultRequestDTOParam getBody() {
        return body;
    }

    public void setBody(UpopActivescanQuerypayresultOpenQueryActiveScanPayResultRequestDTOParam body) {
        this.body = body;
    }

    @Override
    public String getOperationId() {
        return "upopActivescanQuerypayresult";
    }
}
