/*
 * 前置收银台
 * <p>前置收银台</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.frontcashier.request;

import com.yeepay.yop.sdk.model.BaseRequest;
import java.math.BigDecimal;
public class UpopPassivescanValidateRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String merchantFlowId;

    private String payOrderNo;

    private String couponInfo;

    private BigDecimal realTradeAmount;


    /**
     * Get merchantFlowId
     * @return merchantFlowId
     **/
    
    public String getMerchantFlowId() {
        return merchantFlowId;
    }

    public void setMerchantFlowId(String merchantFlowId) {
        this.merchantFlowId = merchantFlowId;
    }

    /**
     * Get payOrderNo
     * @return payOrderNo
     **/
    
    public String getPayOrderNo() {
        return payOrderNo;
    }

    public void setPayOrderNo(String payOrderNo) {
        this.payOrderNo = payOrderNo;
    }

    /**
     * Get couponInfo
     * @return couponInfo
     **/
    
    public String getCouponInfo() {
        return couponInfo;
    }

    public void setCouponInfo(String couponInfo) {
        this.couponInfo = couponInfo;
    }

    /**
     * Get realTradeAmount
     * @return realTradeAmount
     **/
    
    public BigDecimal getRealTradeAmount() {
        return realTradeAmount;
    }

    public void setRealTradeAmount(BigDecimal realTradeAmount) {
        this.realTradeAmount = realTradeAmount;
    }

    @Override
    public String getOperationId() {
        return "upopPassivescanValidate";
    }
}
