/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.m_wallet.response;





import com.yeepay.yop.sdk.model.BaseResponse;

import com.yeepay.yop.sdk.service.m_wallet.model.YopQueryMemberBalanceQuotaRespDTO;

public class AccountQueryQuotaResponse extends BaseResponse {
    private static final long serialVersionUID = 1L;

    private YopQueryMemberBalanceQuotaRespDTO result;

    public YopQueryMemberBalanceQuotaRespDTO getResult() {
        return result;
    }

    public void setResult(YopQueryMemberBalanceQuotaRespDTO result) {
        this.result = result;
    }

}
