/*
 * 无卡交易系统
 * <p>中台的无卡交易系统(Card Not Present)，包含调用统一订单OPR下单及无卡支付服务NCPAY支付的流程</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.cnppay;

import com.yeepay.yop.sdk.exception.YopClientException;
import com.yeepay.yop.sdk.service.cnppay.request.*;
import com.yeepay.yop.sdk.service.cnppay.response.*;
import java.math.BigDecimal;
import com.yeepay.yop.sdk.service.cnppay.model.InstallmentPayRequestInstallmentPayResponseDTOResult;
import com.yeepay.yop.sdk.service.cnppay.model.InstallmentQuerybankcfgInstallmentBankCfgResponseDTOResult;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import org.junit.Test;
import org.junit.Ignore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
/**
 * API tests for CnppayClient
 */
@Ignore
public class CnppayClientTest {

    private static final Logger LOGGER = LoggerFactory.getLogger(CnppayClientTest.class);

    // 该Client线程安全，请使用单例模式，多次请求共用
    private final CnppayClient api = CnppayClientBuilder.builder().build();

    
    /**
     * 分期支付统一下单
     *
     * 
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void installmentPayRequestTest() throws YopClientException {
        InstallmentPayRequestRequest request = new InstallmentPayRequestRequest();
        request.setParentMerchantNo("10012345677");
        request.setMerchantNo("10012345677");
        request.setOrderAmount(new BigDecimal("0"));
        request.setOrderId("221007104428249784269");
        request.setFundProcessType("fundProcessType_example");
        request.setBankId("bankId_example");
        request.setExpireTime("expireTime_example");
        request.setGoodsName("goodsName_example");
        request.setNumOfInstallment(56);
        request.setRiskInfo("riskInfo_example");
        request.setRedirectUrl("redirectUrl_example");
        request.setNotifyUrl("notifyUrl_example");
        request.setCsUrl("csUrl_example");
        request.setMemo("memo_example");
        InstallmentPayRequestResponse response = api.installmentPayRequest(request);
        LOGGER.info("result:{}", response.getResult());
        // TODO: test validations
    }
    
    /**
     * 分期支付商户支持银行信息查询
     *
     * 
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void installmentQuerybankcfgTest() throws YopClientException {
        InstallmentQuerybankcfgRequest request = new InstallmentQuerybankcfgRequest();
        request.setParentMerchantNo("parentMerchantNo_example");
        request.setMerchantNo("10012345677");
        InstallmentQuerybankcfgResponse response = api.installmentQuerybankcfg(request);
        LOGGER.info("result:{}", response.getResult());
        // TODO: test validations
    }
    

}
