/*
 * 商户结算2.0
 * <p><a href=\"http://wiki.yeepay.com/pages/viewpage.action?pageId=112010456\">http://wiki.yeepay.com/pages/viewpage.action?pageId=112010456</a></p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.settle.request;

import com.yeepay.yop.sdk.YopConstants;
import com.yeepay.yop.sdk.http.Headers;
import com.yeepay.yop.sdk.http.HttpMethodName;
import com.yeepay.yop.sdk.http.YopContentType;
import com.yeepay.yop.sdk.internal.DefaultRequest;
import com.yeepay.yop.sdk.internal.Request;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;
import com.yeepay.yop.sdk.protocol.marshaller.PrimitiveMarshallerUtils;
import java.util.Map;
import java.util.UUID;
import java.util.Iterator;
import org.apache.commons.lang3.BooleanUtils;


public class SettleCardAddRequestMarshaller implements RequestMarshaller<SettleCardAddRequest> {
    private final String serviceName = "Settle";

    private final String resourcePath = "/rest/v1.0/settle/settle-card/add";

    private final String contentType = "application/x-www-form-urlencoded";

    private final HttpMethodName httpMethodName = HttpMethodName.POST;


    @Override
    public Request<SettleCardAddRequest> marshall(SettleCardAddRequest request) {
        Request<SettleCardAddRequest> internalRequest = new DefaultRequest<SettleCardAddRequest>(request, serviceName);
        internalRequest.setResourcePath(resourcePath);
        internalRequest.setHttpMethod(httpMethodName);
        if (!internalRequest.getHeaders().containsKey(Headers.YOP_REQUEST_ID)) {
            String requestId = UUID.randomUUID().toString();
            internalRequest.addHeader(Headers.YOP_REQUEST_ID, requestId);
        }
        Map<String, String> customerHeaders = request.getHeaders();
        if (customerHeaders != null) {
            for (String key : customerHeaders.keySet()) {
                internalRequest.addHeader(key, customerHeaders.get(key));
            }
        }
        if (request.getParentMerchantNo() != null) {
            internalRequest.addParameter("parentMerchantNo", PrimitiveMarshallerUtils.marshalling(request.getParentMerchantNo(), "String"));
        }
        if (request.getMerchantNo() != null) {
            internalRequest.addParameter("merchantNo", PrimitiveMarshallerUtils.marshalling(request.getMerchantNo(), "String"));
        }
        if (request.getBankCardNo() != null) {
            internalRequest.addParameter("bankCardNo", PrimitiveMarshallerUtils.marshalling(request.getBankCardNo(), "String"));
        }
        if (request.getBankCardType() != null) {
            internalRequest.addParameter("bankCardType", PrimitiveMarshallerUtils.marshalling(request.getBankCardType(), "String"));
        }
        if (request.getBankCode() != null) {
            internalRequest.addParameter("bankCode", PrimitiveMarshallerUtils.marshalling(request.getBankCode(), "String"));
        }
        if (request.getDefaultSettleCard() != null) {
            internalRequest.addParameter("defaultSettleCard", PrimitiveMarshallerUtils.marshalling(request.getDefaultSettleCard(), "Boolean"));
        }
        internalRequest.setContentType(YopContentType.FORM_URL_ENCODE);
        internalRequest.addHeader(Headers.CONTENT_TYPE, internalRequest.getContentType().getValue());
        return internalRequest;
    }


    private static class CacheInstanceHolder {
        public static SettleCardAddRequestMarshaller INSTANCE = new SettleCardAddRequestMarshaller();

        private CacheInstanceHolder() {
        }
    }

    public static SettleCardAddRequestMarshaller getInstance() {
        return CacheInstanceHolder.INSTANCE;
    }
}
