/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.account.request;

import com.yeepay.yop.sdk.model.BaseRequest;
public class AccountIndividualApplyRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String merchantNo;

    private String requestNo;

    private String name;

      /**
   * Gets or Sets 
   */
  public enum CertificateTypeEnum {
    IDCARD("IDCARD");

    private String value;

    CertificateTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CertificateTypeEnum fromValue(String text) {
      for (CertificateTypeEnum b : CertificateTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

    private CertificateTypeEnum certificateType;

    private String certificateNo;

    private String phone;

    private String frontUrl;

    private String contraryUrl;


    /**
     * Get merchantNo
     * @return merchantNo
     **/
    
    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    /**
     * Get requestNo
     * @return requestNo
     **/
    
    public String getRequestNo() {
        return requestNo;
    }

    public void setRequestNo(String requestNo) {
        this.requestNo = requestNo;
    }

    /**
     * Get name
     * @return name
     **/
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get certificateType
     * @return certificateType
     **/
    
    public CertificateTypeEnum getCertificateType() {
        return certificateType;
    }

    public void setCertificateType(CertificateTypeEnum certificateType) {
        this.certificateType = certificateType;
    }

    /**
     * Get certificateNo
     * @return certificateNo
     **/
    
    public String getCertificateNo() {
        return certificateNo;
    }

    public void setCertificateNo(String certificateNo) {
        this.certificateNo = certificateNo;
    }

    /**
     * Get phone
     * @return phone
     **/
    
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Get frontUrl
     * @return frontUrl
     **/
    
    public String getFrontUrl() {
        return frontUrl;
    }

    public void setFrontUrl(String frontUrl) {
        this.frontUrl = frontUrl;
    }

    /**
     * Get contraryUrl
     * @return contraryUrl
     **/
    
    public String getContraryUrl() {
        return contraryUrl;
    }

    public void setContraryUrl(String contraryUrl) {
        this.contraryUrl = contraryUrl;
    }

    @Override
    public String getOperationId() {
        return "account_individual_apply";
    }
}
