/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.account.request;

import com.yeepay.yop.sdk.model.BaseRequest;
import java.math.BigDecimal;
public class EnterpriseAutoPaymentOrderRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String merchantNo;

    private String orderId;

    private BigDecimal orderAmount;

    private String fundProcessType;

    private String goodsName;

    private String expiredTime;

    private String notifyUrl;

    private String memo;

    private String payerNotifyUrl;

    private String csUrl;


    /**
     * Get merchantNo
     * @return merchantNo
     **/
    
    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    /**
     * Get orderId
     * @return orderId
     **/
    
    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * Get orderAmount
     * @return orderAmount
     **/
    
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * Get fundProcessType
     * @return fundProcessType
     **/
    
    public String getFundProcessType() {
        return fundProcessType;
    }

    public void setFundProcessType(String fundProcessType) {
        this.fundProcessType = fundProcessType;
    }

    /**
     * Get goodsName
     * @return goodsName
     **/
    
    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * Get expiredTime
     * @return expiredTime
     **/
    
    public String getExpiredTime() {
        return expiredTime;
    }

    public void setExpiredTime(String expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * Get notifyUrl
     * @return notifyUrl
     **/
    
    public String getNotifyUrl() {
        return notifyUrl;
    }

    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * Get memo
     * @return memo
     **/
    
    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * Get payerNotifyUrl
     * @return payerNotifyUrl
     **/
    
    public String getPayerNotifyUrl() {
        return payerNotifyUrl;
    }

    public void setPayerNotifyUrl(String payerNotifyUrl) {
        this.payerNotifyUrl = payerNotifyUrl;
    }

    /**
     * Get csUrl
     * @return csUrl
     **/
    
    public String getCsUrl() {
        return csUrl;
    }

    public void setCsUrl(String csUrl) {
        this.csUrl = csUrl;
    }

    @Override
    public String getOperationId() {
        return "enterpriseAutoPaymentOrder";
    }
}
