/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.account.request;

import com.yeepay.yop.sdk.model.BaseRequest;
public class ReceiptGetRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String parentMerchantNo;

    private String tradeType;

    private String orderNo;

    private String requestNo;

    private String orderDate;

    private String merchantNo;


    /**
     * 发起方商户编号&lt;br&gt;（标准商户收付款方案中此参数与商编一致，平台商户收付款方案中此参数为平台商商户编号）
     * @return parentMerchantNo
     **/
    
    public String getParentMerchantNo() {
        return parentMerchantNo;
    }

    public void setParentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
    }

    /**
     * 可选项如下:&lt;br&gt;TRANSFER:企业账户转账&lt;br&gt;PAY:企业付款&lt;br&gt;RECHARGE:企业账户充值&lt;br&gt;WITHDRAW:企业账户提现&lt;br&gt;ADVANCE:记账薄收款
     * @return tradeType
     **/
    
    public String getTradeType() {
        return tradeType;
    }

    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * 易宝支付系统生成的付款订单号（与商户请求号两者填其一）
     * @return orderNo
     **/
    
    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * 商户请求号&lt;br&gt;商户请求号，由商户自定义生成（与易宝付款订单号两者填其一）
     * @return requestNo
     **/
    
    public String getRequestNo() {
        return requestNo;
    }

    public void setRequestNo(String requestNo) {
        this.requestNo = requestNo;
    }

    /**
     * 如果传了商户请求号requestNo，orderDate也是必填的，格式 yyyy-MM/yyyy-MM-dd
     * @return orderDate
     **/
    
    public String getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * 商户编号，易宝支付分配的的商户唯一标识，如果传了商户请求号requestNo，那么merchantNo也是必填的。
     * @return merchantNo
     **/
    
    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    @Override
    public String getOperationId() {
        return "receiptGet";
    }
}
