/*
 * 前置收银台
 * <p>前置收银台</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.frontcashier.response;





import com.yeepay.yop.sdk.model.BaseResponse;

import com.yeepay.yop.sdk.service.frontcashier.model.BindcardGetcardbinOpenQueryCardbinResponseDTOResult;

public class BindcardGetcardbinResponse extends BaseResponse {
    private static final long serialVersionUID = 1L;

    private BindcardGetcardbinOpenQueryCardbinResponseDTOResult result;

    public BindcardGetcardbinOpenQueryCardbinResponseDTOResult getResult() {
        return result;
    }

    public void setResult(BindcardGetcardbinOpenQueryCardbinResponseDTOResult result) {
        this.result = result;
    }

}
