/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.m_wallet.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * AgreementPaymentSignRequestURLResponseDTOResult
 */
public class AgreementPaymentSignRequestURLResponseDTOResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 返回码
   */
  @JsonProperty("code")
  private String code = null;

  /**
   * 返回信息
   */
  @JsonProperty("message")
  private String message = null;

  /**
   * 验密签约确认控件URL
   */
  @JsonProperty("url")
  private String url = null;

  public AgreementPaymentSignRequestURLResponseDTOResult code(String code) {
    this.code = code;
    return this;
  }

   /**
   * 返回码
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public AgreementPaymentSignRequestURLResponseDTOResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * 返回信息
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public AgreementPaymentSignRequestURLResponseDTOResult url(String url) {
    this.url = url;
    return this;
  }

   /**
   * 验密签约确认控件URL
   * @return url
  **/

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    AgreementPaymentSignRequestURLResponseDTOResult agreementPaymentSignRequestURLResponseDTOResult = (AgreementPaymentSignRequestURLResponseDTOResult) o;
    return ObjectUtils.equals(this.code, agreementPaymentSignRequestURLResponseDTOResult.code) &&
    ObjectUtils.equals(this.message, agreementPaymentSignRequestURLResponseDTOResult.message) &&
    ObjectUtils.equals(this.url, agreementPaymentSignRequestURLResponseDTOResult.url);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementPaymentSignRequestURLResponseDTOResult {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

