/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.m_wallet.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * 请修改我
 */
public class AutoDeductionResponseDTO implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   *
   */
  @JsonProperty("code")
  private String code = null;

  /**
   *
   */
  @JsonProperty("message")
  private String message = null;

  /**
   *
   */
  @JsonProperty("requestNo")
  private String requestNo = null;

  /**
   *
   */
  @JsonProperty("status")
  private String status = null;

  public AutoDeductionResponseDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public AutoDeductionResponseDTO message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public AutoDeductionResponseDTO requestNo(String requestNo) {
    this.requestNo = requestNo;
    return this;
  }

   /**
   * Get requestNo
   * @return requestNo
  **/

  public String getRequestNo() {
    return requestNo;
  }

  public void setRequestNo(String requestNo) {
    this.requestNo = requestNo;
  }

  public AutoDeductionResponseDTO status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    AutoDeductionResponseDTO autoDeductionResponseDTO = (AutoDeductionResponseDTO) o;
    return ObjectUtils.equals(this.code, autoDeductionResponseDTO.code) &&
    ObjectUtils.equals(this.message, autoDeductionResponseDTO.message) &&
    ObjectUtils.equals(this.requestNo, autoDeductionResponseDTO.requestNo) &&
    ObjectUtils.equals(this.status, autoDeductionResponseDTO.status);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, requestNo, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoDeductionResponseDTO {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    requestNo: ").append(toIndentedString(requestNo)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

