/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.m_wallet.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * 请修改我
 */
public class BillListDetailDto implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * &lt;p&gt;订单类型&lt;/p&gt; 可选项如下: WITHDRAW:提现 RECHARGE:充值 PAYMENT:支付 DIVIDE:分账 DIVIDE_REFUND:分账退回 REFUND:退款 PAYMENT_MANAGE:管理费 BONUS:红包
   */
  public enum OrderTypeEnum {
    WITHDRAW("WITHDRAW"),

    RECHARGE("RECHARGE"),

    PAYMENT("PAYMENT"),

    DIVIDE("DIVIDE"),

    DIVIDE_REFUND("DIVIDE_REFUND"),

    REFUND("REFUND"),

    PAYMENT_MANAGE("PAYMENT_MANAGE"),

    BONUS("BONUS");

    private String value;

    OrderTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OrderTypeEnum fromValue(String text) {
      for (OrderTypeEnum b : OrderTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  /**
   * &lt;p&gt;订单类型&lt;/p&gt; 可选项如下: WITHDRAW:提现 RECHARGE:充值 PAYMENT:支付 DIVIDE:分账 DIVIDE_REFUND:分账退回 REFUND:退款 PAYMENT_MANAGE:管理费 BONUS:红包
   */
  @JsonProperty("orderType")
  private OrderTypeEnum orderType = null;

  /**
   * &lt;p&gt;订单金额&lt;/p&gt;
   */
  @JsonProperty("amount")
  private String amount = null;

  /**
   * &lt;p&gt;订单创建时间&lt;/p&gt; &lt;pre&gt;yyyy-MM-dd HH:mm:ss&lt;/pre&gt;
   */
  @JsonProperty("createTime")
  private String createTime = null;

  /**
   *
   */
  @JsonProperty("uniqueOrderNo")
  private String uniqueOrderNo = null;

  /**
   *
   */
  @JsonProperty("productName")
  private String productName = null;

  /**
   * &lt;p&gt;订单状态&lt;/p&gt; 可选项如下: PROCESSING:处理中 SUCCESS:成功 FAIL:失败
   */
  public enum StatusEnum {
    PROCESSING("PROCESSING"),

    SUCCESS("SUCCESS"),

    FAIL("FAIL");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  /**
   * &lt;p&gt;订单状态&lt;/p&gt; 可选项如下: PROCESSING:处理中 SUCCESS:成功 FAIL:失败
   */
  @JsonProperty("status")
  private StatusEnum status = null;

  public BillListDetailDto orderType(OrderTypeEnum orderType) {
    this.orderType = orderType;
    return this;
  }

   /**
   * &lt;p&gt;订单类型&lt;/p&gt; 可选项如下: WITHDRAW:提现 RECHARGE:充值 PAYMENT:支付 DIVIDE:分账 DIVIDE_REFUND:分账退回 REFUND:退款 PAYMENT_MANAGE:管理费 BONUS:红包
   * @return orderType
  **/

  public OrderTypeEnum getOrderType() {
    return orderType;
  }

  public void setOrderType(OrderTypeEnum orderType) {
    this.orderType = orderType;
  }

  public BillListDetailDto amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * &lt;p&gt;订单金额&lt;/p&gt;
   * @return amount
  **/

  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public BillListDetailDto createTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * &lt;p&gt;订单创建时间&lt;/p&gt; &lt;pre&gt;yyyy-MM-dd HH:mm:ss&lt;/pre&gt;
   * @return createTime
  **/

  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public BillListDetailDto uniqueOrderNo(String uniqueOrderNo) {
    this.uniqueOrderNo = uniqueOrderNo;
    return this;
  }

   /**
   * Get uniqueOrderNo
   * @return uniqueOrderNo
  **/

  public String getUniqueOrderNo() {
    return uniqueOrderNo;
  }

  public void setUniqueOrderNo(String uniqueOrderNo) {
    this.uniqueOrderNo = uniqueOrderNo;
  }

  public BillListDetailDto productName(String productName) {
    this.productName = productName;
    return this;
  }

   /**
   * Get productName
   * @return productName
  **/

  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public BillListDetailDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * &lt;p&gt;订单状态&lt;/p&gt; 可选项如下: PROCESSING:处理中 SUCCESS:成功 FAIL:失败
   * @return status
  **/

  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    BillListDetailDto billListDetailDto = (BillListDetailDto) o;
    return ObjectUtils.equals(this.orderType, billListDetailDto.orderType) &&
    ObjectUtils.equals(this.amount, billListDetailDto.amount) &&
    ObjectUtils.equals(this.createTime, billListDetailDto.createTime) &&
    ObjectUtils.equals(this.uniqueOrderNo, billListDetailDto.uniqueOrderNo) &&
    ObjectUtils.equals(this.productName, billListDetailDto.productName) &&
    ObjectUtils.equals(this.status, billListDetailDto.status);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(orderType, amount, createTime, uniqueOrderNo, productName, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillListDetailDto {\n");

    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    uniqueOrderNo: ").append(toIndentedString(uniqueOrderNo)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

