/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.m_wallet.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * MemberQueryQueryMemberInfoResponseDTOResult
 */
public class MemberQueryQueryMemberInfoResponseDTOResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 返回码
   */
  @JsonProperty("code")
  private String code = null;

  /**
   * 返回信息
   */
  @JsonProperty("message")
  private String message = null;

  /**
   * 会员号
   */
  @JsonProperty("memberNo")
  private String memberNo = null;

  /**
   * 商户用户ID
   */
  @JsonProperty("externalUserId")
  private String externalUserId = null;

  /**
   * 钱包账户状态
   */
  @JsonProperty("walletStatus")
  private String walletStatus = null;

  /**
   * 钱包账户等级
   */
  @JsonProperty("walletCategory")
  private String walletCategory = null;

  /**
   * 续费状态
   */
  @JsonProperty("renewStatus")
  private String renewStatus = null;

  public MemberQueryQueryMemberInfoResponseDTOResult code(String code) {
    this.code = code;
    return this;
  }

   /**
   * 返回码
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public MemberQueryQueryMemberInfoResponseDTOResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * 返回信息
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public MemberQueryQueryMemberInfoResponseDTOResult memberNo(String memberNo) {
    this.memberNo = memberNo;
    return this;
  }

   /**
   * 会员号
   * @return memberNo
  **/

  public String getMemberNo() {
    return memberNo;
  }

  public void setMemberNo(String memberNo) {
    this.memberNo = memberNo;
  }

  public MemberQueryQueryMemberInfoResponseDTOResult externalUserId(String externalUserId) {
    this.externalUserId = externalUserId;
    return this;
  }

   /**
   * 商户用户ID
   * @return externalUserId
  **/

  public String getExternalUserId() {
    return externalUserId;
  }

  public void setExternalUserId(String externalUserId) {
    this.externalUserId = externalUserId;
  }

  public MemberQueryQueryMemberInfoResponseDTOResult walletStatus(String walletStatus) {
    this.walletStatus = walletStatus;
    return this;
  }

   /**
   * 钱包账户状态
   * @return walletStatus
  **/

  public String getWalletStatus() {
    return walletStatus;
  }

  public void setWalletStatus(String walletStatus) {
    this.walletStatus = walletStatus;
  }

  public MemberQueryQueryMemberInfoResponseDTOResult walletCategory(String walletCategory) {
    this.walletCategory = walletCategory;
    return this;
  }

   /**
   * 钱包账户等级
   * @return walletCategory
  **/

  public String getWalletCategory() {
    return walletCategory;
  }

  public void setWalletCategory(String walletCategory) {
    this.walletCategory = walletCategory;
  }

  public MemberQueryQueryMemberInfoResponseDTOResult renewStatus(String renewStatus) {
    this.renewStatus = renewStatus;
    return this;
  }

   /**
   * 续费状态
   * @return renewStatus
  **/

  public String getRenewStatus() {
    return renewStatus;
  }

  public void setRenewStatus(String renewStatus) {
    this.renewStatus = renewStatus;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    MemberQueryQueryMemberInfoResponseDTOResult memberQueryQueryMemberInfoResponseDTOResult = (MemberQueryQueryMemberInfoResponseDTOResult) o;
    return ObjectUtils.equals(this.code, memberQueryQueryMemberInfoResponseDTOResult.code) &&
    ObjectUtils.equals(this.message, memberQueryQueryMemberInfoResponseDTOResult.message) &&
    ObjectUtils.equals(this.memberNo, memberQueryQueryMemberInfoResponseDTOResult.memberNo) &&
    ObjectUtils.equals(this.externalUserId, memberQueryQueryMemberInfoResponseDTOResult.externalUserId) &&
    ObjectUtils.equals(this.walletStatus, memberQueryQueryMemberInfoResponseDTOResult.walletStatus) &&
    ObjectUtils.equals(this.walletCategory, memberQueryQueryMemberInfoResponseDTOResult.walletCategory) &&
    ObjectUtils.equals(this.renewStatus, memberQueryQueryMemberInfoResponseDTOResult.renewStatus);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, memberNo, externalUserId, walletStatus, walletCategory, renewStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemberQueryQueryMemberInfoResponseDTOResult {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    memberNo: ").append(toIndentedString(memberNo)).append("\n");
    sb.append("    externalUserId: ").append(toIndentedString(externalUserId)).append("\n");
    sb.append("    walletStatus: ").append(toIndentedString(walletStatus)).append("\n");
    sb.append("    walletCategory: ").append(toIndentedString(walletCategory)).append("\n");
    sb.append("    renewStatus: ").append(toIndentedString(renewStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

