/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.m_wallet.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.yeepay.yop.sdk.service.m_wallet.model.BindCardInfo;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * MemberQueryBindCardListResponseDTO
 */
public class MemberQueryBindCardListResponseDTO implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   *
   */
  @JsonProperty("code")
  private String code = null;

  /**
   *
   */
  @JsonProperty("message")
  private String message = null;

  /**
   *
   */
  @JsonProperty("bindCardInfoList")
  private List<BindCardInfo> bindCardInfoList = null;

  public MemberQueryBindCardListResponseDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public MemberQueryBindCardListResponseDTO message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public MemberQueryBindCardListResponseDTO bindCardInfoList(List<BindCardInfo> bindCardInfoList) {
    this.bindCardInfoList = bindCardInfoList;
    return this;
  }

  public MemberQueryBindCardListResponseDTO addBindCardInfoListItem(BindCardInfo bindCardInfoListItem) {
    if (this.bindCardInfoList == null) {
      this.bindCardInfoList = new ArrayList<>();
    }
    this.bindCardInfoList.add(bindCardInfoListItem);
    return this;
  }

   /**
   * Get bindCardInfoList
   * @return bindCardInfoList
  **/

  public List<BindCardInfo> getBindCardInfoList() {
    return bindCardInfoList;
  }

  public void setBindCardInfoList(List<BindCardInfo> bindCardInfoList) {
    this.bindCardInfoList = bindCardInfoList;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    MemberQueryBindCardListResponseDTO memberQueryBindCardListResponseDTO = (MemberQueryBindCardListResponseDTO) o;
    return ObjectUtils.equals(this.code, memberQueryBindCardListResponseDTO.code) &&
    ObjectUtils.equals(this.message, memberQueryBindCardListResponseDTO.message) &&
    ObjectUtils.equals(this.bindCardInfoList, memberQueryBindCardListResponseDTO.bindCardInfoList);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, bindCardInfoList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemberQueryBindCardListResponseDTO {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    bindCardInfoList: ").append(toIndentedString(bindCardInfoList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

