/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.m_wallet.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.io.Serializable;

/**
 * TransferB2cQueryQueryMGB2CResponseDTOResult
 */
public class TransferB2cQueryQueryMGB2CResponseDTOResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 返回码
   */
  @JsonProperty("code")
  private String code = null;

  /**
   * 返回信息
   */
  @JsonProperty("message")
  private String message = null;

  /**
   * 商户请求号
   */
  @JsonProperty("requestNo")
  private String requestNo = null;

  /**
   * 易宝订单号
   */
  @JsonProperty("businessNo")
  private String businessNo = null;

  /**
   * 转账订单金额
   */
  @JsonProperty("orderAmount")
  private BigDecimal orderAmount = null;

  /**
   * 转账订单状态
   */
  @JsonProperty("orderStatus")
  private String orderStatus = null;

  /**
   * 交易主体商编
   */
  @JsonProperty("fromMerchantNo")
  private String fromMerchantNo = null;

  /**
   * 转帐接收方平台商编
   */
  @JsonProperty("toMerchantNo")
  private String toMerchantNo = null;

  /**
   * 转出方易宝用户编号
   */
  @JsonProperty("toMemberNo")
  private String toMemberNo = null;

  public TransferB2cQueryQueryMGB2CResponseDTOResult code(String code) {
    this.code = code;
    return this;
  }

   /**
   * 返回码
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public TransferB2cQueryQueryMGB2CResponseDTOResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * 返回信息
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public TransferB2cQueryQueryMGB2CResponseDTOResult requestNo(String requestNo) {
    this.requestNo = requestNo;
    return this;
  }

   /**
   * 商户请求号
   * @return requestNo
  **/

  public String getRequestNo() {
    return requestNo;
  }

  public void setRequestNo(String requestNo) {
    this.requestNo = requestNo;
  }

  public TransferB2cQueryQueryMGB2CResponseDTOResult businessNo(String businessNo) {
    this.businessNo = businessNo;
    return this;
  }

   /**
   * 易宝订单号
   * @return businessNo
  **/

  public String getBusinessNo() {
    return businessNo;
  }

  public void setBusinessNo(String businessNo) {
    this.businessNo = businessNo;
  }

  public TransferB2cQueryQueryMGB2CResponseDTOResult orderAmount(BigDecimal orderAmount) {
    this.orderAmount = orderAmount;
    return this;
  }

   /**
   * 转账订单金额
   * @return orderAmount
  **/

  public BigDecimal getOrderAmount() {
    return orderAmount;
  }

  public void setOrderAmount(BigDecimal orderAmount) {
    this.orderAmount = orderAmount;
  }

  public TransferB2cQueryQueryMGB2CResponseDTOResult orderStatus(String orderStatus) {
    this.orderStatus = orderStatus;
    return this;
  }

   /**
   * 转账订单状态
   * @return orderStatus
  **/

  public String getOrderStatus() {
    return orderStatus;
  }

  public void setOrderStatus(String orderStatus) {
    this.orderStatus = orderStatus;
  }

  public TransferB2cQueryQueryMGB2CResponseDTOResult fromMerchantNo(String fromMerchantNo) {
    this.fromMerchantNo = fromMerchantNo;
    return this;
  }

   /**
   * 交易主体商编
   * @return fromMerchantNo
  **/

  public String getFromMerchantNo() {
    return fromMerchantNo;
  }

  public void setFromMerchantNo(String fromMerchantNo) {
    this.fromMerchantNo = fromMerchantNo;
  }

  public TransferB2cQueryQueryMGB2CResponseDTOResult toMerchantNo(String toMerchantNo) {
    this.toMerchantNo = toMerchantNo;
    return this;
  }

   /**
   * 转帐接收方平台商编
   * @return toMerchantNo
  **/

  public String getToMerchantNo() {
    return toMerchantNo;
  }

  public void setToMerchantNo(String toMerchantNo) {
    this.toMerchantNo = toMerchantNo;
  }

  public TransferB2cQueryQueryMGB2CResponseDTOResult toMemberNo(String toMemberNo) {
    this.toMemberNo = toMemberNo;
    return this;
  }

   /**
   * 转出方易宝用户编号
   * @return toMemberNo
  **/

  public String getToMemberNo() {
    return toMemberNo;
  }

  public void setToMemberNo(String toMemberNo) {
    this.toMemberNo = toMemberNo;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    TransferB2cQueryQueryMGB2CResponseDTOResult transferB2cQueryQueryMGB2CResponseDTOResult = (TransferB2cQueryQueryMGB2CResponseDTOResult) o;
    return ObjectUtils.equals(this.code, transferB2cQueryQueryMGB2CResponseDTOResult.code) &&
    ObjectUtils.equals(this.message, transferB2cQueryQueryMGB2CResponseDTOResult.message) &&
    ObjectUtils.equals(this.requestNo, transferB2cQueryQueryMGB2CResponseDTOResult.requestNo) &&
    ObjectUtils.equals(this.businessNo, transferB2cQueryQueryMGB2CResponseDTOResult.businessNo) &&
    ObjectUtils.equals(this.orderAmount, transferB2cQueryQueryMGB2CResponseDTOResult.orderAmount) &&
    ObjectUtils.equals(this.orderStatus, transferB2cQueryQueryMGB2CResponseDTOResult.orderStatus) &&
    ObjectUtils.equals(this.fromMerchantNo, transferB2cQueryQueryMGB2CResponseDTOResult.fromMerchantNo) &&
    ObjectUtils.equals(this.toMerchantNo, transferB2cQueryQueryMGB2CResponseDTOResult.toMerchantNo) &&
    ObjectUtils.equals(this.toMemberNo, transferB2cQueryQueryMGB2CResponseDTOResult.toMemberNo);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, requestNo, businessNo, orderAmount, orderStatus, fromMerchantNo, toMerchantNo, toMemberNo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferB2cQueryQueryMGB2CResponseDTOResult {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    requestNo: ").append(toIndentedString(requestNo)).append("\n");
    sb.append("    businessNo: ").append(toIndentedString(businessNo)).append("\n");
    sb.append("    orderAmount: ").append(toIndentedString(orderAmount)).append("\n");
    sb.append("    orderStatus: ").append(toIndentedString(orderStatus)).append("\n");
    sb.append("    fromMerchantNo: ").append(toIndentedString(fromMerchantNo)).append("\n");
    sb.append("    toMerchantNo: ").append(toIndentedString(toMerchantNo)).append("\n");
    sb.append("    toMemberNo: ").append(toIndentedString(toMemberNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

