/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.m_wallet.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * 请修改我
 */
public class WalletOpenByFaceResponseDTO implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * &lt;p&gt;返回码&lt;/p&gt;
   */
  @JsonProperty("code")
  private String code = null;

  /**
   * &lt;p&gt;返回消息&lt;br /&gt;返回码的详细说明&lt;/p&gt;
   */
  @JsonProperty("message")
  private String message = null;

  /**
   * &lt;p&gt;易宝订单号&lt;br /&gt;易宝生成的唯一订单号&lt;/p&gt;
   */
  @JsonProperty("businessNo")
  private String businessNo = null;

  /**
   * &lt;p&gt;钱包账户ID&lt;br /&gt;已开立成功的会员则返回同一钱包账户ID。用户在易宝钱包生成的唯一编号&lt;/p&gt;
   */
  @JsonProperty("walletUserNo")
  private String walletUserNo = null;

  /**
   * &lt;p&gt;钱包账户等级&lt;/p&gt; 可选项如下: ONE_CATEGORY:一类 TWO_CATEGORY:二类 THREE_CATEGORY:三类
   */
  public enum WalletCategoryEnum {
    ONE_CATEGORY("ONE_CATEGORY"),

    TWO_CATEGORY("TWO_CATEGORY"),

    THREE_CATEGORY("THREE_CATEGORY");

    private String value;

    WalletCategoryEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WalletCategoryEnum fromValue(String text) {
      for (WalletCategoryEnum b : WalletCategoryEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  /**
   * &lt;p&gt;钱包账户等级&lt;/p&gt; 可选项如下: ONE_CATEGORY:一类 TWO_CATEGORY:二类 THREE_CATEGORY:三类
   */
  @JsonProperty("walletCategory")
  private WalletCategoryEnum walletCategory = null;

  /**
   * &lt;p&gt;是否需要人脸识别&lt;/p&gt;
   */
  @JsonProperty("needVerifyFace")
  private Boolean needVerifyFace = null;

  /**
   * &lt;p&gt;人脸识别注册页面地址&lt;/p&gt;
   */
  @JsonProperty("url")
  private String url = null;

  public WalletOpenByFaceResponseDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * &lt;p&gt;返回码&lt;/p&gt;
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public WalletOpenByFaceResponseDTO message(String message) {
    this.message = message;
    return this;
  }

   /**
   * &lt;p&gt;返回消息&lt;br /&gt;返回码的详细说明&lt;/p&gt;
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public WalletOpenByFaceResponseDTO businessNo(String businessNo) {
    this.businessNo = businessNo;
    return this;
  }

   /**
   * &lt;p&gt;易宝订单号&lt;br /&gt;易宝生成的唯一订单号&lt;/p&gt;
   * @return businessNo
  **/

  public String getBusinessNo() {
    return businessNo;
  }

  public void setBusinessNo(String businessNo) {
    this.businessNo = businessNo;
  }

  public WalletOpenByFaceResponseDTO walletUserNo(String walletUserNo) {
    this.walletUserNo = walletUserNo;
    return this;
  }

   /**
   * &lt;p&gt;钱包账户ID&lt;br /&gt;已开立成功的会员则返回同一钱包账户ID。用户在易宝钱包生成的唯一编号&lt;/p&gt;
   * @return walletUserNo
  **/

  public String getWalletUserNo() {
    return walletUserNo;
  }

  public void setWalletUserNo(String walletUserNo) {
    this.walletUserNo = walletUserNo;
  }

  public WalletOpenByFaceResponseDTO walletCategory(WalletCategoryEnum walletCategory) {
    this.walletCategory = walletCategory;
    return this;
  }

   /**
   * &lt;p&gt;钱包账户等级&lt;/p&gt; 可选项如下: ONE_CATEGORY:一类 TWO_CATEGORY:二类 THREE_CATEGORY:三类
   * @return walletCategory
  **/

  public WalletCategoryEnum getWalletCategory() {
    return walletCategory;
  }

  public void setWalletCategory(WalletCategoryEnum walletCategory) {
    this.walletCategory = walletCategory;
  }

  public WalletOpenByFaceResponseDTO needVerifyFace(Boolean needVerifyFace) {
    this.needVerifyFace = needVerifyFace;
    return this;
  }

   /**
   * &lt;p&gt;是否需要人脸识别&lt;/p&gt;
   * @return needVerifyFace
  **/

  public Boolean isNeedVerifyFace() {
    return needVerifyFace;
  }

  public void setNeedVerifyFace(Boolean needVerifyFace) {
    this.needVerifyFace = needVerifyFace;
  }

  public WalletOpenByFaceResponseDTO url(String url) {
    this.url = url;
    return this;
  }

   /**
   * &lt;p&gt;人脸识别注册页面地址&lt;/p&gt;
   * @return url
  **/

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    WalletOpenByFaceResponseDTO walletOpenByFaceResponseDTO = (WalletOpenByFaceResponseDTO) o;
    return ObjectUtils.equals(this.code, walletOpenByFaceResponseDTO.code) &&
    ObjectUtils.equals(this.message, walletOpenByFaceResponseDTO.message) &&
    ObjectUtils.equals(this.businessNo, walletOpenByFaceResponseDTO.businessNo) &&
    ObjectUtils.equals(this.walletUserNo, walletOpenByFaceResponseDTO.walletUserNo) &&
    ObjectUtils.equals(this.walletCategory, walletOpenByFaceResponseDTO.walletCategory) &&
    ObjectUtils.equals(this.needVerifyFace, walletOpenByFaceResponseDTO.needVerifyFace) &&
    ObjectUtils.equals(this.url, walletOpenByFaceResponseDTO.url);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, businessNo, walletUserNo, walletCategory, needVerifyFace, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WalletOpenByFaceResponseDTO {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    businessNo: ").append(toIndentedString(businessNo)).append("\n");
    sb.append("    walletUserNo: ").append(toIndentedString(walletUserNo)).append("\n");
    sb.append("    walletCategory: ").append(toIndentedString(walletCategory)).append("\n");
    sb.append("    needVerifyFace: ").append(toIndentedString(needVerifyFace)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

