/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.m_wallet.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * 请修改我
 */
public class YopQueryMemberBalanceQuotaRespDTO implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * &lt;p&gt;返回码&lt;/p&gt; &lt;p&gt;调用结果处理成功时该字段为空&lt;/p&gt; &lt;p&gt;失败时见异常码对应表&lt;/p&gt;
   */
  @JsonProperty("code")
  private String code = null;

  /**
   * &lt;p&gt;返回消息&lt;br /&gt;返回码的详细说明&lt;/p&gt;
   */
  @JsonProperty("message")
  private String message = null;

  /**
   * &lt;p&gt;易宝会员编号&lt;/p&gt;
   */
  @JsonProperty("memberNo")
  private String memberNo = null;

  /**
   * &lt;p&gt;可用余额支付额度&lt;/p&gt; &lt;p&gt;精确至两位小数&amp;nbsp;&lt;/p&gt;
   */
  @JsonProperty("availableQuota")
  private String availableQuota = null;

  /**
   * &lt;div data-page-id&#x3D;\&quot;PAIVdmdabo9DDcxbHUWcsiHvn7b\&quot; data-docx-has-block-data&#x3D;\&quot;false\&quot;&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-SwCmda0owoqO0yxcH3icZwsvnCc\&quot;&gt;钱包账户等级&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-SwCmda0owoqO0yxcH3icZwsvnCc\&quot;&gt;可选项如下:&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-SwCmda0owoqO0yxcH3icZwsvnCc\&quot;&gt;ONE_CATEGORY:一类&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-SwCmda0owoqO0yxcH3icZwsvnCc\&quot;&gt;TWO_CATEGORY:二类&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-SwCmda0owoqO0yxcH3icZwsvnCc\&quot;&gt;THREE_CATEGORY:三类&lt;/div&gt; &lt;/div&gt;
   */
  @JsonProperty("memberCategory")
  private String memberCategory = null;

  /**
   * &lt;p&gt;余额支付总额度&lt;/p&gt; &lt;p&gt;精确至两位小数&amp;nbsp;&lt;/p&gt;
   */
  @JsonProperty("limitQuota")
  private String limitQuota = null;

  /**
   * &lt;p&gt;已使用的余额支付额度&lt;/p&gt; &lt;p&gt;精确至两位小数&lt;/p&gt;
   */
  @JsonProperty("usedQuota")
  private String usedQuota = null;

  public YopQueryMemberBalanceQuotaRespDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * &lt;p&gt;返回码&lt;/p&gt; &lt;p&gt;调用结果处理成功时该字段为空&lt;/p&gt; &lt;p&gt;失败时见异常码对应表&lt;/p&gt;
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public YopQueryMemberBalanceQuotaRespDTO message(String message) {
    this.message = message;
    return this;
  }

   /**
   * &lt;p&gt;返回消息&lt;br /&gt;返回码的详细说明&lt;/p&gt;
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public YopQueryMemberBalanceQuotaRespDTO memberNo(String memberNo) {
    this.memberNo = memberNo;
    return this;
  }

   /**
   * &lt;p&gt;易宝会员编号&lt;/p&gt;
   * @return memberNo
  **/

  public String getMemberNo() {
    return memberNo;
  }

  public void setMemberNo(String memberNo) {
    this.memberNo = memberNo;
  }

  public YopQueryMemberBalanceQuotaRespDTO availableQuota(String availableQuota) {
    this.availableQuota = availableQuota;
    return this;
  }

   /**
   * &lt;p&gt;可用余额支付额度&lt;/p&gt; &lt;p&gt;精确至两位小数&amp;nbsp;&lt;/p&gt;
   * @return availableQuota
  **/

  public String getAvailableQuota() {
    return availableQuota;
  }

  public void setAvailableQuota(String availableQuota) {
    this.availableQuota = availableQuota;
  }

  public YopQueryMemberBalanceQuotaRespDTO memberCategory(String memberCategory) {
    this.memberCategory = memberCategory;
    return this;
  }

   /**
   * &lt;div data-page-id&#x3D;\&quot;PAIVdmdabo9DDcxbHUWcsiHvn7b\&quot; data-docx-has-block-data&#x3D;\&quot;false\&quot;&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-SwCmda0owoqO0yxcH3icZwsvnCc\&quot;&gt;钱包账户等级&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-SwCmda0owoqO0yxcH3icZwsvnCc\&quot;&gt;可选项如下:&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-SwCmda0owoqO0yxcH3icZwsvnCc\&quot;&gt;ONE_CATEGORY:一类&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-SwCmda0owoqO0yxcH3icZwsvnCc\&quot;&gt;TWO_CATEGORY:二类&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-SwCmda0owoqO0yxcH3icZwsvnCc\&quot;&gt;THREE_CATEGORY:三类&lt;/div&gt; &lt;/div&gt;
   * @return memberCategory
  **/

  public String getMemberCategory() {
    return memberCategory;
  }

  public void setMemberCategory(String memberCategory) {
    this.memberCategory = memberCategory;
  }

  public YopQueryMemberBalanceQuotaRespDTO limitQuota(String limitQuota) {
    this.limitQuota = limitQuota;
    return this;
  }

   /**
   * &lt;p&gt;余额支付总额度&lt;/p&gt; &lt;p&gt;精确至两位小数&amp;nbsp;&lt;/p&gt;
   * @return limitQuota
  **/

  public String getLimitQuota() {
    return limitQuota;
  }

  public void setLimitQuota(String limitQuota) {
    this.limitQuota = limitQuota;
  }

  public YopQueryMemberBalanceQuotaRespDTO usedQuota(String usedQuota) {
    this.usedQuota = usedQuota;
    return this;
  }

   /**
   * &lt;p&gt;已使用的余额支付额度&lt;/p&gt; &lt;p&gt;精确至两位小数&lt;/p&gt;
   * @return usedQuota
  **/

  public String getUsedQuota() {
    return usedQuota;
  }

  public void setUsedQuota(String usedQuota) {
    this.usedQuota = usedQuota;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    YopQueryMemberBalanceQuotaRespDTO yopQueryMemberBalanceQuotaRespDTO = (YopQueryMemberBalanceQuotaRespDTO) o;
    return ObjectUtils.equals(this.code, yopQueryMemberBalanceQuotaRespDTO.code) &&
    ObjectUtils.equals(this.message, yopQueryMemberBalanceQuotaRespDTO.message) &&
    ObjectUtils.equals(this.memberNo, yopQueryMemberBalanceQuotaRespDTO.memberNo) &&
    ObjectUtils.equals(this.availableQuota, yopQueryMemberBalanceQuotaRespDTO.availableQuota) &&
    ObjectUtils.equals(this.memberCategory, yopQueryMemberBalanceQuotaRespDTO.memberCategory) &&
    ObjectUtils.equals(this.limitQuota, yopQueryMemberBalanceQuotaRespDTO.limitQuota) &&
    ObjectUtils.equals(this.usedQuota, yopQueryMemberBalanceQuotaRespDTO.usedQuota);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, memberNo, availableQuota, memberCategory, limitQuota, usedQuota);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class YopQueryMemberBalanceQuotaRespDTO {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    memberNo: ").append(toIndentedString(memberNo)).append("\n");
    sb.append("    availableQuota: ").append(toIndentedString(availableQuota)).append("\n");
    sb.append("    memberCategory: ").append(toIndentedString(memberCategory)).append("\n");
    sb.append("    limitQuota: ").append(toIndentedString(limitQuota)).append("\n");
    sb.append("    usedQuota: ").append(toIndentedString(usedQuota)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

