/*
 * 发票服务
 * <p>基于中台商户实际开票场景，提供给商户维护开票规则、票面信息，查询票面信息，申请开具手续费发票，查询开票记录，查询实收手续费金额的服务</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.invoice.request;

import com.yeepay.yop.sdk.model.BaseRequest;
public class ApplyRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String merchantNo;

    private String customerRequestNo;

    private String parentMerchantNo;

    private String chargingDateStart;

    private String chargingDateEnd;

    private String notifyUrl;


    /**
     * Get merchantNo
     * @return merchantNo
     **/
    
    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    /**
     * Get customerRequestNo
     * @return customerRequestNo
     **/
    
    public String getCustomerRequestNo() {
        return customerRequestNo;
    }

    public void setCustomerRequestNo(String customerRequestNo) {
        this.customerRequestNo = customerRequestNo;
    }

    /**
     * Get parentMerchantNo
     * @return parentMerchantNo
     **/
    
    public String getParentMerchantNo() {
        return parentMerchantNo;
    }

    public void setParentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
    }

    /**
     * Get chargingDateStart
     * @return chargingDateStart
     **/
    
    public String getChargingDateStart() {
        return chargingDateStart;
    }

    public void setChargingDateStart(String chargingDateStart) {
        this.chargingDateStart = chargingDateStart;
    }

    /**
     * Get chargingDateEnd
     * @return chargingDateEnd
     **/
    
    public String getChargingDateEnd() {
        return chargingDateEnd;
    }

    public void setChargingDateEnd(String chargingDateEnd) {
        this.chargingDateEnd = chargingDateEnd;
    }

    /**
     * Get notifyUrl
     * @return notifyUrl
     **/
    
    public String getNotifyUrl() {
        return notifyUrl;
    }

    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    @Override
    public String getOperationId() {
        return "apply";
    }
}
