/*
 * 供应商付款系统
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.supplier_remit;

import com.yeepay.yop.sdk.exception.YopClientException;
import com.yeepay.yop.sdk.model.yos.YosDownloadInputStream;
import com.yeepay.yop.sdk.model.yos.YosDownloadResponse;
import com.yeepay.yop.sdk.service.supplier_remit.request.*;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import org.junit.Test;
import org.junit.Ignore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.io.IOException;
import org.apache.commons.io.IOUtils;
/**
 * API tests for SupplierRemitClient
 */
@Ignore
public class SupplierRemitClientTest {

    private static final Logger LOGGER = LoggerFactory.getLogger(SupplierRemitClientTest.class);

    // 该Client线程安全，请使用单例模式，多次请求共用
    private final SupplierRemitClient api = SupplierRemitClientBuilder.builder().build();


    /**
     * 付款对账文件获取接口
     *
     * 支持商户进行对账文件下载。 受理失败，返回响应错误码；受理成功，返回文件
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void billDownloadTest() throws YopClientException {
        BillDownloadRequest request = new BillDownloadRequest();
        request.setRemitDate("remitDate_example");
        YosDownloadResponse response = api.billDownload(request);
        // 及时关闭文件流，避免连接泄漏
        YosDownloadInputStream result = null;
        try {
            result = response.getResult();
            saveFile(result);
        } catch (IOException e) {
            LOGGER.error("error when download, ex:", e);
        }  finally {
            if (null != result) {
                try {
                    result.close();
                } catch (IOException e) {
                    LOGGER.error("error when close YosDownloadInputStream, ex:", e);
                }
            }
        }
        // TODO: test validations
    }


    private void saveFile(YosDownloadInputStream in) throws IOException {
        //todo save
        LOGGER.debug(IOUtils.toString(in, "UTF-8"));
    }
}
