/*
 * 大禹
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.p2f.request;

import com.yeepay.yop.sdk.YopConstants;
import com.yeepay.yop.sdk.http.Headers;
import com.yeepay.yop.sdk.http.HttpMethodName;
import com.yeepay.yop.sdk.http.YopContentType;
import com.yeepay.yop.sdk.internal.DefaultRequest;
import com.yeepay.yop.sdk.internal.Request;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;
import com.yeepay.yop.sdk.protocol.marshaller.PrimitiveMarshallerUtils;
import java.util.Map;
import java.util.UUID;
import java.util.Iterator;
import org.apache.commons.lang3.BooleanUtils;


public class CompanyFinanceAccountRequestMarshaller implements RequestMarshaller<CompanyFinanceAccountRequest> {
    private final String serviceName = "P2f";

    private final String resourcePath = "/rest/v1.0/p2f/company-finance/account";

    private final String contentType = "application/x-www-form-urlencoded";

    private final HttpMethodName httpMethodName = HttpMethodName.POST;


    @Override
    public Request<CompanyFinanceAccountRequest> marshall(CompanyFinanceAccountRequest request) {
        Request<CompanyFinanceAccountRequest> internalRequest = new DefaultRequest<CompanyFinanceAccountRequest>(request, serviceName);
        internalRequest.setResourcePath(resourcePath);
        internalRequest.setHttpMethod(httpMethodName);
        if (!internalRequest.getHeaders().containsKey(Headers.YOP_REQUEST_ID)) {
            String requestId = UUID.randomUUID().toString();
            internalRequest.addHeader(Headers.YOP_REQUEST_ID, requestId);
        }
        Map<String, String> customerHeaders = request.getHeaders();
        if (customerHeaders != null) {
            for (String key : customerHeaders.keySet()) {
                internalRequest.addHeader(key, customerHeaders.get(key));
            }
        }
        if (request.getCompName() != null) {
            internalRequest.addParameter("compName", PrimitiveMarshallerUtils.marshalling(request.getCompName(), "String"));
        }
        if (request.getCompNo() != null) {
            internalRequest.addParameter("compNo", PrimitiveMarshallerUtils.marshalling(request.getCompNo(), "String"));
        }
        if (request.getCustomerCertExpiry() != null) {
            internalRequest.addParameter("customerCertExpiry", PrimitiveMarshallerUtils.marshalling(request.getCustomerCertExpiry(), "String"));
        }
        if (request.getRegSerialNoExpired() != null) {
            internalRequest.addParameter("regSerialNoExpired", PrimitiveMarshallerUtils.marshalling(request.getRegSerialNoExpired(), "String"));
        }
        if (request.getCompTelephone() != null) {
            internalRequest.addParameter("compTelephone", PrimitiveMarshallerUtils.marshalling(request.getCompTelephone(), "String"));
        }
        if (request.getOrgSMSMobile() != null) {
            internalRequest.addParameter("orgSMSMobile", PrimitiveMarshallerUtils.marshalling(request.getOrgSMSMobile(), "String"));
        }
        if (request.getUniteCreditCode() != null) {
            internalRequest.addParameter("uniteCreditCode", PrimitiveMarshallerUtils.marshalling(request.getUniteCreditCode(), "String"));
        }
        if (request.getCompEmail() != null) {
            internalRequest.addParameter("compEmail", PrimitiveMarshallerUtils.marshalling(request.getCompEmail(), "String"));
        }
        if (request.getCompAddr() != null) {
            internalRequest.addParameter("compAddr", PrimitiveMarshallerUtils.marshalling(request.getCompAddr(), "String"));
        }
        if (request.getZipCode() != null) {
            internalRequest.addParameter("zipCode", PrimitiveMarshallerUtils.marshalling(request.getZipCode(), "String"));
        }
        if (request.getBizScope() != null) {
            internalRequest.addParameter("bizScope", PrimitiveMarshallerUtils.marshalling(request.getBizScope(), "String"));
        }
        if (request.getLegalName() != null) {
            internalRequest.addParameter("legalName", PrimitiveMarshallerUtils.marshalling(request.getLegalName(), "String"));
        }
        if (request.getLegalIdNo() != null) {
            internalRequest.addParameter("legalIdNo", PrimitiveMarshallerUtils.marshalling(request.getLegalIdNo(), "String"));
        }
        if (request.getLegalStartDate() != null) {
            internalRequest.addParameter("legalStartDate", PrimitiveMarshallerUtils.marshalling(request.getLegalStartDate(), "String"));
        }
        if (request.getLegalExpiredDate() != null) {
            internalRequest.addParameter("legalExpiredDate", PrimitiveMarshallerUtils.marshalling(request.getLegalExpiredDate(), "String"));
        }
        if (request.getLegalMobile() != null) {
            internalRequest.addParameter("legalMobile", PrimitiveMarshallerUtils.marshalling(request.getLegalMobile(), "String"));
        }
        if (request.getBankCode() != null) {
            internalRequest.addParameter("bankCode", PrimitiveMarshallerUtils.marshalling(request.getBankCode(), "String"));
        }
        if (request.getBankName() != null) {
            internalRequest.addParameter("bankName", PrimitiveMarshallerUtils.marshalling(request.getBankName(), "String"));
        }
        if (request.getBankCardNo() != null) {
            internalRequest.addParameter("bankCardNo", PrimitiveMarshallerUtils.marshalling(request.getBankCardNo(), "String"));
        }
        if (request.getBindType() != null) {
            internalRequest.addParameter("bindType", PrimitiveMarshallerUtils.marshalling(request.getBindType(), "String"));
        }
        if (request.getBindAcctBranch() != null) {
            internalRequest.addParameter("bindAcctBranch", PrimitiveMarshallerUtils.marshalling(request.getBindAcctBranch(), "String"));
        }
        if (request.getThreeInOneFlag() != null) {
            internalRequest.addParameter("threeInOneFlag", PrimitiveMarshallerUtils.marshalling(request.getThreeInOneFlag(), "String"));
        }
        if (request.getUniteCreditCodePath() != null) {
            internalRequest.addParameter("uniteCreditCodePath", PrimitiveMarshallerUtils.marshalling(request.getUniteCreditCodePath(), "String"));
        }
        if (request.getFrontPhotoPath() != null) {
            internalRequest.addParameter("frontPhotoPath", PrimitiveMarshallerUtils.marshalling(request.getFrontPhotoPath(), "String"));
        }
        if (request.getBackPhotoPath() != null) {
            internalRequest.addParameter("backPhotoPath", PrimitiveMarshallerUtils.marshalling(request.getBackPhotoPath(), "String"));
        }
        if (request.getOpenAcctPermitCodePath() != null) {
            internalRequest.addParameter("openAcctPermitCodePath", PrimitiveMarshallerUtils.marshalling(request.getOpenAcctPermitCodePath(), "String"));
        }
        if (request.getChannelCode() != null) {
            internalRequest.addParameter("channelCode", PrimitiveMarshallerUtils.marshalling(request.getChannelCode(), "String"));
        }
        if (request.getRequestNo() != null) {
            internalRequest.addParameter("requestNo", PrimitiveMarshallerUtils.marshalling(request.getRequestNo(), "String"));
        }
        if (request.getMerchantNo() != null) {
            internalRequest.addParameter("merchantNo", PrimitiveMarshallerUtils.marshalling(request.getMerchantNo(), "String"));
        }
        internalRequest.setContentType(YopContentType.FORM_URL_ENCODE);
        internalRequest.addHeader(Headers.CONTENT_TYPE, internalRequest.getContentType().getValue());
        return internalRequest;
    }


    private static class CacheInstanceHolder {
        public static CompanyFinanceAccountRequestMarshaller INSTANCE = new CompanyFinanceAccountRequestMarshaller();

        private CacheInstanceHolder() {
        }
    }

    public static CompanyFinanceAccountRequestMarshaller getInstance() {
        return CacheInstanceHolder.INSTANCE;
    }
}
