/*
 * 聚合支付
 * <p>提供聚合支付相关服务（支付下单、公众号配置等功能</p>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.aggpay.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.yeepay.yop.sdk.service.aggpay.model.WechatConfigAddAppIdConfigDetailResult;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * 方法签名第0个参数，请自行修改arg0等参数的名字
 */
public class WechatConfigAddWechatConfigRequestDTOParam implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   *
   */
  @JsonProperty("appKey")
  private String appKey = null;

  /**
   *
   */
  @JsonProperty("parentMerchantNo")
  private String parentMerchantNo = null;

  /**
   *
   */
  @JsonProperty("merchantNo")
  private String merchantNo = null;

  /**
   *
   */
  @JsonProperty("tradeAuthDirList")
  private List<String> tradeAuthDirList = null;

  /**
   *
   */
  @JsonProperty("appIdList")
  private List<WechatConfigAddAppIdConfigDetailResult> appIdList = null;

  public WechatConfigAddWechatConfigRequestDTOParam appKey(String appKey) {
    this.appKey = appKey;
    return this;
  }

   /**
   * Get appKey
   * @return appKey
  **/

  public String getAppKey() {
    return appKey;
  }

  public void setAppKey(String appKey) {
    this.appKey = appKey;
  }

  public WechatConfigAddWechatConfigRequestDTOParam parentMerchantNo(String parentMerchantNo) {
    this.parentMerchantNo = parentMerchantNo;
    return this;
  }

   /**
   * Get parentMerchantNo
   * @return parentMerchantNo
  **/

  public String getParentMerchantNo() {
    return parentMerchantNo;
  }

  public void setParentMerchantNo(String parentMerchantNo) {
    this.parentMerchantNo = parentMerchantNo;
  }

  public WechatConfigAddWechatConfigRequestDTOParam merchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
    return this;
  }

   /**
   * Get merchantNo
   * @return merchantNo
  **/

  public String getMerchantNo() {
    return merchantNo;
  }

  public void setMerchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
  }

  public WechatConfigAddWechatConfigRequestDTOParam tradeAuthDirList(List<String> tradeAuthDirList) {
    this.tradeAuthDirList = tradeAuthDirList;
    return this;
  }

  public WechatConfigAddWechatConfigRequestDTOParam addTradeAuthDirListItem(String tradeAuthDirListItem) {
    if (this.tradeAuthDirList == null) {
      this.tradeAuthDirList = new ArrayList<>();
    }
    this.tradeAuthDirList.add(tradeAuthDirListItem);
    return this;
  }

   /**
   * Get tradeAuthDirList
   * @return tradeAuthDirList
  **/

  public List<String> getTradeAuthDirList() {
    return tradeAuthDirList;
  }

  public void setTradeAuthDirList(List<String> tradeAuthDirList) {
    this.tradeAuthDirList = tradeAuthDirList;
  }

  public WechatConfigAddWechatConfigRequestDTOParam appIdList(List<WechatConfigAddAppIdConfigDetailResult> appIdList) {
    this.appIdList = appIdList;
    return this;
  }

  public WechatConfigAddWechatConfigRequestDTOParam addAppIdListItem(WechatConfigAddAppIdConfigDetailResult appIdListItem) {
    if (this.appIdList == null) {
      this.appIdList = new ArrayList<>();
    }
    this.appIdList.add(appIdListItem);
    return this;
  }

   /**
   * Get appIdList
   * @return appIdList
  **/

  public List<WechatConfigAddAppIdConfigDetailResult> getAppIdList() {
    return appIdList;
  }

  public void setAppIdList(List<WechatConfigAddAppIdConfigDetailResult> appIdList) {
    this.appIdList = appIdList;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    WechatConfigAddWechatConfigRequestDTOParam wechatConfigAddWechatConfigRequestDTOParam = (WechatConfigAddWechatConfigRequestDTOParam) o;
    return ObjectUtils.equals(this.appKey, wechatConfigAddWechatConfigRequestDTOParam.appKey) &&
    ObjectUtils.equals(this.parentMerchantNo, wechatConfigAddWechatConfigRequestDTOParam.parentMerchantNo) &&
    ObjectUtils.equals(this.merchantNo, wechatConfigAddWechatConfigRequestDTOParam.merchantNo) &&
    ObjectUtils.equals(this.tradeAuthDirList, wechatConfigAddWechatConfigRequestDTOParam.tradeAuthDirList) &&
    ObjectUtils.equals(this.appIdList, wechatConfigAddWechatConfigRequestDTOParam.appIdList);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(appKey, parentMerchantNo, merchantNo, tradeAuthDirList, appIdList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WechatConfigAddWechatConfigRequestDTOParam {\n");

    sb.append("    appKey: ").append(toIndentedString(appKey)).append("\n");
    sb.append("    parentMerchantNo: ").append(toIndentedString(parentMerchantNo)).append("\n");
    sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
    sb.append("    tradeAuthDirList: ").append(toIndentedString(tradeAuthDirList)).append("\n");
    sb.append("    appIdList: ").append(toIndentedString(appIdList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

