/*
 * 聚合支付
 * <p>提供聚合支付相关服务（支付下单、公众号配置等功能</p>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.aggpay.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.yeepay.yop.sdk.service.aggpay.model.WechatConfigQueryAppIdConfigDetailResult;
import com.yeepay.yop.sdk.service.aggpay.model.WechatConfigQueryTradeAuthDirDTOResult;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * WechatConfigQueryConfigMerchantDTOResult
 */
public class WechatConfigQueryConfigMerchantDTOResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 报备商户号
   */
  @JsonProperty("reportMerchantNo")
  private String reportMerchantNo = null;

  /**
   * 支付授权目录列表
   */
  @JsonProperty("tradeAuthDirList")
  private List<WechatConfigQueryTradeAuthDirDTOResult> tradeAuthDirList = null;

  /**
   * 支付appId配置列表
   */
  @JsonProperty("appIdList")
  private List<WechatConfigQueryAppIdConfigDetailResult> appIdList = null;

  public WechatConfigQueryConfigMerchantDTOResult reportMerchantNo(String reportMerchantNo) {
    this.reportMerchantNo = reportMerchantNo;
    return this;
  }

   /**
   * 报备商户号
   * @return reportMerchantNo
  **/

  public String getReportMerchantNo() {
    return reportMerchantNo;
  }

  public void setReportMerchantNo(String reportMerchantNo) {
    this.reportMerchantNo = reportMerchantNo;
  }

  public WechatConfigQueryConfigMerchantDTOResult tradeAuthDirList(List<WechatConfigQueryTradeAuthDirDTOResult> tradeAuthDirList) {
    this.tradeAuthDirList = tradeAuthDirList;
    return this;
  }

  public WechatConfigQueryConfigMerchantDTOResult addTradeAuthDirListItem(WechatConfigQueryTradeAuthDirDTOResult tradeAuthDirListItem) {
    if (this.tradeAuthDirList == null) {
      this.tradeAuthDirList = new ArrayList<>();
    }
    this.tradeAuthDirList.add(tradeAuthDirListItem);
    return this;
  }

   /**
   * 支付授权目录列表
   * @return tradeAuthDirList
  **/

  public List<WechatConfigQueryTradeAuthDirDTOResult> getTradeAuthDirList() {
    return tradeAuthDirList;
  }

  public void setTradeAuthDirList(List<WechatConfigQueryTradeAuthDirDTOResult> tradeAuthDirList) {
    this.tradeAuthDirList = tradeAuthDirList;
  }

  public WechatConfigQueryConfigMerchantDTOResult appIdList(List<WechatConfigQueryAppIdConfigDetailResult> appIdList) {
    this.appIdList = appIdList;
    return this;
  }

  public WechatConfigQueryConfigMerchantDTOResult addAppIdListItem(WechatConfigQueryAppIdConfigDetailResult appIdListItem) {
    if (this.appIdList == null) {
      this.appIdList = new ArrayList<>();
    }
    this.appIdList.add(appIdListItem);
    return this;
  }

   /**
   * 支付appId配置列表
   * @return appIdList
  **/

  public List<WechatConfigQueryAppIdConfigDetailResult> getAppIdList() {
    return appIdList;
  }

  public void setAppIdList(List<WechatConfigQueryAppIdConfigDetailResult> appIdList) {
    this.appIdList = appIdList;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    WechatConfigQueryConfigMerchantDTOResult wechatConfigQueryConfigMerchantDTOResult = (WechatConfigQueryConfigMerchantDTOResult) o;
    return ObjectUtils.equals(this.reportMerchantNo, wechatConfigQueryConfigMerchantDTOResult.reportMerchantNo) &&
    ObjectUtils.equals(this.tradeAuthDirList, wechatConfigQueryConfigMerchantDTOResult.tradeAuthDirList) &&
    ObjectUtils.equals(this.appIdList, wechatConfigQueryConfigMerchantDTOResult.appIdList);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(reportMerchantNo, tradeAuthDirList, appIdList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WechatConfigQueryConfigMerchantDTOResult {\n");

    sb.append("    reportMerchantNo: ").append(toIndentedString(reportMerchantNo)).append("\n");
    sb.append("    tradeAuthDirList: ").append(toIndentedString(tradeAuthDirList)).append("\n");
    sb.append("    appIdList: ").append(toIndentedString(appIdList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

