/*
 * 发票服务
 * <p>基于中台商户实际开票场景，提供给商户维护开票规则、票面信息，查询票面信息，申请开具手续费发票，查询开票记录，查询实收手续费金额的服务</p>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.invoice.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * InfoQueryQueryInvoiceInfoYOPResponseDtoResult
 */
public class InfoQueryQueryInvoiceInfoYOPResponseDtoResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 返回码
   */
  @JsonProperty("code")
  private String code = null;

  /**
   * 返回信息
   */
  @JsonProperty("message")
  private String message = null;

  /**
   * 商编
   */
  @JsonProperty("merchantNo")
  private String merchantNo = null;

  /**
   * 开票方式
   */
  @JsonProperty("mode")
  private String mode = null;

  /**
   * 发票类型
   */
  @JsonProperty("invoiceType")
  private String invoiceType = null;

  /**
   * 发票形式
   */
  @JsonProperty("invoiceForm")
  private String invoiceForm = null;

  /**
   * 联系人
   */
  @JsonProperty("linkman")
  private String linkman = null;

  /**
   * 联系人电话
   */
  @JsonProperty("linkmanPhone")
  private String linkmanPhone = null;

  /**
   * 发票邮寄地址
   */
  @JsonProperty("postalAddress")
  private String postalAddress = null;

  /**
   * 邮编
   */
  @JsonProperty("postalCode")
  private String postalCode = null;

  /**
   * 发票抬头
   */
  @JsonProperty("invoiceName")
  private String invoiceName = null;

  /**
   * 纳税人标识
   */
  @JsonProperty("taxpayerId")
  private String taxpayerId = null;

  /**
   * 开票联系电话
   */
  @JsonProperty("invoicePhone")
  private String invoicePhone = null;

  /**
   * 开票地址
   */
  @JsonProperty("invoiceAddress")
  private String invoiceAddress = null;

  /**
   * 开户银行名称
   */
  @JsonProperty("bankName")
  private String bankName = null;

  /**
   * 账号信息
   */
  @JsonProperty("accountNo")
  private String accountNo = null;

  /**
   * 邮箱
   */
  @JsonProperty("email")
  private String email = null;

  /**
   * 是否需要发票
   */
  @JsonProperty("needInvoice")
  private String needInvoice = null;

  /**
   * 创建时间
   */
  @JsonProperty("createTime")
  private String createTime = null;

  /**
   * 更新时间
   */
  @JsonProperty("lastModifyTime")
  private String lastModifyTime = null;

  /**
   * 备注
   */
  @JsonProperty("remark")
  private String remark = null;

  /**
   * 规格型号
   */
  @JsonProperty("standardType")
  private String standardType = null;

  /**
   * 单位
   */
  @JsonProperty("unit")
  private String unit = null;

  /**
   * 数量
   */
  @JsonProperty("quantity")
  private Integer quantity = null;

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult code(String code) {
    this.code = code;
    return this;
  }

   /**
   * 返回码
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * 返回信息
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult merchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
    return this;
  }

   /**
   * 商编
   * @return merchantNo
  **/

  public String getMerchantNo() {
    return merchantNo;
  }

  public void setMerchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult mode(String mode) {
    this.mode = mode;
    return this;
  }

   /**
   * 开票方式
   * @return mode
  **/

  public String getMode() {
    return mode;
  }

  public void setMode(String mode) {
    this.mode = mode;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult invoiceType(String invoiceType) {
    this.invoiceType = invoiceType;
    return this;
  }

   /**
   * 发票类型
   * @return invoiceType
  **/

  public String getInvoiceType() {
    return invoiceType;
  }

  public void setInvoiceType(String invoiceType) {
    this.invoiceType = invoiceType;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult invoiceForm(String invoiceForm) {
    this.invoiceForm = invoiceForm;
    return this;
  }

   /**
   * 发票形式
   * @return invoiceForm
  **/

  public String getInvoiceForm() {
    return invoiceForm;
  }

  public void setInvoiceForm(String invoiceForm) {
    this.invoiceForm = invoiceForm;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult linkman(String linkman) {
    this.linkman = linkman;
    return this;
  }

   /**
   * 联系人
   * @return linkman
  **/

  public String getLinkman() {
    return linkman;
  }

  public void setLinkman(String linkman) {
    this.linkman = linkman;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult linkmanPhone(String linkmanPhone) {
    this.linkmanPhone = linkmanPhone;
    return this;
  }

   /**
   * 联系人电话
   * @return linkmanPhone
  **/

  public String getLinkmanPhone() {
    return linkmanPhone;
  }

  public void setLinkmanPhone(String linkmanPhone) {
    this.linkmanPhone = linkmanPhone;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult postalAddress(String postalAddress) {
    this.postalAddress = postalAddress;
    return this;
  }

   /**
   * 发票邮寄地址
   * @return postalAddress
  **/

  public String getPostalAddress() {
    return postalAddress;
  }

  public void setPostalAddress(String postalAddress) {
    this.postalAddress = postalAddress;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * 邮编
   * @return postalCode
  **/

  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult invoiceName(String invoiceName) {
    this.invoiceName = invoiceName;
    return this;
  }

   /**
   * 发票抬头
   * @return invoiceName
  **/

  public String getInvoiceName() {
    return invoiceName;
  }

  public void setInvoiceName(String invoiceName) {
    this.invoiceName = invoiceName;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult taxpayerId(String taxpayerId) {
    this.taxpayerId = taxpayerId;
    return this;
  }

   /**
   * 纳税人标识
   * @return taxpayerId
  **/

  public String getTaxpayerId() {
    return taxpayerId;
  }

  public void setTaxpayerId(String taxpayerId) {
    this.taxpayerId = taxpayerId;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult invoicePhone(String invoicePhone) {
    this.invoicePhone = invoicePhone;
    return this;
  }

   /**
   * 开票联系电话
   * @return invoicePhone
  **/

  public String getInvoicePhone() {
    return invoicePhone;
  }

  public void setInvoicePhone(String invoicePhone) {
    this.invoicePhone = invoicePhone;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult invoiceAddress(String invoiceAddress) {
    this.invoiceAddress = invoiceAddress;
    return this;
  }

   /**
   * 开票地址
   * @return invoiceAddress
  **/

  public String getInvoiceAddress() {
    return invoiceAddress;
  }

  public void setInvoiceAddress(String invoiceAddress) {
    this.invoiceAddress = invoiceAddress;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * 开户银行名称
   * @return bankName
  **/

  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult accountNo(String accountNo) {
    this.accountNo = accountNo;
    return this;
  }

   /**
   * 账号信息
   * @return accountNo
  **/

  public String getAccountNo() {
    return accountNo;
  }

  public void setAccountNo(String accountNo) {
    this.accountNo = accountNo;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult email(String email) {
    this.email = email;
    return this;
  }

   /**
   * 邮箱
   * @return email
  **/

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult needInvoice(String needInvoice) {
    this.needInvoice = needInvoice;
    return this;
  }

   /**
   * 是否需要发票
   * @return needInvoice
  **/

  public String getNeedInvoice() {
    return needInvoice;
  }

  public void setNeedInvoice(String needInvoice) {
    this.needInvoice = needInvoice;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult createTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * 创建时间
   * @return createTime
  **/

  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult lastModifyTime(String lastModifyTime) {
    this.lastModifyTime = lastModifyTime;
    return this;
  }

   /**
   * 更新时间
   * @return lastModifyTime
  **/

  public String getLastModifyTime() {
    return lastModifyTime;
  }

  public void setLastModifyTime(String lastModifyTime) {
    this.lastModifyTime = lastModifyTime;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult remark(String remark) {
    this.remark = remark;
    return this;
  }

   /**
   * 备注
   * @return remark
  **/

  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult standardType(String standardType) {
    this.standardType = standardType;
    return this;
  }

   /**
   * 规格型号
   * @return standardType
  **/

  public String getStandardType() {
    return standardType;
  }

  public void setStandardType(String standardType) {
    this.standardType = standardType;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult unit(String unit) {
    this.unit = unit;
    return this;
  }

   /**
   * 单位
   * @return unit
  **/

  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  public InfoQueryQueryInvoiceInfoYOPResponseDtoResult quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * 数量
   * @return quantity
  **/

  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    InfoQueryQueryInvoiceInfoYOPResponseDtoResult infoQueryQueryInvoiceInfoYOPResponseDtoResult = (InfoQueryQueryInvoiceInfoYOPResponseDtoResult) o;
    return ObjectUtils.equals(this.code, infoQueryQueryInvoiceInfoYOPResponseDtoResult.code) &&
    ObjectUtils.equals(this.message, infoQueryQueryInvoiceInfoYOPResponseDtoResult.message) &&
    ObjectUtils.equals(this.merchantNo, infoQueryQueryInvoiceInfoYOPResponseDtoResult.merchantNo) &&
    ObjectUtils.equals(this.mode, infoQueryQueryInvoiceInfoYOPResponseDtoResult.mode) &&
    ObjectUtils.equals(this.invoiceType, infoQueryQueryInvoiceInfoYOPResponseDtoResult.invoiceType) &&
    ObjectUtils.equals(this.invoiceForm, infoQueryQueryInvoiceInfoYOPResponseDtoResult.invoiceForm) &&
    ObjectUtils.equals(this.linkman, infoQueryQueryInvoiceInfoYOPResponseDtoResult.linkman) &&
    ObjectUtils.equals(this.linkmanPhone, infoQueryQueryInvoiceInfoYOPResponseDtoResult.linkmanPhone) &&
    ObjectUtils.equals(this.postalAddress, infoQueryQueryInvoiceInfoYOPResponseDtoResult.postalAddress) &&
    ObjectUtils.equals(this.postalCode, infoQueryQueryInvoiceInfoYOPResponseDtoResult.postalCode) &&
    ObjectUtils.equals(this.invoiceName, infoQueryQueryInvoiceInfoYOPResponseDtoResult.invoiceName) &&
    ObjectUtils.equals(this.taxpayerId, infoQueryQueryInvoiceInfoYOPResponseDtoResult.taxpayerId) &&
    ObjectUtils.equals(this.invoicePhone, infoQueryQueryInvoiceInfoYOPResponseDtoResult.invoicePhone) &&
    ObjectUtils.equals(this.invoiceAddress, infoQueryQueryInvoiceInfoYOPResponseDtoResult.invoiceAddress) &&
    ObjectUtils.equals(this.bankName, infoQueryQueryInvoiceInfoYOPResponseDtoResult.bankName) &&
    ObjectUtils.equals(this.accountNo, infoQueryQueryInvoiceInfoYOPResponseDtoResult.accountNo) &&
    ObjectUtils.equals(this.email, infoQueryQueryInvoiceInfoYOPResponseDtoResult.email) &&
    ObjectUtils.equals(this.needInvoice, infoQueryQueryInvoiceInfoYOPResponseDtoResult.needInvoice) &&
    ObjectUtils.equals(this.createTime, infoQueryQueryInvoiceInfoYOPResponseDtoResult.createTime) &&
    ObjectUtils.equals(this.lastModifyTime, infoQueryQueryInvoiceInfoYOPResponseDtoResult.lastModifyTime) &&
    ObjectUtils.equals(this.remark, infoQueryQueryInvoiceInfoYOPResponseDtoResult.remark) &&
    ObjectUtils.equals(this.standardType, infoQueryQueryInvoiceInfoYOPResponseDtoResult.standardType) &&
    ObjectUtils.equals(this.unit, infoQueryQueryInvoiceInfoYOPResponseDtoResult.unit) &&
    ObjectUtils.equals(this.quantity, infoQueryQueryInvoiceInfoYOPResponseDtoResult.quantity);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, merchantNo, mode, invoiceType, invoiceForm, linkman, linkmanPhone, postalAddress, postalCode, invoiceName, taxpayerId, invoicePhone, invoiceAddress, bankName, accountNo, email, needInvoice, createTime, lastModifyTime, remark, standardType, unit, quantity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfoQueryQueryInvoiceInfoYOPResponseDtoResult {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    invoiceType: ").append(toIndentedString(invoiceType)).append("\n");
    sb.append("    invoiceForm: ").append(toIndentedString(invoiceForm)).append("\n");
    sb.append("    linkman: ").append(toIndentedString(linkman)).append("\n");
    sb.append("    linkmanPhone: ").append(toIndentedString(linkmanPhone)).append("\n");
    sb.append("    postalAddress: ").append(toIndentedString(postalAddress)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    invoiceName: ").append(toIndentedString(invoiceName)).append("\n");
    sb.append("    taxpayerId: ").append(toIndentedString(taxpayerId)).append("\n");
    sb.append("    invoicePhone: ").append(toIndentedString(invoicePhone)).append("\n");
    sb.append("    invoiceAddress: ").append(toIndentedString(invoiceAddress)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    accountNo: ").append(toIndentedString(accountNo)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    needInvoice: ").append(toIndentedString(needInvoice)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    lastModifyTime: ").append(toIndentedString(lastModifyTime)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    standardType: ").append(toIndentedString(standardType)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

