/*
 * 分账
 * <p>名称（中文）：分账<br />名称（英文，xx.war）：opr-hessian.war<br />简介：中台收款交易支持分账<br />wiki文档地址：http://wiki.yeepay.com/pages/viewpage.action?pageId=108380664<br />预计项目上线时间：2020年6月9日<br />归属/拟申请的sp编码（可选）：opr<br />期望api分组编码、名称（可选）：divide（分账）<br />涉及的接口：申请分账、分账查询、分账资金归还/分账退回、分账退回查询</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.divide.request;

import com.yeepay.yop.sdk.model.BaseRequest;
public class QueryRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String parentMerchantNo;

    private String merchantNo;

    private String divideRequestId;

    private String orderId;

    private String uniqueOrderNo;


    /**
     * 
     * @return parentMerchantNo
     **/
    
    public String getParentMerchantNo() {
        return parentMerchantNo;
    }

    public void setParentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
    }

    /**
     * 收款商户编号
     * @return merchantNo
     **/
    
    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    /**
     * 
     * @return divideRequestId
     **/
    
    public String getDivideRequestId() {
        return divideRequestId;
    }

    public void setDivideRequestId(String divideRequestId) {
        this.divideRequestId = divideRequestId;
    }

    /**
     * 原支付订单的商户订单号
     * @return orderId
     **/
    
    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * 收款交易对应在易宝的单号
     * @return uniqueOrderNo
     **/
    
    public String getUniqueOrderNo() {
        return uniqueOrderNo;
    }

    public void setUniqueOrderNo(String uniqueOrderNo) {
        this.uniqueOrderNo = uniqueOrderNo;
    }

    @Override
    public String getOperationId() {
        return "query";
    }
}
