/*
 * 子商户管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.mer.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult
 */
public class MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 响应编码
   */
  @JsonProperty("returnCode")
  private String returnCode = null;

  /**
   * 响应描述
   */
  @JsonProperty("returnMsg")
  private String returnMsg = null;

  /**
   * 申请单编号
   */
  @JsonProperty("applicationNo")
  private String applicationNo = null;

  /**
   * 请求号
   */
  @JsonProperty("requestNo")
  private String requestNo = null;

  /**
   * 申请单状态
   */
  @JsonProperty("bizStatus")
  private String bizStatus = null;

  /**
   * 解冻商编
   */
  @JsonProperty("merchantNo")
  private String merchantNo = null;

  /**
   * 失败原因
   */
  @JsonProperty("failReason")
  private String failReason = null;

  public MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult returnCode(String returnCode) {
    this.returnCode = returnCode;
    return this;
  }

   /**
   * 响应编码
   * @return returnCode
  **/

  public String getReturnCode() {
    return returnCode;
  }

  public void setReturnCode(String returnCode) {
    this.returnCode = returnCode;
  }

  public MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult returnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
    return this;
  }

   /**
   * 响应描述
   * @return returnMsg
  **/

  public String getReturnMsg() {
    return returnMsg;
  }

  public void setReturnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
  }

  public MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult applicationNo(String applicationNo) {
    this.applicationNo = applicationNo;
    return this;
  }

   /**
   * 申请单编号
   * @return applicationNo
  **/

  public String getApplicationNo() {
    return applicationNo;
  }

  public void setApplicationNo(String applicationNo) {
    this.applicationNo = applicationNo;
  }

  public MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult requestNo(String requestNo) {
    this.requestNo = requestNo;
    return this;
  }

   /**
   * 请求号
   * @return requestNo
  **/

  public String getRequestNo() {
    return requestNo;
  }

  public void setRequestNo(String requestNo) {
    this.requestNo = requestNo;
  }

  public MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult bizStatus(String bizStatus) {
    this.bizStatus = bizStatus;
    return this;
  }

   /**
   * 申请单状态
   * @return bizStatus
  **/

  public String getBizStatus() {
    return bizStatus;
  }

  public void setBizStatus(String bizStatus) {
    this.bizStatus = bizStatus;
  }

  public MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult merchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
    return this;
  }

   /**
   * 解冻商编
   * @return merchantNo
  **/

  public String getMerchantNo() {
    return merchantNo;
  }

  public void setMerchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
  }

  public MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult failReason(String failReason) {
    this.failReason = failReason;
    return this;
  }

   /**
   * 失败原因
   * @return failReason
  **/

  public String getFailReason() {
    return failReason;
  }

  public void setFailReason(String failReason) {
    this.failReason = failReason;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult merchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult = (MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult) o;
    return ObjectUtils.equals(this.returnCode, merchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult.returnCode) &&
    ObjectUtils.equals(this.returnMsg, merchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult.returnMsg) &&
    ObjectUtils.equals(this.applicationNo, merchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult.applicationNo) &&
    ObjectUtils.equals(this.requestNo, merchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult.requestNo) &&
    ObjectUtils.equals(this.bizStatus, merchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult.bizStatus) &&
    ObjectUtils.equals(this.merchantNo, merchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult.merchantNo) &&
    ObjectUtils.equals(this.failReason, merchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult.failReason);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(returnCode, returnMsg, applicationNo, requestNo, bizStatus, merchantNo, failReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantDisposeQueryMerchantQueryDisposeNotifyRespDtoResult {\n");

    sb.append("    returnCode: ").append(toIndentedString(returnCode)).append("\n");
    sb.append("    returnMsg: ").append(toIndentedString(returnMsg)).append("\n");
    sb.append("    applicationNo: ").append(toIndentedString(applicationNo)).append("\n");
    sb.append("    requestNo: ").append(toIndentedString(requestNo)).append("\n");
    sb.append("    bizStatus: ").append(toIndentedString(bizStatus)).append("\n");
    sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
    sb.append("    failReason: ").append(toIndentedString(failReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

