/*
 * 子商户管理
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.mer.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * RegisterSaasMicroV2ContributeMicroMerchantNetInRespDtoResult
 */
public class RegisterSaasMicroV2ContributeMicroMerchantNetInRespDtoResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 响应编码
   */
  @JsonProperty("returnCode")
  private String returnCode = null;

  /**
   * 响应描述
   */
  @JsonProperty("returnMsg")
  private String returnMsg = null;

  /**
   * 入网请求号
   */
  @JsonProperty("requestNo")
  private String requestNo = null;

  /**
   * 申请单编号
   */
  @JsonProperty("applicationNo")
  private String applicationNo = null;

  /**
   * 申请状态
   */
  @JsonProperty("applicationStatus")
  private String applicationStatus = null;

  /**
   * 商户编号
   */
  @JsonProperty("merchantNo")
  private String merchantNo = null;

  public RegisterSaasMicroV2ContributeMicroMerchantNetInRespDtoResult returnCode(String returnCode) {
    this.returnCode = returnCode;
    return this;
  }

   /**
   * 响应编码
   * @return returnCode
  **/

  public String getReturnCode() {
    return returnCode;
  }

  public void setReturnCode(String returnCode) {
    this.returnCode = returnCode;
  }

  public RegisterSaasMicroV2ContributeMicroMerchantNetInRespDtoResult returnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
    return this;
  }

   /**
   * 响应描述
   * @return returnMsg
  **/

  public String getReturnMsg() {
    return returnMsg;
  }

  public void setReturnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
  }

  public RegisterSaasMicroV2ContributeMicroMerchantNetInRespDtoResult requestNo(String requestNo) {
    this.requestNo = requestNo;
    return this;
  }

   /**
   * 入网请求号
   * @return requestNo
  **/

  public String getRequestNo() {
    return requestNo;
  }

  public void setRequestNo(String requestNo) {
    this.requestNo = requestNo;
  }

  public RegisterSaasMicroV2ContributeMicroMerchantNetInRespDtoResult applicationNo(String applicationNo) {
    this.applicationNo = applicationNo;
    return this;
  }

   /**
   * 申请单编号
   * @return applicationNo
  **/

  public String getApplicationNo() {
    return applicationNo;
  }

  public void setApplicationNo(String applicationNo) {
    this.applicationNo = applicationNo;
  }

  public RegisterSaasMicroV2ContributeMicroMerchantNetInRespDtoResult applicationStatus(String applicationStatus) {
    this.applicationStatus = applicationStatus;
    return this;
  }

   /**
   * 申请状态
   * @return applicationStatus
  **/

  public String getApplicationStatus() {
    return applicationStatus;
  }

  public void setApplicationStatus(String applicationStatus) {
    this.applicationStatus = applicationStatus;
  }

  public RegisterSaasMicroV2ContributeMicroMerchantNetInRespDtoResult merchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
    return this;
  }

   /**
   * 商户编号
   * @return merchantNo
  **/

  public String getMerchantNo() {
    return merchantNo;
  }

  public void setMerchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    RegisterSaasMicroV2ContributeMicroMerchantNetInRespDtoResult registerSaasMicroV2ContributeMicroMerchantNetInRespDtoResult = (RegisterSaasMicroV2ContributeMicroMerchantNetInRespDtoResult) o;
    return ObjectUtils.equals(this.returnCode, registerSaasMicroV2ContributeMicroMerchantNetInRespDtoResult.returnCode) &&
    ObjectUtils.equals(this.returnMsg, registerSaasMicroV2ContributeMicroMerchantNetInRespDtoResult.returnMsg) &&
    ObjectUtils.equals(this.requestNo, registerSaasMicroV2ContributeMicroMerchantNetInRespDtoResult.requestNo) &&
    ObjectUtils.equals(this.applicationNo, registerSaasMicroV2ContributeMicroMerchantNetInRespDtoResult.applicationNo) &&
    ObjectUtils.equals(this.applicationStatus, registerSaasMicroV2ContributeMicroMerchantNetInRespDtoResult.applicationStatus) &&
    ObjectUtils.equals(this.merchantNo, registerSaasMicroV2ContributeMicroMerchantNetInRespDtoResult.merchantNo);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(returnCode, returnMsg, requestNo, applicationNo, applicationStatus, merchantNo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegisterSaasMicroV2ContributeMicroMerchantNetInRespDtoResult {\n");

    sb.append("    returnCode: ").append(toIndentedString(returnCode)).append("\n");
    sb.append("    returnMsg: ").append(toIndentedString(returnMsg)).append("\n");
    sb.append("    requestNo: ").append(toIndentedString(requestNo)).append("\n");
    sb.append("    applicationNo: ").append(toIndentedString(applicationNo)).append("\n");
    sb.append("    applicationStatus: ").append(toIndentedString(applicationStatus)).append("\n");
    sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

