/*
 * 发票服务
 * <p>基于中台商户实际开票场景，提供给商户维护开票规则、票面信息，查询票面信息，申请开具手续费发票，查询开票记录，查询实收手续费金额的服务</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.invoice.response;





import com.yeepay.yop.sdk.model.BaseResponse;

import com.yeepay.yop.sdk.service.invoice.model.FeeQueryGetFeeResponseDtoResult;

public class FeeQueryResponse extends BaseResponse {
    private static final long serialVersionUID = 1L;

    private FeeQueryGetFeeResponseDtoResult result;

    public FeeQueryGetFeeResponseDtoResult getResult() {
        return result;
    }

    public void setResult(FeeQueryGetFeeResponseDtoResult result) {
        this.result = result;
    }

}
