/*
 * 聚合支付
 * <p>提供聚合支付相关服务（支付下单、公众号配置等功能</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.aggpay.request;

import com.yeepay.yop.sdk.YopConstants;
import com.yeepay.yop.sdk.http.Headers;
import com.yeepay.yop.sdk.http.HttpMethodName;
import com.yeepay.yop.sdk.http.YopContentType;
import com.yeepay.yop.sdk.internal.DefaultRequest;
import com.yeepay.yop.sdk.internal.Request;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;
import com.yeepay.yop.sdk.protocol.marshaller.PrimitiveMarshallerUtils;
import java.util.Map;
import java.util.UUID;
import java.util.Iterator;
import org.apache.commons.lang3.BooleanUtils;


public class ComplaintWechatListRequestMarshaller implements RequestMarshaller<ComplaintWechatListRequest> {
    private final String serviceName = "Aggpay";

    private final String resourcePath = "/rest/v1.0/aggpay/complaint/wechat/list";

    private final String contentType = "application/x-www-form-urlencoded";

    private final HttpMethodName httpMethodName = HttpMethodName.GET;


    @Override
    public Request<ComplaintWechatListRequest> marshall(ComplaintWechatListRequest request) {
        Request<ComplaintWechatListRequest> internalRequest = new DefaultRequest<ComplaintWechatListRequest>(request, serviceName);
        internalRequest.setResourcePath(resourcePath);
        internalRequest.setHttpMethod(httpMethodName);
        if (!internalRequest.getHeaders().containsKey(Headers.YOP_REQUEST_ID)) {
            String requestId = UUID.randomUUID().toString();
            internalRequest.addHeader(Headers.YOP_REQUEST_ID, requestId);
        }
        Map<String, String> customerHeaders = request.getHeaders();
        if (customerHeaders != null) {
            for (String key : customerHeaders.keySet()) {
                internalRequest.addHeader(key, customerHeaders.get(key));
            }
        }
        if (request.getStartTime() != null) {
            internalRequest.addParameter("startTime", PrimitiveMarshallerUtils.marshalling(request.getStartTime(), "String"));
        }
        if (request.getEndTime() != null) {
            internalRequest.addParameter("endTime", PrimitiveMarshallerUtils.marshalling(request.getEndTime(), "String"));
        }
        if (request.getMerchantOrderNo() != null) {
            internalRequest.addParameter("merchantOrderNo", PrimitiveMarshallerUtils.marshalling(request.getMerchantOrderNo(), "String"));
        }
        if (request.getWechatOrderNo() != null) {
            internalRequest.addParameter("wechatOrderNo", PrimitiveMarshallerUtils.marshalling(request.getWechatOrderNo(), "String"));
        }
        if (request.getMerchantNo() != null) {
            internalRequest.addParameter("merchantNo", PrimitiveMarshallerUtils.marshalling(request.getMerchantNo(), "String"));
        }
        if (request.getPage() != null) {
            internalRequest.addParameter("page", PrimitiveMarshallerUtils.marshalling(request.getPage(), "Integer"));
        }
        if (request.getLimit() != null) {
            internalRequest.addParameter("limit", PrimitiveMarshallerUtils.marshalling(request.getLimit(), "Integer"));
        }
        internalRequest.setContentType(YopContentType.FORM_URL_ENCODE);
        internalRequest.addHeader(Headers.CONTENT_TYPE, internalRequest.getContentType().getValue());
        return internalRequest;
    }


    private static class CacheInstanceHolder {
        public static ComplaintWechatListRequestMarshaller INSTANCE = new ComplaintWechatListRequestMarshaller();

        private CacheInstanceHolder() {
        }
    }

    public static ComplaintWechatListRequestMarshaller getInstance() {
        return CacheInstanceHolder.INSTANCE;
    }
}
