/*
 * 聚合支付
 * <p>提供聚合支付相关服务（支付下单、公众号配置等功能</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.aggpay.request;

import com.yeepay.yop.sdk.model.BaseRequest;
import java.math.BigDecimal;
public class PayLinkRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String parentMerchantNo;

    private String merchantNo;

    private String orderId;

    private BigDecimal orderAmount;

    private String expiredTime;

    private String notifyUrl;

    private String memo;

    private String goodsName;

    private String fundProcessType;

    private String scene;

    private String appId;

    private String channelSpecifiedInfo;

    private String channelPromotionInfo;

    private String identityInfo;

    private String limitCredit;

    private String csUrl;

    private String ypPromotionInfo;

    private String businessInfo;

    private String token;


    /**
     * Get parentMerchantNo
     * @return parentMerchantNo
     **/
    
    public String getParentMerchantNo() {
        return parentMerchantNo;
    }

    public void setParentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
    }

    /**
     * Get merchantNo
     * @return merchantNo
     **/
    
    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    /**
     * Get orderId
     * @return orderId
     **/
    
    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * Get orderAmount
     * @return orderAmount
     **/
    
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * Get expiredTime
     * @return expiredTime
     **/
    
    public String getExpiredTime() {
        return expiredTime;
    }

    public void setExpiredTime(String expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * Get notifyUrl
     * @return notifyUrl
     **/
    
    public String getNotifyUrl() {
        return notifyUrl;
    }

    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * Get memo
     * @return memo
     **/
    
    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * Get goodsName
     * @return goodsName
     **/
    
    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * Get fundProcessType
     * @return fundProcessType
     **/
    
    public String getFundProcessType() {
        return fundProcessType;
    }

    public void setFundProcessType(String fundProcessType) {
        this.fundProcessType = fundProcessType;
    }

    /**
     * Get scene
     * @return scene
     **/
    
    public String getScene() {
        return scene;
    }

    public void setScene(String scene) {
        this.scene = scene;
    }

    /**
     * Get appId
     * @return appId
     **/
    
    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * Get channelSpecifiedInfo
     * @return channelSpecifiedInfo
     **/
    
    public String getChannelSpecifiedInfo() {
        return channelSpecifiedInfo;
    }

    public void setChannelSpecifiedInfo(String channelSpecifiedInfo) {
        this.channelSpecifiedInfo = channelSpecifiedInfo;
    }

    /**
     * Get channelPromotionInfo
     * @return channelPromotionInfo
     **/
    
    public String getChannelPromotionInfo() {
        return channelPromotionInfo;
    }

    public void setChannelPromotionInfo(String channelPromotionInfo) {
        this.channelPromotionInfo = channelPromotionInfo;
    }

    /**
     * Get identityInfo
     * @return identityInfo
     **/
    
    public String getIdentityInfo() {
        return identityInfo;
    }

    public void setIdentityInfo(String identityInfo) {
        this.identityInfo = identityInfo;
    }

    /**
     * Get limitCredit
     * @return limitCredit
     **/
    
    public String getLimitCredit() {
        return limitCredit;
    }

    public void setLimitCredit(String limitCredit) {
        this.limitCredit = limitCredit;
    }

    /**
     * Get csUrl
     * @return csUrl
     **/
    
    public String getCsUrl() {
        return csUrl;
    }

    public void setCsUrl(String csUrl) {
        this.csUrl = csUrl;
    }

    /**
     * Get ypPromotionInfo
     * @return ypPromotionInfo
     **/
    
    public String getYpPromotionInfo() {
        return ypPromotionInfo;
    }

    public void setYpPromotionInfo(String ypPromotionInfo) {
        this.ypPromotionInfo = ypPromotionInfo;
    }

    /**
     * Get businessInfo
     * @return businessInfo
     **/
    
    public String getBusinessInfo() {
        return businessInfo;
    }

    public void setBusinessInfo(String businessInfo) {
        this.businessInfo = businessInfo;
    }

    /**
     * Get token
     * @return token
     **/
    
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @Override
    public String getOperationId() {
        return "payLink";
    }
}
