/*
 * 聚合支付
 * <p>提供聚合支付相关服务（支付下单、公众号配置等功能</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.aggpay.request;

import com.yeepay.yop.sdk.model.BaseRequest;
import com.yeepay.yop.sdk.service.aggpay.model.WechatConfigAddWechatConfigRequestDTOParam;
public class WechatConfigAddRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private WechatConfigAddWechatConfigRequestDTOParam body;


    /**
     * Get body
     * @return body
     **/
    
    public WechatConfigAddWechatConfigRequestDTOParam getBody() {
        return body;
    }

    public void setBody(WechatConfigAddWechatConfigRequestDTOParam body) {
        this.body = body;
    }

    @Override
    public String getOperationId() {
        return "wechatConfigAdd";
    }
}
