/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.account.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * 银行编码为JSBCHINA时必填
 */
public class AccountManageBankAccountOpenJsbcOpenAccountDTOParam implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   *
   */
  @JsonProperty("accountType")
  private String accountType = null;

  /**
   *
   */
  @JsonProperty("bindCardType")
  private String bindCardType = null;

  /**
   *
   */
  @JsonProperty("bindCardNo")
  private String bindCardNo = null;

  /**
   *
   */
  @JsonProperty("bindBankCode")
  private String bindBankCode = null;

  /**
   *
   */
  @JsonProperty("bindAccountName")
  private String bindAccountName = null;

  /**
   *
   */
  @JsonProperty("businessLicenceEffectiveDate")
  private String businessLicenceEffectiveDate = null;

  /**
   *
   */
  @JsonProperty("businessLicenceExpirationDate")
  private String businessLicenceExpirationDate = null;

  /**
   *
   */
  @JsonProperty("legalLicenceEffectiveDate")
  private String legalLicenceEffectiveDate = null;

  /**
   *
   */
  @JsonProperty("legalLicenceExpirationDate")
  private String legalLicenceExpirationDate = null;

  /**
   *
   */
  @JsonProperty("registerAddress")
  private String registerAddress = null;

  /**
   *
   */
  @JsonProperty("organizationNo")
  private String organizationNo = null;

  /**
   *
   */
  @JsonProperty("organizationStart")
  private String organizationStart = null;

  /**
   *
   */
  @JsonProperty("organizationNoEnd")
  private String organizationNoEnd = null;

  /**
   *
   */
  @JsonProperty("taxNo")
  private String taxNo = null;

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/

  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam bindCardType(String bindCardType) {
    this.bindCardType = bindCardType;
    return this;
  }

   /**
   * Get bindCardType
   * @return bindCardType
  **/

  public String getBindCardType() {
    return bindCardType;
  }

  public void setBindCardType(String bindCardType) {
    this.bindCardType = bindCardType;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam bindCardNo(String bindCardNo) {
    this.bindCardNo = bindCardNo;
    return this;
  }

   /**
   * Get bindCardNo
   * @return bindCardNo
  **/

  public String getBindCardNo() {
    return bindCardNo;
  }

  public void setBindCardNo(String bindCardNo) {
    this.bindCardNo = bindCardNo;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam bindBankCode(String bindBankCode) {
    this.bindBankCode = bindBankCode;
    return this;
  }

   /**
   * Get bindBankCode
   * @return bindBankCode
  **/

  public String getBindBankCode() {
    return bindBankCode;
  }

  public void setBindBankCode(String bindBankCode) {
    this.bindBankCode = bindBankCode;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam bindAccountName(String bindAccountName) {
    this.bindAccountName = bindAccountName;
    return this;
  }

   /**
   * Get bindAccountName
   * @return bindAccountName
  **/

  public String getBindAccountName() {
    return bindAccountName;
  }

  public void setBindAccountName(String bindAccountName) {
    this.bindAccountName = bindAccountName;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam businessLicenceEffectiveDate(String businessLicenceEffectiveDate) {
    this.businessLicenceEffectiveDate = businessLicenceEffectiveDate;
    return this;
  }

   /**
   * Get businessLicenceEffectiveDate
   * @return businessLicenceEffectiveDate
  **/

  public String getBusinessLicenceEffectiveDate() {
    return businessLicenceEffectiveDate;
  }

  public void setBusinessLicenceEffectiveDate(String businessLicenceEffectiveDate) {
    this.businessLicenceEffectiveDate = businessLicenceEffectiveDate;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam businessLicenceExpirationDate(String businessLicenceExpirationDate) {
    this.businessLicenceExpirationDate = businessLicenceExpirationDate;
    return this;
  }

   /**
   * Get businessLicenceExpirationDate
   * @return businessLicenceExpirationDate
  **/

  public String getBusinessLicenceExpirationDate() {
    return businessLicenceExpirationDate;
  }

  public void setBusinessLicenceExpirationDate(String businessLicenceExpirationDate) {
    this.businessLicenceExpirationDate = businessLicenceExpirationDate;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam legalLicenceEffectiveDate(String legalLicenceEffectiveDate) {
    this.legalLicenceEffectiveDate = legalLicenceEffectiveDate;
    return this;
  }

   /**
   * Get legalLicenceEffectiveDate
   * @return legalLicenceEffectiveDate
  **/

  public String getLegalLicenceEffectiveDate() {
    return legalLicenceEffectiveDate;
  }

  public void setLegalLicenceEffectiveDate(String legalLicenceEffectiveDate) {
    this.legalLicenceEffectiveDate = legalLicenceEffectiveDate;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam legalLicenceExpirationDate(String legalLicenceExpirationDate) {
    this.legalLicenceExpirationDate = legalLicenceExpirationDate;
    return this;
  }

   /**
   * Get legalLicenceExpirationDate
   * @return legalLicenceExpirationDate
  **/

  public String getLegalLicenceExpirationDate() {
    return legalLicenceExpirationDate;
  }

  public void setLegalLicenceExpirationDate(String legalLicenceExpirationDate) {
    this.legalLicenceExpirationDate = legalLicenceExpirationDate;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam registerAddress(String registerAddress) {
    this.registerAddress = registerAddress;
    return this;
  }

   /**
   * Get registerAddress
   * @return registerAddress
  **/

  public String getRegisterAddress() {
    return registerAddress;
  }

  public void setRegisterAddress(String registerAddress) {
    this.registerAddress = registerAddress;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam organizationNo(String organizationNo) {
    this.organizationNo = organizationNo;
    return this;
  }

   /**
   * Get organizationNo
   * @return organizationNo
  **/

  public String getOrganizationNo() {
    return organizationNo;
  }

  public void setOrganizationNo(String organizationNo) {
    this.organizationNo = organizationNo;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam organizationStart(String organizationStart) {
    this.organizationStart = organizationStart;
    return this;
  }

   /**
   * Get organizationStart
   * @return organizationStart
  **/

  public String getOrganizationStart() {
    return organizationStart;
  }

  public void setOrganizationStart(String organizationStart) {
    this.organizationStart = organizationStart;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam organizationNoEnd(String organizationNoEnd) {
    this.organizationNoEnd = organizationNoEnd;
    return this;
  }

   /**
   * Get organizationNoEnd
   * @return organizationNoEnd
  **/

  public String getOrganizationNoEnd() {
    return organizationNoEnd;
  }

  public void setOrganizationNoEnd(String organizationNoEnd) {
    this.organizationNoEnd = organizationNoEnd;
  }

  public AccountManageBankAccountOpenJsbcOpenAccountDTOParam taxNo(String taxNo) {
    this.taxNo = taxNo;
    return this;
  }

   /**
   * Get taxNo
   * @return taxNo
  **/

  public String getTaxNo() {
    return taxNo;
  }

  public void setTaxNo(String taxNo) {
    this.taxNo = taxNo;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    AccountManageBankAccountOpenJsbcOpenAccountDTOParam accountManageBankAccountOpenJsbcOpenAccountDTOParam = (AccountManageBankAccountOpenJsbcOpenAccountDTOParam) o;
    return ObjectUtils.equals(this.accountType, accountManageBankAccountOpenJsbcOpenAccountDTOParam.accountType) &&
    ObjectUtils.equals(this.bindCardType, accountManageBankAccountOpenJsbcOpenAccountDTOParam.bindCardType) &&
    ObjectUtils.equals(this.bindCardNo, accountManageBankAccountOpenJsbcOpenAccountDTOParam.bindCardNo) &&
    ObjectUtils.equals(this.bindBankCode, accountManageBankAccountOpenJsbcOpenAccountDTOParam.bindBankCode) &&
    ObjectUtils.equals(this.bindAccountName, accountManageBankAccountOpenJsbcOpenAccountDTOParam.bindAccountName) &&
    ObjectUtils.equals(this.businessLicenceEffectiveDate, accountManageBankAccountOpenJsbcOpenAccountDTOParam.businessLicenceEffectiveDate) &&
    ObjectUtils.equals(this.businessLicenceExpirationDate, accountManageBankAccountOpenJsbcOpenAccountDTOParam.businessLicenceExpirationDate) &&
    ObjectUtils.equals(this.legalLicenceEffectiveDate, accountManageBankAccountOpenJsbcOpenAccountDTOParam.legalLicenceEffectiveDate) &&
    ObjectUtils.equals(this.legalLicenceExpirationDate, accountManageBankAccountOpenJsbcOpenAccountDTOParam.legalLicenceExpirationDate) &&
    ObjectUtils.equals(this.registerAddress, accountManageBankAccountOpenJsbcOpenAccountDTOParam.registerAddress) &&
    ObjectUtils.equals(this.organizationNo, accountManageBankAccountOpenJsbcOpenAccountDTOParam.organizationNo) &&
    ObjectUtils.equals(this.organizationStart, accountManageBankAccountOpenJsbcOpenAccountDTOParam.organizationStart) &&
    ObjectUtils.equals(this.organizationNoEnd, accountManageBankAccountOpenJsbcOpenAccountDTOParam.organizationNoEnd) &&
    ObjectUtils.equals(this.taxNo, accountManageBankAccountOpenJsbcOpenAccountDTOParam.taxNo);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(accountType, bindCardType, bindCardNo, bindBankCode, bindAccountName, businessLicenceEffectiveDate, businessLicenceExpirationDate, legalLicenceEffectiveDate, legalLicenceExpirationDate, registerAddress, organizationNo, organizationStart, organizationNoEnd, taxNo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountManageBankAccountOpenJsbcOpenAccountDTOParam {\n");

    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    bindCardType: ").append(toIndentedString(bindCardType)).append("\n");
    sb.append("    bindCardNo: ").append(toIndentedString(bindCardNo)).append("\n");
    sb.append("    bindBankCode: ").append(toIndentedString(bindBankCode)).append("\n");
    sb.append("    bindAccountName: ").append(toIndentedString(bindAccountName)).append("\n");
    sb.append("    businessLicenceEffectiveDate: ").append(toIndentedString(businessLicenceEffectiveDate)).append("\n");
    sb.append("    businessLicenceExpirationDate: ").append(toIndentedString(businessLicenceExpirationDate)).append("\n");
    sb.append("    legalLicenceEffectiveDate: ").append(toIndentedString(legalLicenceEffectiveDate)).append("\n");
    sb.append("    legalLicenceExpirationDate: ").append(toIndentedString(legalLicenceExpirationDate)).append("\n");
    sb.append("    registerAddress: ").append(toIndentedString(registerAddress)).append("\n");
    sb.append("    organizationNo: ").append(toIndentedString(organizationNo)).append("\n");
    sb.append("    organizationStart: ").append(toIndentedString(organizationStart)).append("\n");
    sb.append("    organizationNoEnd: ").append(toIndentedString(organizationNoEnd)).append("\n");
    sb.append("    taxNo: ").append(toIndentedString(taxNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

