/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.account.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * EnterpriseTokenPayOrderTokenPaymentResponseDtoResult
 */
public class EnterpriseTokenPayOrderTokenPaymentResponseDtoResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 返回码
   */
  @JsonProperty("code")
  private String code = null;

  /**
   * 描述信息
   */
  @JsonProperty("message")
  private String message = null;

  /**
   * token
   */
  @JsonProperty("token")
  private String token = null;

  /**
   * 订单状态
   */
  @JsonProperty("orderStatus")
  private String orderStatus = null;

  public EnterpriseTokenPayOrderTokenPaymentResponseDtoResult code(String code) {
    this.code = code;
    return this;
  }

   /**
   * 返回码
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public EnterpriseTokenPayOrderTokenPaymentResponseDtoResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * 描述信息
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public EnterpriseTokenPayOrderTokenPaymentResponseDtoResult token(String token) {
    this.token = token;
    return this;
  }

   /**
   * token
   * @return token
  **/

  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public EnterpriseTokenPayOrderTokenPaymentResponseDtoResult orderStatus(String orderStatus) {
    this.orderStatus = orderStatus;
    return this;
  }

   /**
   * 订单状态
   * @return orderStatus
  **/

  public String getOrderStatus() {
    return orderStatus;
  }

  public void setOrderStatus(String orderStatus) {
    this.orderStatus = orderStatus;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    EnterpriseTokenPayOrderTokenPaymentResponseDtoResult enterpriseTokenPayOrderTokenPaymentResponseDtoResult = (EnterpriseTokenPayOrderTokenPaymentResponseDtoResult) o;
    return ObjectUtils.equals(this.code, enterpriseTokenPayOrderTokenPaymentResponseDtoResult.code) &&
    ObjectUtils.equals(this.message, enterpriseTokenPayOrderTokenPaymentResponseDtoResult.message) &&
    ObjectUtils.equals(this.token, enterpriseTokenPayOrderTokenPaymentResponseDtoResult.token) &&
    ObjectUtils.equals(this.orderStatus, enterpriseTokenPayOrderTokenPaymentResponseDtoResult.orderStatus);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, token, orderStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnterpriseTokenPayOrderTokenPaymentResponseDtoResult {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    orderStatus: ").append(toIndentedString(orderStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

