/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.account.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * 查询付款到个人信息详情
 */
public class IndividualDTO implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * &lt;p&gt;商户编号&lt;/p&gt;
   */
  @JsonProperty("merchantNo")
  private String merchantNo = null;

  /**
   * &lt;p&gt;收款方id&lt;/p&gt;
   */
  @JsonProperty("id")
  private Long id = null;

  /**
   * &lt;pre&gt;个人姓名&lt;/pre&gt;
   */
  @JsonProperty("name")
  private String name = null;

  /**
   * &lt;p&gt;手机号&lt;/p&gt;
   */
  @JsonProperty("phone")
  private String phone = null;

  /**
   * &lt;p&gt;证件类型&lt;/p&gt;
   */
  @JsonProperty("certificateType")
  private String certificateType = null;

  /**
   * &lt;p&gt;证件号&lt;/p&gt;
   */
  @JsonProperty("certificateNo")
  private String certificateNo = null;

  public IndividualDTO merchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
    return this;
  }

   /**
   * &lt;p&gt;商户编号&lt;/p&gt;
   * @return merchantNo
  **/

  public String getMerchantNo() {
    return merchantNo;
  }

  public void setMerchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
  }

  public IndividualDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * &lt;p&gt;收款方id&lt;/p&gt;
   * @return id
  **/

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public IndividualDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * &lt;pre&gt;个人姓名&lt;/pre&gt;
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IndividualDTO phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * &lt;p&gt;手机号&lt;/p&gt;
   * @return phone
  **/

  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public IndividualDTO certificateType(String certificateType) {
    this.certificateType = certificateType;
    return this;
  }

   /**
   * &lt;p&gt;证件类型&lt;/p&gt;
   * @return certificateType
  **/

  public String getCertificateType() {
    return certificateType;
  }

  public void setCertificateType(String certificateType) {
    this.certificateType = certificateType;
  }

  public IndividualDTO certificateNo(String certificateNo) {
    this.certificateNo = certificateNo;
    return this;
  }

   /**
   * &lt;p&gt;证件号&lt;/p&gt;
   * @return certificateNo
  **/

  public String getCertificateNo() {
    return certificateNo;
  }

  public void setCertificateNo(String certificateNo) {
    this.certificateNo = certificateNo;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    IndividualDTO individualDTO = (IndividualDTO) o;
    return ObjectUtils.equals(this.merchantNo, individualDTO.merchantNo) &&
    ObjectUtils.equals(this.id, individualDTO.id) &&
    ObjectUtils.equals(this.name, individualDTO.name) &&
    ObjectUtils.equals(this.phone, individualDTO.phone) &&
    ObjectUtils.equals(this.certificateType, individualDTO.certificateType) &&
    ObjectUtils.equals(this.certificateNo, individualDTO.certificateNo);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(merchantNo, id, name, phone, certificateType, certificateNo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndividualDTO {\n");

    sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    certificateType: ").append(toIndentedString(certificateType)).append("\n");
    sb.append("    certificateNo: ").append(toIndentedString(certificateNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

