/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.account.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 *
 */
public class PayBatchOrderBatchRemitExtInfoDTOParam implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   *
   */
  @JsonProperty("requestIP")
  private String requestIP = null;

  /**
   *
   */
  @JsonProperty("terminalType")
  private String terminalType = null;

  public PayBatchOrderBatchRemitExtInfoDTOParam requestIP(String requestIP) {
    this.requestIP = requestIP;
    return this;
  }

   /**
   * Get requestIP
   * @return requestIP
  **/

  public String getRequestIP() {
    return requestIP;
  }

  public void setRequestIP(String requestIP) {
    this.requestIP = requestIP;
  }

  public PayBatchOrderBatchRemitExtInfoDTOParam terminalType(String terminalType) {
    this.terminalType = terminalType;
    return this;
  }

   /**
   * Get terminalType
   * @return terminalType
  **/

  public String getTerminalType() {
    return terminalType;
  }

  public void setTerminalType(String terminalType) {
    this.terminalType = terminalType;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    PayBatchOrderBatchRemitExtInfoDTOParam payBatchOrderBatchRemitExtInfoDTOParam = (PayBatchOrderBatchRemitExtInfoDTOParam) o;
    return ObjectUtils.equals(this.requestIP, payBatchOrderBatchRemitExtInfoDTOParam.requestIP) &&
    ObjectUtils.equals(this.terminalType, payBatchOrderBatchRemitExtInfoDTOParam.terminalType);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(requestIP, terminalType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayBatchOrderBatchRemitExtInfoDTOParam {\n");

    sb.append("    requestIP: ").append(toIndentedString(requestIP)).append("\n");
    sb.append("    terminalType: ").append(toIndentedString(terminalType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

