/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.account.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.yeepay.yop.sdk.service.account.model.IndividualDTO;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * 查询付款到个人信息
 */
public class QueryIndividualRespDTO implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * &lt;p&gt;返回码,响应成功时返回UA00000&lt;/p&gt;
   */
  @JsonProperty("returnCode")
  private String returnCode = null;

  /**
   * &lt;p&gt;返回信息&lt;/p&gt;
   */
  @JsonProperty("returnMsg")
  private String returnMsg = null;

  /**
   * &lt;p&gt;返回详情&lt;/p&gt;
   */
  @JsonProperty("resultList")
  private List<IndividualDTO> resultList = null;

  public QueryIndividualRespDTO returnCode(String returnCode) {
    this.returnCode = returnCode;
    return this;
  }

   /**
   * &lt;p&gt;返回码,响应成功时返回UA00000&lt;/p&gt;
   * @return returnCode
  **/

  public String getReturnCode() {
    return returnCode;
  }

  public void setReturnCode(String returnCode) {
    this.returnCode = returnCode;
  }

  public QueryIndividualRespDTO returnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
    return this;
  }

   /**
   * &lt;p&gt;返回信息&lt;/p&gt;
   * @return returnMsg
  **/

  public String getReturnMsg() {
    return returnMsg;
  }

  public void setReturnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
  }

  public QueryIndividualRespDTO resultList(List<IndividualDTO> resultList) {
    this.resultList = resultList;
    return this;
  }

  public QueryIndividualRespDTO addResultListItem(IndividualDTO resultListItem) {
    if (this.resultList == null) {
      this.resultList = new ArrayList<>();
    }
    this.resultList.add(resultListItem);
    return this;
  }

   /**
   * &lt;p&gt;返回详情&lt;/p&gt;
   * @return resultList
  **/

  public List<IndividualDTO> getResultList() {
    return resultList;
  }

  public void setResultList(List<IndividualDTO> resultList) {
    this.resultList = resultList;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    QueryIndividualRespDTO queryIndividualRespDTO = (QueryIndividualRespDTO) o;
    return ObjectUtils.equals(this.returnCode, queryIndividualRespDTO.returnCode) &&
    ObjectUtils.equals(this.returnMsg, queryIndividualRespDTO.returnMsg) &&
    ObjectUtils.equals(this.resultList, queryIndividualRespDTO.resultList);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(returnCode, returnMsg, resultList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryIndividualRespDTO {\n");

    sb.append("    returnCode: ").append(toIndentedString(returnCode)).append("\n");
    sb.append("    returnMsg: ").append(toIndentedString(returnMsg)).append("\n");
    sb.append("    resultList: ").append(toIndentedString(resultList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

