/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.account.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * ReceiptGatherBatchReceiptRespDTOResult
 */
public class ReceiptGatherBatchReceiptRespDTOResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 返回码
   */
  @JsonProperty("returnCode")
  private String returnCode = null;

  /**
   * 返回信息
   */
  @JsonProperty("returnMsg")
  private String returnMsg = null;

  /**
   * 返回信息
   */
  @JsonProperty("data")
  private String data = null;

  public ReceiptGatherBatchReceiptRespDTOResult returnCode(String returnCode) {
    this.returnCode = returnCode;
    return this;
  }

   /**
   * 返回码
   * @return returnCode
  **/

  public String getReturnCode() {
    return returnCode;
  }

  public void setReturnCode(String returnCode) {
    this.returnCode = returnCode;
  }

  public ReceiptGatherBatchReceiptRespDTOResult returnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
    return this;
  }

   /**
   * 返回信息
   * @return returnMsg
  **/

  public String getReturnMsg() {
    return returnMsg;
  }

  public void setReturnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
  }

  public ReceiptGatherBatchReceiptRespDTOResult data(String data) {
    this.data = data;
    return this;
  }

   /**
   * 返回信息
   * @return data
  **/

  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    ReceiptGatherBatchReceiptRespDTOResult receiptGatherBatchReceiptRespDTOResult = (ReceiptGatherBatchReceiptRespDTOResult) o;
    return ObjectUtils.equals(this.returnCode, receiptGatherBatchReceiptRespDTOResult.returnCode) &&
    ObjectUtils.equals(this.returnMsg, receiptGatherBatchReceiptRespDTOResult.returnMsg) &&
    ObjectUtils.equals(this.data, receiptGatherBatchReceiptRespDTOResult.data);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(returnCode, returnMsg, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReceiptGatherBatchReceiptRespDTOResult {\n");

    sb.append("    returnCode: ").append(toIndentedString(returnCode)).append("\n");
    sb.append("    returnMsg: ").append(toIndentedString(returnMsg)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

