/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.account.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.yeepay.yop.sdk.service.account.model.RechargeAccountBookQueryRechargeOrderApiDtoResult;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * RechargeAccountBookQueryRechargePageQueryResponseDTOResult
 */
public class RechargeAccountBookQueryRechargePageQueryResponseDTOResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 返回码
   */
  @JsonProperty("returnCode")
  private String returnCode = null;

  /**
   * 返回描述
   */
  @JsonProperty("returnMsg")
  private String returnMsg = null;

  /**
   * 总笔数
   */
  @JsonProperty("totalCount")
  private Long totalCount = null;

  /**
   * 列表
   */
  @JsonProperty("list")
  private List<RechargeAccountBookQueryRechargeOrderApiDtoResult> list = null;

  public RechargeAccountBookQueryRechargePageQueryResponseDTOResult returnCode(String returnCode) {
    this.returnCode = returnCode;
    return this;
  }

   /**
   * 返回码
   * @return returnCode
  **/

  public String getReturnCode() {
    return returnCode;
  }

  public void setReturnCode(String returnCode) {
    this.returnCode = returnCode;
  }

  public RechargeAccountBookQueryRechargePageQueryResponseDTOResult returnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
    return this;
  }

   /**
   * 返回描述
   * @return returnMsg
  **/

  public String getReturnMsg() {
    return returnMsg;
  }

  public void setReturnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
  }

  public RechargeAccountBookQueryRechargePageQueryResponseDTOResult totalCount(Long totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * 总笔数
   * @return totalCount
  **/

  public Long getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
  }

  public RechargeAccountBookQueryRechargePageQueryResponseDTOResult list(List<RechargeAccountBookQueryRechargeOrderApiDtoResult> list) {
    this.list = list;
    return this;
  }

  public RechargeAccountBookQueryRechargePageQueryResponseDTOResult addListItem(RechargeAccountBookQueryRechargeOrderApiDtoResult listItem) {
    if (this.list == null) {
      this.list = new ArrayList<>();
    }
    this.list.add(listItem);
    return this;
  }

   /**
   * 列表
   * @return list
  **/

  public List<RechargeAccountBookQueryRechargeOrderApiDtoResult> getList() {
    return list;
  }

  public void setList(List<RechargeAccountBookQueryRechargeOrderApiDtoResult> list) {
    this.list = list;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    RechargeAccountBookQueryRechargePageQueryResponseDTOResult rechargeAccountBookQueryRechargePageQueryResponseDTOResult = (RechargeAccountBookQueryRechargePageQueryResponseDTOResult) o;
    return ObjectUtils.equals(this.returnCode, rechargeAccountBookQueryRechargePageQueryResponseDTOResult.returnCode) &&
    ObjectUtils.equals(this.returnMsg, rechargeAccountBookQueryRechargePageQueryResponseDTOResult.returnMsg) &&
    ObjectUtils.equals(this.totalCount, rechargeAccountBookQueryRechargePageQueryResponseDTOResult.totalCount) &&
    ObjectUtils.equals(this.list, rechargeAccountBookQueryRechargePageQueryResponseDTOResult.list);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(returnCode, returnMsg, totalCount, list);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RechargeAccountBookQueryRechargePageQueryResponseDTOResult {\n");

    sb.append("    returnCode: ").append(toIndentedString(returnCode)).append("\n");
    sb.append("    returnMsg: ").append(toIndentedString(returnMsg)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

