/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.account.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * SupplierQuerySupplierDTOResult
 */
public class SupplierQuerySupplierDTOResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 商户编号
   */
  @JsonProperty("merchantNo")
  private String merchantNo = null;

  /**
   * 供应商id
   */
  @JsonProperty("supplierId")
  private Long supplierId = null;

  /**
   * 供应商类型
   */
  @JsonProperty("supplierType")
  private String supplierType = null;

  /**
   * 供应商名称
   */
  @JsonProperty("supplierName")
  private String supplierName = null;

  /**
   * 供应商资质编码
   */
  @JsonProperty("supplierQualLicenceNo")
  private String supplierQualLicenceNo = null;

  /**
   * 供应商创建时间
   */
  @JsonProperty("createTime")
  private String createTime = null;

  public SupplierQuerySupplierDTOResult merchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
    return this;
  }

   /**
   * 商户编号
   * @return merchantNo
  **/

  public String getMerchantNo() {
    return merchantNo;
  }

  public void setMerchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
  }

  public SupplierQuerySupplierDTOResult supplierId(Long supplierId) {
    this.supplierId = supplierId;
    return this;
  }

   /**
   * 供应商id
   * @return supplierId
  **/

  public Long getSupplierId() {
    return supplierId;
  }

  public void setSupplierId(Long supplierId) {
    this.supplierId = supplierId;
  }

  public SupplierQuerySupplierDTOResult supplierType(String supplierType) {
    this.supplierType = supplierType;
    return this;
  }

   /**
   * 供应商类型
   * @return supplierType
  **/

  public String getSupplierType() {
    return supplierType;
  }

  public void setSupplierType(String supplierType) {
    this.supplierType = supplierType;
  }

  public SupplierQuerySupplierDTOResult supplierName(String supplierName) {
    this.supplierName = supplierName;
    return this;
  }

   /**
   * 供应商名称
   * @return supplierName
  **/

  public String getSupplierName() {
    return supplierName;
  }

  public void setSupplierName(String supplierName) {
    this.supplierName = supplierName;
  }

  public SupplierQuerySupplierDTOResult supplierQualLicenceNo(String supplierQualLicenceNo) {
    this.supplierQualLicenceNo = supplierQualLicenceNo;
    return this;
  }

   /**
   * 供应商资质编码
   * @return supplierQualLicenceNo
  **/

  public String getSupplierQualLicenceNo() {
    return supplierQualLicenceNo;
  }

  public void setSupplierQualLicenceNo(String supplierQualLicenceNo) {
    this.supplierQualLicenceNo = supplierQualLicenceNo;
  }

  public SupplierQuerySupplierDTOResult createTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * 供应商创建时间
   * @return createTime
  **/

  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    SupplierQuerySupplierDTOResult supplierQuerySupplierDTOResult = (SupplierQuerySupplierDTOResult) o;
    return ObjectUtils.equals(this.merchantNo, supplierQuerySupplierDTOResult.merchantNo) &&
    ObjectUtils.equals(this.supplierId, supplierQuerySupplierDTOResult.supplierId) &&
    ObjectUtils.equals(this.supplierType, supplierQuerySupplierDTOResult.supplierType) &&
    ObjectUtils.equals(this.supplierName, supplierQuerySupplierDTOResult.supplierName) &&
    ObjectUtils.equals(this.supplierQualLicenceNo, supplierQuerySupplierDTOResult.supplierQualLicenceNo) &&
    ObjectUtils.equals(this.createTime, supplierQuerySupplierDTOResult.createTime);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(merchantNo, supplierId, supplierType, supplierName, supplierQualLicenceNo, createTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupplierQuerySupplierDTOResult {\n");

    sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
    sb.append("    supplierId: ").append(toIndentedString(supplierId)).append("\n");
    sb.append("    supplierType: ").append(toIndentedString(supplierType)).append("\n");
    sb.append("    supplierName: ").append(toIndentedString(supplierName)).append("\n");
    sb.append("    supplierQualLicenceNo: ").append(toIndentedString(supplierQualLicenceNo)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

