/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.account.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.io.Serializable;

/**
 * WithdrawQueryMGWithdrawOrderQueryRespDTOResult
 */
public class WithdrawQueryMGWithdrawOrderQueryRespDTOResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 返回码
   */
  @JsonProperty("returnCode")
  private String returnCode = null;

  /**
   * 返回信息
   */
  @JsonProperty("returnMsg")
  private String returnMsg = null;

  /**
   * 商户请求号
   */
  @JsonProperty("requestNo")
  private String requestNo = null;

  /**
   * 易宝提现订单号
   */
  @JsonProperty("orderNo")
  private String orderNo = null;

  /**
   * 商户编号
   */
  @JsonProperty("merchantNo")
  private String merchantNo = null;

  /**
   * 提现金额
   */
  @JsonProperty("orderAmount")
  private BigDecimal orderAmount = null;

  /**
   * 到账金额
   */
  @JsonProperty("receiveAmount")
  private BigDecimal receiveAmount = null;

  /**
   * 扣账金额
   */
  @JsonProperty("debitAmount")
  private BigDecimal debitAmount = null;

  /**
   * 提现下单时间
   */
  @JsonProperty("orderTime")
  private String orderTime = null;

  /**
   * 提现完成时间
   */
  @JsonProperty("finishTime")
  private String finishTime = null;

  /**
   * 提现订单状态
   */
  @JsonProperty("status")
  private String status = null;

  /**
   * 失败原因
   */
  @JsonProperty("failReason")
  private String failReason = null;

  /**
   * 手续费承担方商编
   */
  @JsonProperty("feeUndertakerMerchantNo")
  private String feeUndertakerMerchantNo = null;

  /**
   * 手续费
   */
  @JsonProperty("fee")
  private BigDecimal fee = null;

  /**
   * 到账类型
   */
  @JsonProperty("receiveType")
  private String receiveType = null;

  /**
   * 开户名
   */
  @JsonProperty("accountName")
  private String accountName = null;

  /**
   * 银行账号
   */
  @JsonProperty("accountNo")
  private String accountNo = null;

  /**
   * 开户行名称
   */
  @JsonProperty("bankName")
  private String bankName = null;

  /**
   * 冲退标识
   */
  @JsonProperty("isReversed")
  private Boolean isReversed = null;

  /**
   * 冲退时间
   */
  @JsonProperty("reverseTime")
  private String reverseTime = null;

  /**
   * 备注
   */
  @JsonProperty("remark")
  private String remark = null;

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult returnCode(String returnCode) {
    this.returnCode = returnCode;
    return this;
  }

   /**
   * 返回码
   * @return returnCode
  **/

  public String getReturnCode() {
    return returnCode;
  }

  public void setReturnCode(String returnCode) {
    this.returnCode = returnCode;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult returnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
    return this;
  }

   /**
   * 返回信息
   * @return returnMsg
  **/

  public String getReturnMsg() {
    return returnMsg;
  }

  public void setReturnMsg(String returnMsg) {
    this.returnMsg = returnMsg;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult requestNo(String requestNo) {
    this.requestNo = requestNo;
    return this;
  }

   /**
   * 商户请求号
   * @return requestNo
  **/

  public String getRequestNo() {
    return requestNo;
  }

  public void setRequestNo(String requestNo) {
    this.requestNo = requestNo;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult orderNo(String orderNo) {
    this.orderNo = orderNo;
    return this;
  }

   /**
   * 易宝提现订单号
   * @return orderNo
  **/

  public String getOrderNo() {
    return orderNo;
  }

  public void setOrderNo(String orderNo) {
    this.orderNo = orderNo;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult merchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
    return this;
  }

   /**
   * 商户编号
   * @return merchantNo
  **/

  public String getMerchantNo() {
    return merchantNo;
  }

  public void setMerchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult orderAmount(BigDecimal orderAmount) {
    this.orderAmount = orderAmount;
    return this;
  }

   /**
   * 提现金额
   * @return orderAmount
  **/

  public BigDecimal getOrderAmount() {
    return orderAmount;
  }

  public void setOrderAmount(BigDecimal orderAmount) {
    this.orderAmount = orderAmount;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult receiveAmount(BigDecimal receiveAmount) {
    this.receiveAmount = receiveAmount;
    return this;
  }

   /**
   * 到账金额
   * @return receiveAmount
  **/

  public BigDecimal getReceiveAmount() {
    return receiveAmount;
  }

  public void setReceiveAmount(BigDecimal receiveAmount) {
    this.receiveAmount = receiveAmount;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult debitAmount(BigDecimal debitAmount) {
    this.debitAmount = debitAmount;
    return this;
  }

   /**
   * 扣账金额
   * @return debitAmount
  **/

  public BigDecimal getDebitAmount() {
    return debitAmount;
  }

  public void setDebitAmount(BigDecimal debitAmount) {
    this.debitAmount = debitAmount;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult orderTime(String orderTime) {
    this.orderTime = orderTime;
    return this;
  }

   /**
   * 提现下单时间
   * @return orderTime
  **/

  public String getOrderTime() {
    return orderTime;
  }

  public void setOrderTime(String orderTime) {
    this.orderTime = orderTime;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult finishTime(String finishTime) {
    this.finishTime = finishTime;
    return this;
  }

   /**
   * 提现完成时间
   * @return finishTime
  **/

  public String getFinishTime() {
    return finishTime;
  }

  public void setFinishTime(String finishTime) {
    this.finishTime = finishTime;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult status(String status) {
    this.status = status;
    return this;
  }

   /**
   * 提现订单状态
   * @return status
  **/

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult failReason(String failReason) {
    this.failReason = failReason;
    return this;
  }

   /**
   * 失败原因
   * @return failReason
  **/

  public String getFailReason() {
    return failReason;
  }

  public void setFailReason(String failReason) {
    this.failReason = failReason;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult feeUndertakerMerchantNo(String feeUndertakerMerchantNo) {
    this.feeUndertakerMerchantNo = feeUndertakerMerchantNo;
    return this;
  }

   /**
   * 手续费承担方商编
   * @return feeUndertakerMerchantNo
  **/

  public String getFeeUndertakerMerchantNo() {
    return feeUndertakerMerchantNo;
  }

  public void setFeeUndertakerMerchantNo(String feeUndertakerMerchantNo) {
    this.feeUndertakerMerchantNo = feeUndertakerMerchantNo;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult fee(BigDecimal fee) {
    this.fee = fee;
    return this;
  }

   /**
   * 手续费
   * @return fee
  **/

  public BigDecimal getFee() {
    return fee;
  }

  public void setFee(BigDecimal fee) {
    this.fee = fee;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult receiveType(String receiveType) {
    this.receiveType = receiveType;
    return this;
  }

   /**
   * 到账类型
   * @return receiveType
  **/

  public String getReceiveType() {
    return receiveType;
  }

  public void setReceiveType(String receiveType) {
    this.receiveType = receiveType;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * 开户名
   * @return accountName
  **/

  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult accountNo(String accountNo) {
    this.accountNo = accountNo;
    return this;
  }

   /**
   * 银行账号
   * @return accountNo
  **/

  public String getAccountNo() {
    return accountNo;
  }

  public void setAccountNo(String accountNo) {
    this.accountNo = accountNo;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * 开户行名称
   * @return bankName
  **/

  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult isReversed(Boolean isReversed) {
    this.isReversed = isReversed;
    return this;
  }

   /**
   * 冲退标识
   * @return isReversed
  **/

  public Boolean isIsReversed() {
    return isReversed;
  }

  public void setIsReversed(Boolean isReversed) {
    this.isReversed = isReversed;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult reverseTime(String reverseTime) {
    this.reverseTime = reverseTime;
    return this;
  }

   /**
   * 冲退时间
   * @return reverseTime
  **/

  public String getReverseTime() {
    return reverseTime;
  }

  public void setReverseTime(String reverseTime) {
    this.reverseTime = reverseTime;
  }

  public WithdrawQueryMGWithdrawOrderQueryRespDTOResult remark(String remark) {
    this.remark = remark;
    return this;
  }

   /**
   * 备注
   * @return remark
  **/

  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    WithdrawQueryMGWithdrawOrderQueryRespDTOResult withdrawQueryMGWithdrawOrderQueryRespDTOResult = (WithdrawQueryMGWithdrawOrderQueryRespDTOResult) o;
    return ObjectUtils.equals(this.returnCode, withdrawQueryMGWithdrawOrderQueryRespDTOResult.returnCode) &&
    ObjectUtils.equals(this.returnMsg, withdrawQueryMGWithdrawOrderQueryRespDTOResult.returnMsg) &&
    ObjectUtils.equals(this.requestNo, withdrawQueryMGWithdrawOrderQueryRespDTOResult.requestNo) &&
    ObjectUtils.equals(this.orderNo, withdrawQueryMGWithdrawOrderQueryRespDTOResult.orderNo) &&
    ObjectUtils.equals(this.merchantNo, withdrawQueryMGWithdrawOrderQueryRespDTOResult.merchantNo) &&
    ObjectUtils.equals(this.orderAmount, withdrawQueryMGWithdrawOrderQueryRespDTOResult.orderAmount) &&
    ObjectUtils.equals(this.receiveAmount, withdrawQueryMGWithdrawOrderQueryRespDTOResult.receiveAmount) &&
    ObjectUtils.equals(this.debitAmount, withdrawQueryMGWithdrawOrderQueryRespDTOResult.debitAmount) &&
    ObjectUtils.equals(this.orderTime, withdrawQueryMGWithdrawOrderQueryRespDTOResult.orderTime) &&
    ObjectUtils.equals(this.finishTime, withdrawQueryMGWithdrawOrderQueryRespDTOResult.finishTime) &&
    ObjectUtils.equals(this.status, withdrawQueryMGWithdrawOrderQueryRespDTOResult.status) &&
    ObjectUtils.equals(this.failReason, withdrawQueryMGWithdrawOrderQueryRespDTOResult.failReason) &&
    ObjectUtils.equals(this.feeUndertakerMerchantNo, withdrawQueryMGWithdrawOrderQueryRespDTOResult.feeUndertakerMerchantNo) &&
    ObjectUtils.equals(this.fee, withdrawQueryMGWithdrawOrderQueryRespDTOResult.fee) &&
    ObjectUtils.equals(this.receiveType, withdrawQueryMGWithdrawOrderQueryRespDTOResult.receiveType) &&
    ObjectUtils.equals(this.accountName, withdrawQueryMGWithdrawOrderQueryRespDTOResult.accountName) &&
    ObjectUtils.equals(this.accountNo, withdrawQueryMGWithdrawOrderQueryRespDTOResult.accountNo) &&
    ObjectUtils.equals(this.bankName, withdrawQueryMGWithdrawOrderQueryRespDTOResult.bankName) &&
    ObjectUtils.equals(this.isReversed, withdrawQueryMGWithdrawOrderQueryRespDTOResult.isReversed) &&
    ObjectUtils.equals(this.reverseTime, withdrawQueryMGWithdrawOrderQueryRespDTOResult.reverseTime) &&
    ObjectUtils.equals(this.remark, withdrawQueryMGWithdrawOrderQueryRespDTOResult.remark);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(returnCode, returnMsg, requestNo, orderNo, merchantNo, orderAmount, receiveAmount, debitAmount, orderTime, finishTime, status, failReason, feeUndertakerMerchantNo, fee, receiveType, accountName, accountNo, bankName, isReversed, reverseTime, remark);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WithdrawQueryMGWithdrawOrderQueryRespDTOResult {\n");

    sb.append("    returnCode: ").append(toIndentedString(returnCode)).append("\n");
    sb.append("    returnMsg: ").append(toIndentedString(returnMsg)).append("\n");
    sb.append("    requestNo: ").append(toIndentedString(requestNo)).append("\n");
    sb.append("    orderNo: ").append(toIndentedString(orderNo)).append("\n");
    sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
    sb.append("    orderAmount: ").append(toIndentedString(orderAmount)).append("\n");
    sb.append("    receiveAmount: ").append(toIndentedString(receiveAmount)).append("\n");
    sb.append("    debitAmount: ").append(toIndentedString(debitAmount)).append("\n");
    sb.append("    orderTime: ").append(toIndentedString(orderTime)).append("\n");
    sb.append("    finishTime: ").append(toIndentedString(finishTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    failReason: ").append(toIndentedString(failReason)).append("\n");
    sb.append("    feeUndertakerMerchantNo: ").append(toIndentedString(feeUndertakerMerchantNo)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    receiveType: ").append(toIndentedString(receiveType)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    accountNo: ").append(toIndentedString(accountNo)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    isReversed: ").append(toIndentedString(isReversed)).append("\n");
    sb.append("    reverseTime: ").append(toIndentedString(reverseTime)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

