/*
 * 刷脸付
 * <p>Facepay是一款部署在支付公司的应用内刷脸支付产品，用于代替现有的H5形态的快捷支付产品、以刷脸技术来代替短信验证啊技术，在app环境中提供安全，快捷，不可抵赖的支付体验。</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.facepay.request;

import com.yeepay.yop.sdk.model.BaseRequest;
public class FacepayProxyOpenFaceAccountRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String faceImageFirst;

    private String faceImageSecond;

    private String faceImageThird;

    private String collectType;

    private String collectDevice;

    private String orderToken;

    private String bizSystem;

    private String mtToken;

    private String memberNo;


    /**
     * Get faceImageFirst
     * @return faceImageFirst
     **/
    
    public String getFaceImageFirst() {
        return faceImageFirst;
    }

    public void setFaceImageFirst(String faceImageFirst) {
        this.faceImageFirst = faceImageFirst;
    }

    /**
     * Get faceImageSecond
     * @return faceImageSecond
     **/
    
    public String getFaceImageSecond() {
        return faceImageSecond;
    }

    public void setFaceImageSecond(String faceImageSecond) {
        this.faceImageSecond = faceImageSecond;
    }

    /**
     * Get faceImageThird
     * @return faceImageThird
     **/
    
    public String getFaceImageThird() {
        return faceImageThird;
    }

    public void setFaceImageThird(String faceImageThird) {
        this.faceImageThird = faceImageThird;
    }

    /**
     * Get collectType
     * @return collectType
     **/
    
    public String getCollectType() {
        return collectType;
    }

    public void setCollectType(String collectType) {
        this.collectType = collectType;
    }

    /**
     * Get collectDevice
     * @return collectDevice
     **/
    
    public String getCollectDevice() {
        return collectDevice;
    }

    public void setCollectDevice(String collectDevice) {
        this.collectDevice = collectDevice;
    }

    /**
     * Get orderToken
     * @return orderToken
     **/
    
    public String getOrderToken() {
        return orderToken;
    }

    public void setOrderToken(String orderToken) {
        this.orderToken = orderToken;
    }

    /**
     * Get bizSystem
     * @return bizSystem
     **/
    
    public String getBizSystem() {
        return bizSystem;
    }

    public void setBizSystem(String bizSystem) {
        this.bizSystem = bizSystem;
    }

    /**
     * Get mtToken
     * @return mtToken
     **/
    
    public String getMtToken() {
        return mtToken;
    }

    public void setMtToken(String mtToken) {
        this.mtToken = mtToken;
    }

    /**
     * Get memberNo
     * @return memberNo
     **/
    
    public String getMemberNo() {
        return memberNo;
    }

    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo;
    }

    @Override
    public String getOperationId() {
        return "facepayProxyOpenFaceAccount";
    }
}
