/*
 * 营销
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.promtion;

import com.yeepay.yop.sdk.exception.YopClientException;
import com.yeepay.yop.sdk.service.promtion.request.*;
import com.yeepay.yop.sdk.service.promtion.response.*;

public interface PromtionClient {

    /**
     * 营销积分账户开立
     * 营销积分账户开立
     * @return PointCreateResponse
     * @throws YopClientException if fails to make API call
     */
    PointCreateResponse pointCreate(PointCreateRequest request) throws YopClientException;

    /**
     * 营销账户积分变更
     * 营销账户积分变更
     * @return PointOperateResponse
     * @throws YopClientException if fails to make API call
     */
    PointOperateResponse pointOperate(PointOperateRequest request) throws YopClientException;

    /**
     * 营销账户积分查询
     * 营销账户积分查询
     * @return PointQueryResponse
     * @throws YopClientException if fails to make API call
     */
    PointQueryResponse pointQuery(PointQueryRequest request) throws YopClientException;

    /**
     * 申请营销补贴
     * 商户申请营销补贴
     * @return SubsidyApplyResponse
     * @throws YopClientException if fails to make API call
     */
    SubsidyApplyResponse subsidyApply(SubsidyApplyRequest request) throws YopClientException;

    /**
     * 申请营销补贴退回
     * 商户申请营销补贴退回
     * @return SubsidyBackResponse
     * @throws YopClientException if fails to make API call
     */
    SubsidyBackResponse subsidyBack(SubsidyBackRequest request) throws YopClientException;

    /**
     * 查询营销补贴退回
     * 商户申请营销补贴退回查询
     * @return SubsidyBackQueryResponse
     * @throws YopClientException if fails to make API call
     */
    SubsidyBackQueryResponse subsidyBackQuery(SubsidyBackQueryRequest request) throws YopClientException;

    /**
     * 查询营销补贴
     * 商户申请营销补贴查询
     * @return SubsidyQueryResponse
     * @throws YopClientException if fails to make API call
     */
    SubsidyQueryResponse subsidyQuery(SubsidyQueryRequest request) throws YopClientException;


    /**
     * Shuts down this client object, releasing any resources that might be held open. This is an optional method, and
     * callers are not expected to call it, but can if they want to explicitly release any open resources. Once a client
     * has been shutdown, it should not be used to make any more requests.
     */
    void shutdown();
}
