/*
 * 大禹
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.p2f.response;





import com.yeepay.yop.sdk.model.BaseResponse;

import com.yeepay.yop.sdk.service.p2f.model.ZzdfQueryQueryRechargeAndPayRspDTOResult;

public class ZzdfQueryResponse extends BaseResponse {
    private static final long serialVersionUID = 1L;

    private ZzdfQueryQueryRechargeAndPayRspDTOResult result;

    public ZzdfQueryQueryRechargeAndPayRspDTOResult getResult() {
        return result;
    }

    public void setResult(ZzdfQueryQueryRechargeAndPayRspDTOResult result) {
        this.result = result;
    }

}
