/*
 * pos
 * <p>pos对外接口</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.pos.request;

import com.yeepay.yop.sdk.model.BaseRequest;
public class GetPosInfoDtosRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String customerNumber;

    private String posCati;

    private String serialNumber;

    private String shopName;


    /**
     * Get customerNumber
     * @return customerNumber
     **/
    
    public String getCustomerNumber() {
        return customerNumber;
    }

    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber;
    }

    /**
     * Get posCati
     * @return posCati
     **/
    
    public String getPosCati() {
        return posCati;
    }

    public void setPosCati(String posCati) {
        this.posCati = posCati;
    }

    /**
     * Get serialNumber
     * @return serialNumber
     **/
    
    public String getSerialNumber() {
        return serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * Get shopName
     * @return shopName
     **/
    
    public String getShopName() {
        return shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    @Override
    public String getOperationId() {
        return "getPosInfoDtos";
    }
}
