/*
 * 标准版
 * <p>标准版</p>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.std.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * BillFundbillApplyManualGenerationResponseDTOResult
 */
public class BillFundbillApplyManualGenerationResponseDTOResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 响应码
   */
  @JsonProperty("code")
  private String code = null;

  /**
   * 响应信息
   */
  @JsonProperty("message")
  private String message = null;

  /**
   * 文件id
   */
  @JsonProperty("fileId")
  private String fileId = null;

  /**
   * 文件生成的状态
   */
  @JsonProperty("status")
  private String status = null;

  public BillFundbillApplyManualGenerationResponseDTOResult code(String code) {
    this.code = code;
    return this;
  }

   /**
   * 响应码
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public BillFundbillApplyManualGenerationResponseDTOResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * 响应信息
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public BillFundbillApplyManualGenerationResponseDTOResult fileId(String fileId) {
    this.fileId = fileId;
    return this;
  }

   /**
   * 文件id
   * @return fileId
  **/

  public String getFileId() {
    return fileId;
  }

  public void setFileId(String fileId) {
    this.fileId = fileId;
  }

  public BillFundbillApplyManualGenerationResponseDTOResult status(String status) {
    this.status = status;
    return this;
  }

   /**
   * 文件生成的状态
   * @return status
  **/

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    BillFundbillApplyManualGenerationResponseDTOResult billFundbillApplyManualGenerationResponseDTOResult = (BillFundbillApplyManualGenerationResponseDTOResult) o;
    return ObjectUtils.equals(this.code, billFundbillApplyManualGenerationResponseDTOResult.code) &&
    ObjectUtils.equals(this.message, billFundbillApplyManualGenerationResponseDTOResult.message) &&
    ObjectUtils.equals(this.fileId, billFundbillApplyManualGenerationResponseDTOResult.fileId) &&
    ObjectUtils.equals(this.status, billFundbillApplyManualGenerationResponseDTOResult.status);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, fileId, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillFundbillApplyManualGenerationResponseDTOResult {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

