/*
 * 无卡交易系统
 * <p>中台的无卡交易系统(Card Not Present)，包含调用统一订单OPR下单及无卡支付服务NCPAY支付的流程</p>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.cnppay.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.yeepay.yop.sdk.service.cnppay.model.InstallmentPayRequestInstallmentApiInfoResult;
import java.io.Serializable;

/**
 * InstallmentPayRequestInstallmentPayResponseDTOResult
 */
public class InstallmentPayRequestInstallmentPayResponseDTOResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 返回码
   */
  @JsonProperty("code")
  private String code = null;

  /**
   * 返回信息
   */
  @JsonProperty("message")
  private String message = null;

  /**
   * 收款商户商编
   */
  @JsonProperty("merchantNo")
  private String merchantNo = null;

  /**
   * 商户收款请求号
   */
  @JsonProperty("orderId")
  private String orderId = null;

  /**
   * 订单状态
   */
  @JsonProperty("status")
  private String status = null;

  /**
   * 易宝收款订单号
   */
  @JsonProperty("uniqueOrderNo")
  private String uniqueOrderNo = null;

  /**
   * 分期信息
   */
  @JsonProperty("installmentInfo")
  private InstallmentPayRequestInstallmentApiInfoResult installmentInfo = null;

  public InstallmentPayRequestInstallmentPayResponseDTOResult code(String code) {
    this.code = code;
    return this;
  }

   /**
   * 返回码
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public InstallmentPayRequestInstallmentPayResponseDTOResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * 返回信息
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public InstallmentPayRequestInstallmentPayResponseDTOResult merchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
    return this;
  }

   /**
   * 收款商户商编
   * @return merchantNo
  **/

  public String getMerchantNo() {
    return merchantNo;
  }

  public void setMerchantNo(String merchantNo) {
    this.merchantNo = merchantNo;
  }

  public InstallmentPayRequestInstallmentPayResponseDTOResult orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * 商户收款请求号
   * @return orderId
  **/

  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public InstallmentPayRequestInstallmentPayResponseDTOResult status(String status) {
    this.status = status;
    return this;
  }

   /**
   * 订单状态
   * @return status
  **/

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InstallmentPayRequestInstallmentPayResponseDTOResult uniqueOrderNo(String uniqueOrderNo) {
    this.uniqueOrderNo = uniqueOrderNo;
    return this;
  }

   /**
   * 易宝收款订单号
   * @return uniqueOrderNo
  **/

  public String getUniqueOrderNo() {
    return uniqueOrderNo;
  }

  public void setUniqueOrderNo(String uniqueOrderNo) {
    this.uniqueOrderNo = uniqueOrderNo;
  }

  public InstallmentPayRequestInstallmentPayResponseDTOResult installmentInfo(InstallmentPayRequestInstallmentApiInfoResult installmentInfo) {
    this.installmentInfo = installmentInfo;
    return this;
  }

   /**
   * 分期信息
   * @return installmentInfo
  **/

  public InstallmentPayRequestInstallmentApiInfoResult getInstallmentInfo() {
    return installmentInfo;
  }

  public void setInstallmentInfo(InstallmentPayRequestInstallmentApiInfoResult installmentInfo) {
    this.installmentInfo = installmentInfo;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    InstallmentPayRequestInstallmentPayResponseDTOResult installmentPayRequestInstallmentPayResponseDTOResult = (InstallmentPayRequestInstallmentPayResponseDTOResult) o;
    return ObjectUtils.equals(this.code, installmentPayRequestInstallmentPayResponseDTOResult.code) &&
    ObjectUtils.equals(this.message, installmentPayRequestInstallmentPayResponseDTOResult.message) &&
    ObjectUtils.equals(this.merchantNo, installmentPayRequestInstallmentPayResponseDTOResult.merchantNo) &&
    ObjectUtils.equals(this.orderId, installmentPayRequestInstallmentPayResponseDTOResult.orderId) &&
    ObjectUtils.equals(this.status, installmentPayRequestInstallmentPayResponseDTOResult.status) &&
    ObjectUtils.equals(this.uniqueOrderNo, installmentPayRequestInstallmentPayResponseDTOResult.uniqueOrderNo) &&
    ObjectUtils.equals(this.installmentInfo, installmentPayRequestInstallmentPayResponseDTOResult.installmentInfo);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, merchantNo, orderId, status, uniqueOrderNo, installmentInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstallmentPayRequestInstallmentPayResponseDTOResult {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    uniqueOrderNo: ").append(toIndentedString(uniqueOrderNo)).append("\n");
    sb.append("    installmentInfo: ").append(toIndentedString(installmentInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

