/*
 * 无卡交易系统
 * <p>中台的无卡交易系统(Card Not Present)，包含调用统一订单OPR下单及无卡支付服务NCPAY支付的流程</p>
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.cnppay.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.yeepay.yop.sdk.service.cnppay.model.InstallmentQuerybankcfgInstallmentBankCfgInfoResult;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * InstallmentQuerybankcfgInstallmentBankCfgResponseDTOResult
 */
public class InstallmentQuerybankcfgInstallmentBankCfgResponseDTOResult implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * 返回码
   */
  @JsonProperty("code")
  private String code = null;

  /**
   * 返回信息
   */
  @JsonProperty("message")
  private String message = null;

  /**
   * 分期银行配置信息
   */
  @JsonProperty("bankCfgInfo")
  private List<InstallmentQuerybankcfgInstallmentBankCfgInfoResult> bankCfgInfo = null;

  public InstallmentQuerybankcfgInstallmentBankCfgResponseDTOResult code(String code) {
    this.code = code;
    return this;
  }

   /**
   * 返回码
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public InstallmentQuerybankcfgInstallmentBankCfgResponseDTOResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * 返回信息
   * @return message
  **/

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public InstallmentQuerybankcfgInstallmentBankCfgResponseDTOResult bankCfgInfo(List<InstallmentQuerybankcfgInstallmentBankCfgInfoResult> bankCfgInfo) {
    this.bankCfgInfo = bankCfgInfo;
    return this;
  }

  public InstallmentQuerybankcfgInstallmentBankCfgResponseDTOResult addBankCfgInfoItem(InstallmentQuerybankcfgInstallmentBankCfgInfoResult bankCfgInfoItem) {
    if (this.bankCfgInfo == null) {
      this.bankCfgInfo = new ArrayList<>();
    }
    this.bankCfgInfo.add(bankCfgInfoItem);
    return this;
  }

   /**
   * 分期银行配置信息
   * @return bankCfgInfo
  **/

  public List<InstallmentQuerybankcfgInstallmentBankCfgInfoResult> getBankCfgInfo() {
    return bankCfgInfo;
  }

  public void setBankCfgInfo(List<InstallmentQuerybankcfgInstallmentBankCfgInfoResult> bankCfgInfo) {
    this.bankCfgInfo = bankCfgInfo;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    InstallmentQuerybankcfgInstallmentBankCfgResponseDTOResult installmentQuerybankcfgInstallmentBankCfgResponseDTOResult = (InstallmentQuerybankcfgInstallmentBankCfgResponseDTOResult) o;
    return ObjectUtils.equals(this.code, installmentQuerybankcfgInstallmentBankCfgResponseDTOResult.code) &&
    ObjectUtils.equals(this.message, installmentQuerybankcfgInstallmentBankCfgResponseDTOResult.message) &&
    ObjectUtils.equals(this.bankCfgInfo, installmentQuerybankcfgInstallmentBankCfgResponseDTOResult.bankCfgInfo);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, message, bankCfgInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstallmentQuerybankcfgInstallmentBankCfgResponseDTOResult {\n");

    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    bankCfgInfo: ").append(toIndentedString(bankCfgInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

