/*
 * 账单
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.bill.request;

import com.yeepay.yop.sdk.YopConstants;
import com.yeepay.yop.sdk.http.Headers;
import com.yeepay.yop.sdk.http.HttpMethodName;
import com.yeepay.yop.sdk.http.YopContentType;
import com.yeepay.yop.sdk.internal.DefaultRequest;
import com.yeepay.yop.sdk.internal.Request;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;
import com.yeepay.yop.sdk.protocol.marshaller.PrimitiveMarshallerUtils;
import java.util.Map;
import java.util.UUID;
import java.util.Iterator;
import org.apache.commons.lang3.BooleanUtils;


public class DownloadRequestMarshaller implements RequestMarshaller<DownloadRequest> {
    private final String serviceName = "Bill";

    private final String resourcePath = "/yos/v1.0/bill/download";

    private final String contentType = "application/x-www-form-urlencoded";

    private final HttpMethodName httpMethodName = HttpMethodName.GET;


    @Override
    public Request<DownloadRequest> marshall(DownloadRequest request) {
        Request<DownloadRequest> internalRequest = new DefaultRequest<DownloadRequest>(request, serviceName);
        internalRequest.setResourcePath(resourcePath);
        internalRequest.setHttpMethod(httpMethodName);
        internalRequest.assignYos();
        if (!internalRequest.getHeaders().containsKey(Headers.YOP_REQUEST_ID)) {
            String requestId = UUID.randomUUID().toString();
            internalRequest.addHeader(Headers.YOP_REQUEST_ID, requestId);
        }
        Map<String, String> customerHeaders = request.getHeaders();
        if (customerHeaders != null) {
            for (String key : customerHeaders.keySet()) {
                internalRequest.addHeader(key, customerHeaders.get(key));
            }
        }
        if (request.getBizType() != null) {
            internalRequest.addParameter("bizType", PrimitiveMarshallerUtils.marshalling(request.getBizType(), "String"));
        }
        if (request.getBillDate() != null) {
            internalRequest.addParameter("billDate", PrimitiveMarshallerUtils.marshalling(request.getBillDate(), "String"));
        }
        internalRequest.setContentType(YopContentType.FORM_URL_ENCODE);
        internalRequest.addHeader(Headers.CONTENT_TYPE, internalRequest.getContentType().getValue());
        return internalRequest;
    }


    private static class CacheInstanceHolder {
        public static DownloadRequestMarshaller INSTANCE = new DownloadRequestMarshaller();

        private CacheInstanceHolder() {
        }
    }

    public static DownloadRequestMarshaller getInstance() {
        return CacheInstanceHolder.INSTANCE;
    }
}
