/*
 * 分账
 * <p>名称（中文）：分账<br />名称（英文，xx.war）：opr-hessian.war<br />简介：中台收款交易支持分账<br />wiki文档地址：http://wiki.yeepay.com/pages/viewpage.action?pageId=108380664<br />预计项目上线时间：2020年6月9日<br />归属/拟申请的sp编码（可选）：opr<br />期望api分组编码、名称（可选）：divide（分账）<br />涉及的接口：申请分账、分账查询、分账资金归还/分账退回、分账退回查询</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.divide;

import com.yeepay.yop.sdk.exception.YopClientException;
import com.yeepay.yop.sdk.service.divide.request.*;
import com.yeepay.yop.sdk.service.divide.response.*;

public interface DivideClient {

    /**
     * 申请分账
     * 订单支付成功后再分账时可以调用本接口实现
     * @return ApplyResponse
     * @throws YopClientException if fails to make API call
     */
    ApplyResponse apply(ApplyRequest request) throws YopClientException;

    /**
     * 申请分账资金归还
     * 
     * @return BackResponse
     * @throws YopClientException if fails to make API call
     */
    BackResponse back(BackRequest request) throws YopClientException;

    /**
     * 查询分账资金归还结果
     * 查询分账资金归还结果
     * @return BackQueryResponse
     * @throws YopClientException if fails to make API call
     */
    BackQueryResponse backQuery(BackQueryRequest request) throws YopClientException;

    /**
     * 分账资金归还回单
     * 分账资金归还回单
     * @return BackReceiptDownloadResponse
     * @throws YopClientException if fails to make API call
     */
    BackReceiptDownloadResponse backReceiptDownload(BackReceiptDownloadRequest request) throws YopClientException;

    /**
     * 完结分账
     * 完结分账
     * @return CompleteResponse
     * @throws YopClientException if fails to make API call
     */
    CompleteResponse complete(CompleteRequest request) throws YopClientException;

    /**
     * 查询分账结果
     * 调用该接口查询分账结果
     * @return QueryResponse
     * @throws YopClientException if fails to make API call
     */
    QueryResponse query(QueryRequest request) throws YopClientException;

    /**
     * 分账回单
     * 分账回单
     * @return ReceiptDownloadResponse
     * @throws YopClientException if fails to make API call
     */
    ReceiptDownloadResponse receiptDownload(ReceiptDownloadRequest request) throws YopClientException;


    /**
     * Shuts down this client object, releasing any resources that might be held open. This is an optional method, and
     * callers are not expected to call it, but can if they want to explicitly release any open resources. Once a client
     * has been shutdown, it should not be used to make any more requests.
     */
    void shutdown();
}
