/*
 * 聚合支付
 * <p>提供聚合支付相关服务（支付下单、公众号配置等功能</p>
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.aggpay.response;





import com.yeepay.yop.sdk.model.BaseResponse;

import com.yeepay.yop.sdk.service.aggpay.model.TutelagePrePayWrapPrePayOrderResponseDTOResult;

public class TutelagePrePayResponse extends BaseResponse {
    private static final long serialVersionUID = 1L;

    private TutelagePrePayWrapPrePayOrderResponseDTOResult result;

    public TutelagePrePayWrapPrePayOrderResponseDTOResult getResult() {
        return result;
    }

    public void setResult(TutelagePrePayWrapPrePayOrderResponseDTOResult result) {
        this.result = result;
    }

}
