/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.m_wallet;

import com.yeepay.yop.sdk.client.*;
import com.yeepay.yop.sdk.exception.YopClientException;
import com.yeepay.yop.sdk.http.HttpResponseAnalyzerSupport;
import com.yeepay.yop.sdk.http.HttpResponseHandler;
import com.yeepay.yop.sdk.http.handler.DefaultHttpResponseHandler;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;
import com.yeepay.yop.sdk.service.m_wallet.request.*;
import com.yeepay.yop.sdk.service.m_wallet.response.*;

public class MWalletClientImpl implements MWalletClient {

    private final ClientHandler clientHandler;

    MWalletClientImpl(ClientParams clientParams) {
        this.clientHandler = new ClientHandlerImpl(new ClientHandlerParams().withClientParams(clientParams));
    }

    @Override
    public AccountOpenResponse accountOpen(AccountOpenRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AccountOpenRequest> requestMarshaller = AccountOpenRequestMarshaller.getInstance();
        HttpResponseHandler<AccountOpenResponse> responseHandler =
                new DefaultHttpResponseHandler<AccountOpenResponse>(AccountOpenResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AccountOpenRequest, AccountOpenResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AccountQueryResponse accountQuery(AccountQueryRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getMerchantUserNo() == null){
            throw new YopClientException("request.merchantUserNo is required.");
        }
        if(request.getMerchantNo() == null){
            throw new YopClientException("request.merchantNo is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        RequestMarshaller<AccountQueryRequest> requestMarshaller = AccountQueryRequestMarshaller.getInstance();
        HttpResponseHandler<AccountQueryResponse> responseHandler =
                new DefaultHttpResponseHandler<AccountQueryResponse>(AccountQueryResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AccountQueryRequest, AccountQueryResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AccountQueryBalanceResponse accountQueryBalance(AccountQueryBalanceRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getMerchantMemberNo() == null){
            throw new YopClientException("request.merchantMemberNo is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        if(request.getMerchantNo() == null){
            throw new YopClientException("request.merchantNo is required.");
        }
        RequestMarshaller<AccountQueryBalanceRequest> requestMarshaller = AccountQueryBalanceRequestMarshaller.getInstance();
        HttpResponseHandler<AccountQueryBalanceResponse> responseHandler =
                new DefaultHttpResponseHandler<AccountQueryBalanceResponse>(AccountQueryBalanceResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AccountQueryBalanceRequest, AccountQueryBalanceResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AccountFaceCertifyOpenResponse account_face_certify_open(AccountFaceCertifyOpenRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AccountFaceCertifyOpenRequest> requestMarshaller = AccountFaceCertifyOpenRequestMarshaller.getInstance();
        HttpResponseHandler<AccountFaceCertifyOpenResponse> responseHandler =
                new DefaultHttpResponseHandler<AccountFaceCertifyOpenResponse>(AccountFaceCertifyOpenResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AccountFaceCertifyOpenRequest, AccountFaceCertifyOpenResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AccountOpenNotifyResponse account_open_notify(AccountOpenNotifyRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AccountOpenNotifyRequest> requestMarshaller = AccountOpenNotifyRequestMarshaller.getInstance();
        HttpResponseHandler<AccountOpenNotifyResponse> responseHandler =
                new DefaultHttpResponseHandler<AccountOpenNotifyResponse>(AccountOpenNotifyResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AccountOpenNotifyRequest, AccountOpenNotifyResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AccountQueryQuotaResponse account_query_quota(AccountQueryQuotaRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AccountQueryQuotaRequest> requestMarshaller = AccountQueryQuotaRequestMarshaller.getInstance();
        HttpResponseHandler<AccountQueryQuotaResponse> responseHandler =
                new DefaultHttpResponseHandler<AccountQueryQuotaResponse>(AccountQueryQuotaResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AccountQueryQuotaRequest, AccountQueryQuotaResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AgreementPaymentCancelResponse agreementPaymentCancel(AgreementPaymentCancelRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AgreementPaymentCancelRequest> requestMarshaller = AgreementPaymentCancelRequestMarshaller.getInstance();
        HttpResponseHandler<AgreementPaymentCancelResponse> responseHandler =
                new DefaultHttpResponseHandler<AgreementPaymentCancelResponse>(AgreementPaymentCancelResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AgreementPaymentCancelRequest, AgreementPaymentCancelResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AgreementPaymentSignResponse agreementPaymentSign(AgreementPaymentSignRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AgreementPaymentSignRequest> requestMarshaller = AgreementPaymentSignRequestMarshaller.getInstance();
        HttpResponseHandler<AgreementPaymentSignResponse> responseHandler =
                new DefaultHttpResponseHandler<AgreementPaymentSignResponse>(AgreementPaymentSignResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AgreementPaymentSignRequest, AgreementPaymentSignResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AgreementPaymentQueryResponse agreement_payment_query(AgreementPaymentQueryRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AgreementPaymentQueryRequest> requestMarshaller = AgreementPaymentQueryRequestMarshaller.getInstance();
        HttpResponseHandler<AgreementPaymentQueryResponse> responseHandler =
                new DefaultHttpResponseHandler<AgreementPaymentQueryResponse>(AgreementPaymentQueryResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AgreementPaymentQueryRequest, AgreementPaymentQueryResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AgreementPaymentRequestV1Response agreement_payment_request_v1(AgreementPaymentRequestV1Request request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AgreementPaymentRequestV1Request> requestMarshaller = AgreementPaymentRequestV1RequestMarshaller.getInstance();
        HttpResponseHandler<AgreementPaymentRequestV1Response> responseHandler =
                new DefaultHttpResponseHandler<AgreementPaymentRequestV1Response>(AgreementPaymentRequestV1Response.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AgreementPaymentRequestV1Request, AgreementPaymentRequestV1Response>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AutoDeductionCreateResponse auto_deduction_create(AutoDeductionCreateRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AutoDeductionCreateRequest> requestMarshaller = AutoDeductionCreateRequestMarshaller.getInstance();
        HttpResponseHandler<AutoDeductionCreateResponse> responseHandler =
                new DefaultHttpResponseHandler<AutoDeductionCreateResponse>(AutoDeductionCreateResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AutoDeductionCreateRequest, AutoDeductionCreateResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AutoDeductionQueryResponse auto_deduction_query(AutoDeductionQueryRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AutoDeductionQueryRequest> requestMarshaller = AutoDeductionQueryRequestMarshaller.getInstance();
        HttpResponseHandler<AutoDeductionQueryResponse> responseHandler =
                new DefaultHttpResponseHandler<AutoDeductionQueryResponse>(AutoDeductionQueryResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AutoDeductionQueryRequest, AutoDeductionQueryResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AutoWithdrawResponse auto_withdraw(AutoWithdrawRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AutoWithdrawRequest> requestMarshaller = AutoWithdrawRequestMarshaller.getInstance();
        HttpResponseHandler<AutoWithdrawResponse> responseHandler =
                new DefaultHttpResponseHandler<AutoWithdrawResponse>(AutoWithdrawResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AutoWithdrawRequest, AutoWithdrawResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public AutoWithdrawQueryResponse auto_withdraw_query(AutoWithdrawQueryRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<AutoWithdrawQueryRequest> requestMarshaller = AutoWithdrawQueryRequestMarshaller.getInstance();
        HttpResponseHandler<AutoWithdrawQueryResponse> responseHandler =
                new DefaultHttpResponseHandler<AutoWithdrawQueryResponse>(AutoWithdrawQueryResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<AutoWithdrawQueryRequest, AutoWithdrawQueryResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BankAccountActivationResponse bankAccountActivation(BankAccountActivationRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<BankAccountActivationRequest> requestMarshaller = BankAccountActivationRequestMarshaller.getInstance();
        HttpResponseHandler<BankAccountActivationResponse> responseHandler =
                new DefaultHttpResponseHandler<BankAccountActivationResponse>(BankAccountActivationResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BankAccountActivationRequest, BankAccountActivationResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BankAccountConfirmResponse bankAccountConfirm(BankAccountConfirmRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<BankAccountConfirmRequest> requestMarshaller = BankAccountConfirmRequestMarshaller.getInstance();
        HttpResponseHandler<BankAccountConfirmResponse> responseHandler =
                new DefaultHttpResponseHandler<BankAccountConfirmResponse>(BankAccountConfirmResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BankAccountConfirmRequest, BankAccountConfirmResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BankAccountOpenResponse bankAccountOpen(BankAccountOpenRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getBody() == null){
            throw new YopClientException("request.body is required.");
        }
        RequestMarshaller<BankAccountOpenRequest> requestMarshaller = BankAccountOpenRequestMarshaller.getInstance();
        HttpResponseHandler<BankAccountOpenResponse> responseHandler =
                new DefaultHttpResponseHandler<BankAccountOpenResponse>(BankAccountOpenResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BankAccountOpenRequest, BankAccountOpenResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BankAccountQueryActivationResponse bankAccountQueryActivation(BankAccountQueryActivationRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getRequestNo() == null){
            throw new YopClientException("request.requestNo is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        if(request.getMerchantNo() == null){
            throw new YopClientException("request.merchantNo is required.");
        }
        RequestMarshaller<BankAccountQueryActivationRequest> requestMarshaller = BankAccountQueryActivationRequestMarshaller.getInstance();
        HttpResponseHandler<BankAccountQueryActivationResponse> responseHandler =
                new DefaultHttpResponseHandler<BankAccountQueryActivationResponse>(BankAccountQueryActivationResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BankAccountQueryActivationRequest, BankAccountQueryActivationResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BankAccountQueryComplaintResponse bankAccountQueryComplaint(BankAccountQueryComplaintRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getMerchantMemberNo() == null){
            throw new YopClientException("request.merchantMemberNo is required.");
        }
        if(request.getAccountNo() == null){
            throw new YopClientException("request.accountNo is required.");
        }
        if(request.getBankTradeNo() == null){
            throw new YopClientException("request.bankTradeNo is required.");
        }
        if(request.getTradeTime() == null){
            throw new YopClientException("request.tradeTime is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        if(request.getMerchantNo() == null){
            throw new YopClientException("request.merchantNo is required.");
        }
        RequestMarshaller<BankAccountQueryComplaintRequest> requestMarshaller = BankAccountQueryComplaintRequestMarshaller.getInstance();
        HttpResponseHandler<BankAccountQueryComplaintResponse> responseHandler =
                new DefaultHttpResponseHandler<BankAccountQueryComplaintResponse>(BankAccountQueryComplaintResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BankAccountQueryComplaintRequest, BankAccountQueryComplaintResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BankAccountQueryOpenResultResponse bankAccountQueryOpenResult(BankAccountQueryOpenResultRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getRequestNo() == null){
            throw new YopClientException("request.requestNo is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        if(request.getMerchantNo() == null){
            throw new YopClientException("request.merchantNo is required.");
        }
        RequestMarshaller<BankAccountQueryOpenResultRequest> requestMarshaller = BankAccountQueryOpenResultRequestMarshaller.getInstance();
        HttpResponseHandler<BankAccountQueryOpenResultResponse> responseHandler =
                new DefaultHttpResponseHandler<BankAccountQueryOpenResultResponse>(BankAccountQueryOpenResultResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BankAccountQueryOpenResultRequest, BankAccountQueryOpenResultResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BankAccountQueryTradeResponse bankAccountQueryTrade(BankAccountQueryTradeRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getMerchantMemberNo() == null){
            throw new YopClientException("request.merchantMemberNo is required.");
        }
        if(request.getAccountNo() == null){
            throw new YopClientException("request.accountNo is required.");
        }
        if(request.getBeginDate() == null){
            throw new YopClientException("request.beginDate is required.");
        }
        if(request.getEndDate() == null){
            throw new YopClientException("request.endDate is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        if(request.getMerchantNo() == null){
            throw new YopClientException("request.merchantNo is required.");
        }
        RequestMarshaller<BankAccountQueryTradeRequest> requestMarshaller = BankAccountQueryTradeRequestMarshaller.getInstance();
        HttpResponseHandler<BankAccountQueryTradeResponse> responseHandler =
                new DefaultHttpResponseHandler<BankAccountQueryTradeResponse>(BankAccountQueryTradeResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BankAccountQueryTradeRequest, BankAccountQueryTradeResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BankAccountQueryWithdrawResponse bankAccountQueryWithdraw(BankAccountQueryWithdrawRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getRequestNo() == null){
            throw new YopClientException("request.requestNo is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        if(request.getMerchantNo() == null){
            throw new YopClientException("request.merchantNo is required.");
        }
        RequestMarshaller<BankAccountQueryWithdrawRequest> requestMarshaller = BankAccountQueryWithdrawRequestMarshaller.getInstance();
        HttpResponseHandler<BankAccountQueryWithdrawResponse> responseHandler =
                new DefaultHttpResponseHandler<BankAccountQueryWithdrawResponse>(BankAccountQueryWithdrawResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BankAccountQueryWithdrawRequest, BankAccountQueryWithdrawResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BankAccountSendMsgResponse bankAccountSendMsg(BankAccountSendMsgRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<BankAccountSendMsgRequest> requestMarshaller = BankAccountSendMsgRequestMarshaller.getInstance();
        HttpResponseHandler<BankAccountSendMsgResponse> responseHandler =
                new DefaultHttpResponseHandler<BankAccountSendMsgResponse>(BankAccountSendMsgResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BankAccountSendMsgRequest, BankAccountSendMsgResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BankAccountUpdateKeyWordsResponse bankAccountUpdateKeyWords(BankAccountUpdateKeyWordsRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<BankAccountUpdateKeyWordsRequest> requestMarshaller = BankAccountUpdateKeyWordsRequestMarshaller.getInstance();
        HttpResponseHandler<BankAccountUpdateKeyWordsResponse> responseHandler =
                new DefaultHttpResponseHandler<BankAccountUpdateKeyWordsResponse>(BankAccountUpdateKeyWordsResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BankAccountUpdateKeyWordsRequest, BankAccountUpdateKeyWordsResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BankAccountWithdrawResponse bankAccountWithdraw(BankAccountWithdrawRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<BankAccountWithdrawRequest> requestMarshaller = BankAccountWithdrawRequestMarshaller.getInstance();
        HttpResponseHandler<BankAccountWithdrawResponse> responseHandler =
                new DefaultHttpResponseHandler<BankAccountWithdrawResponse>(BankAccountWithdrawResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BankAccountWithdrawRequest, BankAccountWithdrawResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BillQueryDetailResponse bill_query_detail(BillQueryDetailRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<BillQueryDetailRequest> requestMarshaller = BillQueryDetailRequestMarshaller.getInstance();
        HttpResponseHandler<BillQueryDetailResponse> responseHandler =
                new DefaultHttpResponseHandler<BillQueryDetailResponse>(BillQueryDetailResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BillQueryDetailRequest, BillQueryDetailResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BillQueryListResponse bill_query_list(BillQueryListRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<BillQueryListRequest> requestMarshaller = BillQueryListRequestMarshaller.getInstance();
        HttpResponseHandler<BillQueryListResponse> responseHandler =
                new DefaultHttpResponseHandler<BillQueryListResponse>(BillQueryListResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BillQueryListRequest, BillQueryListResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public BillQueryOverviewResponse bill_query_overview(BillQueryOverviewRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<BillQueryOverviewRequest> requestMarshaller = BillQueryOverviewRequestMarshaller.getInstance();
        HttpResponseHandler<BillQueryOverviewResponse> responseHandler =
                new DefaultHttpResponseHandler<BillQueryOverviewResponse>(BillQueryOverviewResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<BillQueryOverviewRequest, BillQueryOverviewResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public CardQueryResponse cardQuery(CardQueryRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<CardQueryRequest> requestMarshaller = CardQueryRequestMarshaller.getInstance();
        HttpResponseHandler<CardQueryResponse> responseHandler =
                new DefaultHttpResponseHandler<CardQueryResponse>(CardQueryResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<CardQueryRequest, CardQueryResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public MemberQueryResponse memberQuery(MemberQueryRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        if(request.getMerchantNo() == null){
            throw new YopClientException("request.merchantNo is required.");
        }
        RequestMarshaller<MemberQueryRequest> requestMarshaller = MemberQueryRequestMarshaller.getInstance();
        HttpResponseHandler<MemberQueryResponse> responseHandler =
                new DefaultHttpResponseHandler<MemberQueryResponse>(MemberQueryResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<MemberQueryRequest, MemberQueryResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public MemberCardListResponse member_card_list(MemberCardListRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<MemberCardListRequest> requestMarshaller = MemberCardListRequestMarshaller.getInstance();
        HttpResponseHandler<MemberCardListResponse> responseHandler =
                new DefaultHttpResponseHandler<MemberCardListResponse>(MemberCardListResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<MemberCardListRequest, MemberCardListResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public PasswordManageResponse passwordManage(PasswordManageRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<PasswordManageRequest> requestMarshaller = PasswordManageRequestMarshaller.getInstance();
        HttpResponseHandler<PasswordManageResponse> responseHandler =
                new DefaultHttpResponseHandler<PasswordManageResponse>(PasswordManageResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<PasswordManageRequest, PasswordManageResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public RechargeInitiateResponse rechargeInitiate(RechargeInitiateRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<RechargeInitiateRequest> requestMarshaller = RechargeInitiateRequestMarshaller.getInstance();
        HttpResponseHandler<RechargeInitiateResponse> responseHandler =
                new DefaultHttpResponseHandler<RechargeInitiateResponse>(RechargeInitiateResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<RechargeInitiateRequest, RechargeInitiateResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public RechargeQueryResponse rechargeQuery(RechargeQueryRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getRequestNo() == null){
            throw new YopClientException("request.requestNo is required.");
        }
        if(request.getMerchantNo() == null){
            throw new YopClientException("request.merchantNo is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        RequestMarshaller<RechargeQueryRequest> requestMarshaller = RechargeQueryRequestMarshaller.getInstance();
        HttpResponseHandler<RechargeQueryResponse> responseHandler =
                new DefaultHttpResponseHandler<RechargeQueryResponse>(RechargeQueryResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<RechargeQueryRequest, RechargeQueryResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public SubscribeExpireNotifyResponse subscribe_expire_notify(SubscribeExpireNotifyRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<SubscribeExpireNotifyRequest> requestMarshaller = SubscribeExpireNotifyRequestMarshaller.getInstance();
        HttpResponseHandler<SubscribeExpireNotifyResponse> responseHandler =
                new DefaultHttpResponseHandler<SubscribeExpireNotifyResponse>(SubscribeExpireNotifyResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<SubscribeExpireNotifyRequest, SubscribeExpireNotifyResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public TradeOrderResponse tradeOrder(TradeOrderRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<TradeOrderRequest> requestMarshaller = TradeOrderRequestMarshaller.getInstance();
        HttpResponseHandler<TradeOrderResponse> responseHandler =
                new DefaultHttpResponseHandler<TradeOrderResponse>(TradeOrderResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<TradeOrderRequest, TradeOrderResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public TradeOrderV2Response tradeOrderV2(TradeOrderV2Request request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<TradeOrderV2Request> requestMarshaller = TradeOrderV2RequestMarshaller.getInstance();
        HttpResponseHandler<TradeOrderV2Response> responseHandler =
                new DefaultHttpResponseHandler<TradeOrderV2Response>(TradeOrderV2Response.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<TradeOrderV2Request, TradeOrderV2Response>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public TransferB2cInitiateResponse transferB2cInitiate(TransferB2cInitiateRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<TransferB2cInitiateRequest> requestMarshaller = TransferB2cInitiateRequestMarshaller.getInstance();
        HttpResponseHandler<TransferB2cInitiateResponse> responseHandler =
                new DefaultHttpResponseHandler<TransferB2cInitiateResponse>(TransferB2cInitiateResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<TransferB2cInitiateRequest, TransferB2cInitiateResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public TransferB2cMarketResponse transferB2cMarket(TransferB2cMarketRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<TransferB2cMarketRequest> requestMarshaller = TransferB2cMarketRequestMarshaller.getInstance();
        HttpResponseHandler<TransferB2cMarketResponse> responseHandler =
                new DefaultHttpResponseHandler<TransferB2cMarketResponse>(TransferB2cMarketResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<TransferB2cMarketRequest, TransferB2cMarketResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public TransferB2cQueryResponse transferB2cQuery(TransferB2cQueryRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        if(request.getFromMerchantNo() == null){
            throw new YopClientException("request.fromMerchantNo is required.");
        }
        RequestMarshaller<TransferB2cQueryRequest> requestMarshaller = TransferB2cQueryRequestMarshaller.getInstance();
        HttpResponseHandler<TransferB2cQueryResponse> responseHandler =
                new DefaultHttpResponseHandler<TransferB2cQueryResponse>(TransferB2cQueryResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<TransferB2cQueryRequest, TransferB2cQueryResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public WalletCancelResponse walletCancel(WalletCancelRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<WalletCancelRequest> requestMarshaller = WalletCancelRequestMarshaller.getInstance();
        HttpResponseHandler<WalletCancelResponse> responseHandler =
                new DefaultHttpResponseHandler<WalletCancelResponse>(WalletCancelResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<WalletCancelRequest, WalletCancelResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public WalletIndexV2Response walletIndexV2(WalletIndexV2Request request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<WalletIndexV2Request> requestMarshaller = WalletIndexV2RequestMarshaller.getInstance();
        HttpResponseHandler<WalletIndexV2Response> responseHandler =
                new DefaultHttpResponseHandler<WalletIndexV2Response>(WalletIndexV2Response.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<WalletIndexV2Request, WalletIndexV2Response>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public WithdrawInitiateResponse withdrawInitiate(WithdrawInitiateRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<WithdrawInitiateRequest> requestMarshaller = WithdrawInitiateRequestMarshaller.getInstance();
        HttpResponseHandler<WithdrawInitiateResponse> responseHandler =
                new DefaultHttpResponseHandler<WithdrawInitiateResponse>(WithdrawInitiateResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<WithdrawInitiateRequest, WithdrawInitiateResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }
    @Override
    public WithdrawQueryResponse withdrawQuery(WithdrawQueryRequest request) throws YopClientException{
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        if(request.getRequestNo() == null){
            throw new YopClientException("request.requestNo is required.");
        }
        if(request.getMerchantNo() == null){
            throw new YopClientException("request.merchantNo is required.");
        }
        if(request.getParentMerchantNo() == null){
            throw new YopClientException("request.parentMerchantNo is required.");
        }
        RequestMarshaller<WithdrawQueryRequest> requestMarshaller = WithdrawQueryRequestMarshaller.getInstance();
        HttpResponseHandler<WithdrawQueryResponse> responseHandler =
                new DefaultHttpResponseHandler<WithdrawQueryResponse>(WithdrawQueryResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<WithdrawQueryRequest, WithdrawQueryResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }

    @Override
    public void shutdown() {
        clientHandler.shutdown();
    }

}
