/*
 * 账户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.account;

import com.yeepay.yop.sdk.exception.YopClientException;
import com.yeepay.yop.sdk.service.account.request.*;
import com.yeepay.yop.sdk.service.account.response.*;

public interface AccountClient {

    /**
     * 记账簿退款查询
     * 
     * @return AccountBookQueryRefundResponse
     * @throws YopClientException if fails to make API call
     */
    AccountBookQueryRefundResponse accountBookQueryRefund(AccountBookQueryRefundRequest request) throws YopClientException;

    /**
     * 记账簿退款
     * 
     * @return AccountBookRefundResponse
     * @throws YopClientException if fails to make API call
     */
    AccountBookRefundResponse accountBookRefund(AccountBookRefundRequest request) throws YopClientException;

    /**
     * 开立记账簿
     * 商户请求该接口，申请开通买家记账簿
     * @return AccountManageAccountOpenResponse
     * @throws YopClientException if fails to make API call
     */
    AccountManageAccountOpenResponse accountManageAccountOpen(AccountManageAccountOpenRequest request) throws YopClientException;

    /**
     * 查询记账簿
     * 商户请求该接口，查询相应记账簿余额。
     * @return AccountManageAccountQueryResponse
     * @throws YopClientException if fails to make API call
     */
    AccountManageAccountQueryResponse accountManageAccountQuery(AccountManageAccountQueryRequest request) throws YopClientException;

    /**
     * 开立银行账户
     * 
     * @return AccountManageBankAccountOpenResponse
     * @throws YopClientException if fails to make API call
     */
    AccountManageBankAccountOpenResponse accountManageBankAccountOpen(AccountManageBankAccountOpenRequest request) throws YopClientException;

    /**
     * 开立银行账户查询
     * 
     * @return AccountManageBankAccountQueryResponse
     * @throws YopClientException if fails to make API call
     */
    AccountManageBankAccountQueryResponse accountManageBankAccountQuery(AccountManageBankAccountQueryRequest request) throws YopClientException;

    /**
     * 付款到个人--申请添加个人用户
     * 此服务针对于有付款给个人收款方且不满足使用企业付款场景的商户使用。商户向常用个人用户付款前，请先通过此接口申请添加个人用户信息
     * @return AccountIndividualApplyResponse
     * @throws YopClientException if fails to make API call
     */
    AccountIndividualApplyResponse account_individual_apply(AccountIndividualApplyRequest request) throws YopClientException;

    /**
     * 付款到个人--查询已添加的个人用户
     * 通过此服务查询付款商户已经添加的个人用户信息
     * @return AccountIndividualQueryResponse
     * @throws YopClientException if fails to make API call
     */
    AccountIndividualQueryResponse account_individual_query(AccountIndividualQueryRequest request) throws YopClientException;

    /**
     * 付款到个人--查询申请进度
     * 通过此接口服务查询个人用户添加进度
     * @return AccountIndividualQueryProgressResponse
     * @throws YopClientException if fails to make API call
     */
    AccountIndividualQueryProgressResponse account_individual_query_progress(AccountIndividualQueryProgressRequest request) throws YopClientException;

    /**
     * 全部账户余额查询
     * 
     * @return AccountinfosQueryResponse
     * @throws YopClientException if fails to make API call
     */
    AccountinfosQueryResponse accountinfosQuery(AccountinfosQueryRequest request) throws YopClientException;

    /**
     * 自动提现-规则作废
     * 自动提现-规则作废
     * @return AutoWithdrawRuleCancelResponse
     * @throws YopClientException if fails to make API call
     */
    AutoWithdrawRuleCancelResponse autoWithdrawRuleCancel(AutoWithdrawRuleCancelRequest request) throws YopClientException;

    /**
     * 自动提现-规则查询
     * 自动提现-规则查询
     * @return AutoWithdrawRuleQueryResponse
     * @throws YopClientException if fails to make API call
     */
    AutoWithdrawRuleQueryResponse autoWithdrawRuleQuery(AutoWithdrawRuleQueryRequest request) throws YopClientException;

    /**
     * 自动提现-规则设置
     * 自动提现-规则设置
     * @return AutoWithdrawRuleSetResponse
     * @throws YopClientException if fails to make API call
     */
    AutoWithdrawRuleSetResponse autoWithdrawRuleSet(AutoWithdrawRuleSetRequest request) throws YopClientException;

    /**
     * 资金账户余额查询
     * 查询商户余额
     * @return BalanceQueryResponse
     * @throws YopClientException if fails to make API call
     */
    BalanceQueryResponse balanceQuery(BalanceQueryRequest request) throws YopClientException;

    /**
     * 银行账户支付
     * 提供银行账户支付服务
     * @return BankPaymentOrderResponse
     * @throws YopClientException if fails to make API call
     */
    BankPaymentOrderResponse bankPaymentOrder(BankPaymentOrderRequest request) throws YopClientException;

    /**
     * 记账薄支付
     * 记账薄支付
     * @return EnterpriseAccountBookPayOrderResponse
     * @throws YopClientException if fails to make API call
     */
    EnterpriseAccountBookPayOrderResponse enterpriseAccountBookPayOrder(EnterpriseAccountBookPayOrderRequest request) throws YopClientException;

    /**
     * 企业账户支付-下单
     * 企业账户支付提供商户支付给其他商家的能力，主要解决收单场景中商户余额付款需求，如购买机票等
     * @return EnterpriseAccountPayOrderResponse
     * @throws YopClientException if fails to make API call
     */
    EnterpriseAccountPayOrderResponse enterpriseAccountPayOrder(EnterpriseAccountPayOrderRequest request) throws YopClientException;

    /**
     * 企业账户支付-自动付款
     * 付款方主动发起的付款请求
     * @return EnterpriseAutoPaymentOrderResponse
     * @throws YopClientException if fails to make API call
     */
    EnterpriseAutoPaymentOrderResponse enterpriseAutoPaymentOrder(EnterpriseAutoPaymentOrderRequest request) throws YopClientException;

    /**
     * 企业账户支付-自动付款订单查询
     * 查询自动付款订单
     * @return EnterpriseAutoPaymentQueryResponse
     * @throws YopClientException if fails to make API call
     */
    EnterpriseAutoPaymentQueryResponse enterpriseAutoPaymentQuery(EnterpriseAutoPaymentQueryRequest request) throws YopClientException;

    /**
     * 企业账户支付-token支付
     * 企业账户支付-token支付
     * @return EnterpriseTokenPayOrderResponse
     * @throws YopClientException if fails to make API call
     */
    EnterpriseTokenPayOrderResponse enterpriseTokenPayOrder(EnterpriseTokenPayOrderRequest request) throws YopClientException;

    /**
     * 企业账户支付-关系扣款
     * 企业账户支付-关系扣款
     * @return EnterpriseWithholdingOrderResponse
     * @throws YopClientException if fails to make API call
     */
    EnterpriseWithholdingOrderResponse enterpriseWithholdingOrder(EnterpriseWithholdingOrderRequest request) throws YopClientException;

    /**
     * 银行账户支付-外部订单同步
     * 用于报送非易宝订单信息
     * @return ExternalOrderResponse
     * @throws YopClientException if fails to make API call
     */
    ExternalOrderResponse externalOrder(ExternalOrderRequest request) throws YopClientException;

    /**
     * 付款-批量下单
     * 为了保证出款成功，各农信社卡或账号16位以下的农业银行卡，建议或尽可能填写支行编码； &lt;/br&gt;有报错信息并不代表未受理，具体是否受理参看batchAcceptDetailList中受理明细
     * @return PayBatchOrderResponse
     * @throws YopClientException if fails to make API call
     */
    PayBatchOrderResponse payBatchOrder(PayBatchOrderRequest request) throws YopClientException;

    /**
     * 付款-批次查询
     * 付款-批次查询
     * @return PayBatchQueryResponse
     * @throws YopClientException if fails to make API call
     */
    PayBatchQueryResponse payBatchQuery(PayBatchQueryRequest request) throws YopClientException;

    /**
     * 付款-撤销
     * 撤销预约付款请求
     * @return PayCancelResponse
     * @throws YopClientException if fails to make API call
     */
    PayCancelResponse payCancel(PayCancelRequest request) throws YopClientException;

    /**
     * 付款-下单
     * 为了保证出款成功，各农信社卡或账号16位以下的农业银行卡，建议或尽可能填写支行编码；
     * @return PayOrderResponse
     * @throws YopClientException if fails to make API call
     */
    PayOrderResponse payOrder(PayOrderRequest request) throws YopClientException;

    /**
     * 付款-查询
     * 
     * @return PayQueryResponse
     * @throws YopClientException if fails to make API call
     */
    PayQueryResponse payQuery(PayQueryRequest request) throws YopClientException;

    /**
     * 付款-查询
     * 
     * @return PaySystemQueryResponse
     * @throws YopClientException if fails to make API call
     */
    PaySystemQueryResponse paySystemQuery(PaySystemQueryRequest request) throws YopClientException;

    /**
     * 获取资金汇总凭证
     * 
     * @return ReceiptGatherResponse
     * @throws YopClientException if fails to make API call
     */
    ReceiptGatherResponse receiptGather(ReceiptGatherRequest request) throws YopClientException;

    /**
     * 电子回单-下载
     * 
     * @return ReceiptGetResponse
     * @throws YopClientException if fails to make API call
     */
    ReceiptGetResponse receiptGet(ReceiptGetRequest request) throws YopClientException;

    /**
     * 充值-下单（多种支付）
     * 提供商户资金进入易宝商户账户的能力，充值方式支持企业网银和个人网银、银行汇款、银行扣款等
     * @return RechargeResponse
     * @throws YopClientException if fails to make API call
     */
    RechargeResponse recharge(RechargeRequest request) throws YopClientException;

    /**
     * 批量查询记账簿来账流水
     * 通过此接口可批量查询记账簿来账流水
     * @return RechargeAccountBookQueryResponse
     * @throws YopClientException if fails to make API call
     */
    RechargeAccountBookQueryResponse rechargeAccountBookQuery(RechargeAccountBookQueryRequest request) throws YopClientException;

    /**
     * 充值订单批量查询
     * 
     * @return RechargeBatchQueryResponse
     * @throws YopClientException if fails to make API call
     */
    RechargeBatchQueryResponse rechargeBatchQuery(RechargeBatchQueryRequest request) throws YopClientException;

    /**
     * 充值-网银下单
     * 
     * @return RechargeOnlinebankOrderResponse
     * @throws YopClientException if fails to make API call
     */
    RechargeOnlinebankOrderResponse rechargeOnlinebankOrder(RechargeOnlinebankOrderRequest request) throws YopClientException;

    /**
     * 充值-银行汇款下单
     * 发起充值
     * @return RechargeOrderResponse
     * @throws YopClientException if fails to make API call
     */
    RechargeOrderResponse rechargeOrder(RechargeOrderRequest request) throws YopClientException;

    /**
     * 充值-查询
     * 
     * @return RechargeQueryResponse
     * @throws YopClientException if fails to make API call
     */
    RechargeQueryResponse rechargeQuery(RechargeQueryRequest request) throws YopClientException;

    /**
     * 设置提现规则
     * 
     * @return SetWithdrawRuleResponse
     * @throws YopClientException if fails to make API call
     */
    SetWithdrawRuleResponse setWithdrawRule(SetWithdrawRuleRequest request) throws YopClientException;

    /**
     * 付款到供应商--申请添加供应商
     * 付款到供应商--申请添加供应商
     * @return SupplierApplyResponse
     * @throws YopClientException if fails to make API call
     */
    SupplierApplyResponse supplierApply(SupplierApplyRequest request) throws YopClientException;

    /**
     * 付款到供应商-下单
     * 付款到供应商-下单
     * @return SupplierPayOrderResponse
     * @throws YopClientException if fails to make API call
     */
    SupplierPayOrderResponse supplierPayOrder(SupplierPayOrderRequest request) throws YopClientException;

    /**
     * 付款到供应商--查询已添加的供应商
     * 付款到供应商--查询已添加的供应商
     * @return SupplierQueryResponse
     * @throws YopClientException if fails to make API call
     */
    SupplierQueryResponse supplierQuery(SupplierQueryRequest request) throws YopClientException;

    /**
     * 付款到供应商--查询申请进度
     * 付款到供应商--查询申请进度
     * @return SupplierQueryProgressResponse
     * @throws YopClientException if fails to make API call
     */
    SupplierQueryProgressResponse supplierQueryProgress(SupplierQueryProgressRequest request) throws YopClientException;

    /**
     * 转账-下单
     * 
     * @return TransferB2bOrderResponse
     * @throws YopClientException if fails to make API call
     */
    TransferB2bOrderResponse transferB2bOrder(TransferB2bOrderRequest request) throws YopClientException;

    /**
     * 转账-查询
     * 
     * @return TransferB2bQueryResponse
     * @throws YopClientException if fails to make API call
     */
    TransferB2bQueryResponse transferB2bQuery(TransferB2bQueryRequest request) throws YopClientException;

    /**
     * 转账-查询
     * 
     * @return TransferSystemQueryResponse
     * @throws YopClientException if fails to make API call
     */
    TransferSystemQueryResponse transferSystemQuery(TransferSystemQueryRequest request) throws YopClientException;

    /**
     * 转账到微信零钱-下单
     * 
     * @return TransferWechatOrderResponse
     * @throws YopClientException if fails to make API call
     */
    TransferWechatOrderResponse transferWechatOrder(TransferWechatOrderRequest request) throws YopClientException;

    /**
     * 转账到微信零钱-查询
     * 
     * @return TransferWechatQueryResponse
     * @throws YopClientException if fails to make API call
     */
    TransferWechatQueryResponse transferWechatQuery(TransferWechatQueryRequest request) throws YopClientException;

    /**
     * 提现卡-添加
     * 为了保证出款成功，各农信社卡或账号16位以下的农业银行卡，建议或尽可能填写支行编码；
     * @return WithdrawCardBindResponse
     * @throws YopClientException if fails to make API call
     */
    WithdrawCardBindResponse withdrawCardBind(WithdrawCardBindRequest request) throws YopClientException;

    /**
     * 提现卡-修改/注销
     * 
     * @return WithdrawCardModifyResponse
     * @throws YopClientException if fails to make API call
     */
    WithdrawCardModifyResponse withdrawCardModify(WithdrawCardModifyRequest request) throws YopClientException;

    /**
     * 提现卡查询
     * 
     * @return WithdrawCardQueryResponse
     * @throws YopClientException if fails to make API call
     */
    WithdrawCardQueryResponse withdrawCardQuery(WithdrawCardQueryRequest request) throws YopClientException;

    /**
     * 提现-下单
     * 
     * @return WithdrawOrderResponse
     * @throws YopClientException if fails to make API call
     */
    WithdrawOrderResponse withdrawOrder(WithdrawOrderRequest request) throws YopClientException;

    /**
     * 提现-查询
     * 
     * @return WithdrawQueryResponse
     * @throws YopClientException if fails to make API call
     */
    WithdrawQueryResponse withdrawQuery(WithdrawQueryRequest request) throws YopClientException;

    /**
     * 提现-查询
     * 
     * @return WithdrawSystemQueryResponse
     * @throws YopClientException if fails to make API call
     */
    WithdrawSystemQueryResponse withdrawSystemQuery(WithdrawSystemQueryRequest request) throws YopClientException;


    /**
     * Shuts down this client object, releasing any resources that might be held open. This is an optional method, and
     * callers are not expected to call it, but can if they want to explicitly release any open resources. Once a client
     * has been shutdown, it should not be used to make any more requests.
     */
    void shutdown();
}
