/*
 * 子商户入网大算航旅
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.sys;

import com.yeepay.yop.sdk.exception.YopClientException;
import com.yeepay.yop.sdk.service.sys.request.*;
import com.yeepay.yop.sdk.service.sys.response.*;
import java.io.File;
import com.yeepay.yop.sdk.service.sys.model.MerchantQualUploadMerFileUploadRespDtoResult;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import org.junit.Test;
import org.junit.Ignore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
/**
 * API tests for SysClient
 */
@Ignore
public class SysClientTest {

    private static final Logger LOGGER = LoggerFactory.getLogger(SysClientTest.class);

    // 该Client线程安全，请使用单例模式，多次请求共用
    private final SysClient api = SysClientBuilder.builder().build();

    
    /**
     * 子商户入网资质文件上传
     *
     * &lt;p&gt;子商户入网资质文件上传，程序实现方式请参考，&lt;a href&#x3D;\&quot;https://open.yeepay.com/docs/v2/products/opr/others/5e941bd9c73481001a17bd85/index.html\&quot;&gt;文件上传程序实现样例&lt;/a &gt;&lt;/p &gt; &lt;p&gt;银行卡图片、身份证正反面不能超过5M&lt;/p &gt; &lt;p class&#x3D;\&quot;p1\&quot;&gt;营业执照图片 不能超过4M&lt;/p &gt; &lt;p class&#x3D;\&quot;p1\&quot;&gt;格式为 JPG（JPEG），BMP，PNG，GIF，TIFF，PDF&lt;/p &gt;
     *
     * @throws YopClientException
     *          if the Api call fails
     */
    @Test
    public void merchantQualUploadTest() throws YopClientException {
        MerchantQualUploadRequest request = new MerchantQualUploadRequest();
        request.setMerQual(new File("/path/to/file"));
        MerchantQualUploadResponse response = api.merchantQualUpload(request);
        LOGGER.info("result:{}", response.getResult());
        // TODO: test validations
    }
    

}
