/*
 * 子商户入网大算航旅
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.sys.response;




import com.yeepay.yop.sdk.model.yos.BaseYosUploadResponse;


import com.yeepay.yop.sdk.service.sys.model.MerchantQualUploadMerFileUploadRespDtoResult;

public class MerchantQualUploadResponse extends BaseYosUploadResponse {
    private static final long serialVersionUID = 1L;

    private MerchantQualUploadMerFileUploadRespDtoResult result;

    public MerchantQualUploadMerFileUploadRespDtoResult getResult() {
        return result;
    }

    public void setResult(MerchantQualUploadMerFileUploadRespDtoResult result) {
        this.result = result;
    }

}
