/*
 * 子商户入网大算航旅
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.sys.request;

import com.yeepay.yop.sdk.model.BaseRequest;
import java.io.File;
public class MerchantQualUploadRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private File merQual;


    /**
     * Get merQual
     * @return merQual
     **/
    
    public File getMerQual() {
        return merQual;
    }

    public void setMerQual(File merQual) {
        this.merQual = merQual;
    }

    @Override
    public String getOperationId() {
        return "merchantQualUpload";
    }
}
