/*
 * 线下业务
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.offline.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;

/**
 * 绑机入参支付方式；用来控制终端是否展示用户扫码、商家扫码、退货、撤销的入口
 */
public class PayWayInfo implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * &lt;div data-page-id&#x3D;\&quot;doxcnTwjJz4RAeZptELxdVTBOTd\&quot; data-docx-has-block-data&#x3D;\&quot;false\&quot;&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcn0qMSw4qYgocMUvPJMGht5e\&quot;&gt;用户扫码入口&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnIGEU86ECKYSqwTVDsLLzTf\&quot;&gt;0：隐藏&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcn0qsm4uCEis66ETPjeJmt3f\&quot;&gt;1：展示（默认）&lt;/div&gt; &lt;/div&gt;
   */
  @JsonProperty("userScan")
  private Integer userScan = null;

  /**
   * &lt;div data-page-id&#x3D;\&quot;doxcnTwjJz4RAeZptELxdVTBOTd\&quot; data-docx-has-block-data&#x3D;\&quot;false\&quot;&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcne8MQAKeqImwwYZD4j7CSbh\&quot;&gt;商家扫码入口&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnaOEE08eOayw2YT7xThal77\&quot;&gt;0：隐藏&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnckse2AAG2YKKUFWGsKnMCg\&quot;&gt;1：展示（默认）&lt;/div&gt; &lt;/div&gt;
   */
  @JsonProperty("merchantScan")
  private Integer merchantScan = null;

  /**
   * &lt;div data-page-id&#x3D;\&quot;doxcnTwjJz4RAeZptELxdVTBOTd\&quot; data-docx-has-block-data&#x3D;\&quot;false\&quot;&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnaqSqCOOG6mqMaOKgEkfzhh\&quot;&gt;退货入口&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnG60Suc68GoSM6DfUthz7db\&quot;&gt;0：隐藏&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcn0qUEyo0sOKyAoRqbk7pWKd\&quot;&gt;1：展示（默认）&lt;/div&gt; &lt;/div&gt;
   */
  @JsonProperty("reverse")
  private Integer reverse = null;

  /**
   * &lt;div data-page-id&#x3D;\&quot;doxcnTwjJz4RAeZptELxdVTBOTd\&quot; data-docx-has-block-data&#x3D;\&quot;false\&quot;&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcn2aOU0q6yGesugQ09PpAxnb\&quot;&gt;撤销入口&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnE0MScoswCKGMeGHXLD8Qye\&quot;&gt;0：隐藏&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcn48I80aKgasaiekQXHlXKvh\&quot;&gt;1：展示（默认）&lt;/div&gt; &lt;/div&gt;
   */
  @JsonProperty("refund")
  private Integer refund = null;

  public PayWayInfo userScan(Integer userScan) {
    this.userScan = userScan;
    return this;
  }

   /**
   * &lt;div data-page-id&#x3D;\&quot;doxcnTwjJz4RAeZptELxdVTBOTd\&quot; data-docx-has-block-data&#x3D;\&quot;false\&quot;&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcn0qMSw4qYgocMUvPJMGht5e\&quot;&gt;用户扫码入口&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnIGEU86ECKYSqwTVDsLLzTf\&quot;&gt;0：隐藏&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcn0qsm4uCEis66ETPjeJmt3f\&quot;&gt;1：展示（默认）&lt;/div&gt; &lt;/div&gt;
   * @return userScan
  **/

  public Integer getUserScan() {
    return userScan;
  }

  public void setUserScan(Integer userScan) {
    this.userScan = userScan;
  }

  public PayWayInfo merchantScan(Integer merchantScan) {
    this.merchantScan = merchantScan;
    return this;
  }

   /**
   * &lt;div data-page-id&#x3D;\&quot;doxcnTwjJz4RAeZptELxdVTBOTd\&quot; data-docx-has-block-data&#x3D;\&quot;false\&quot;&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcne8MQAKeqImwwYZD4j7CSbh\&quot;&gt;商家扫码入口&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnaOEE08eOayw2YT7xThal77\&quot;&gt;0：隐藏&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnckse2AAG2YKKUFWGsKnMCg\&quot;&gt;1：展示（默认）&lt;/div&gt; &lt;/div&gt;
   * @return merchantScan
  **/

  public Integer getMerchantScan() {
    return merchantScan;
  }

  public void setMerchantScan(Integer merchantScan) {
    this.merchantScan = merchantScan;
  }

  public PayWayInfo reverse(Integer reverse) {
    this.reverse = reverse;
    return this;
  }

   /**
   * &lt;div data-page-id&#x3D;\&quot;doxcnTwjJz4RAeZptELxdVTBOTd\&quot; data-docx-has-block-data&#x3D;\&quot;false\&quot;&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnaqSqCOOG6mqMaOKgEkfzhh\&quot;&gt;退货入口&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnG60Suc68GoSM6DfUthz7db\&quot;&gt;0：隐藏&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcn0qUEyo0sOKyAoRqbk7pWKd\&quot;&gt;1：展示（默认）&lt;/div&gt; &lt;/div&gt;
   * @return reverse
  **/

  public Integer getReverse() {
    return reverse;
  }

  public void setReverse(Integer reverse) {
    this.reverse = reverse;
  }

  public PayWayInfo refund(Integer refund) {
    this.refund = refund;
    return this;
  }

   /**
   * &lt;div data-page-id&#x3D;\&quot;doxcnTwjJz4RAeZptELxdVTBOTd\&quot; data-docx-has-block-data&#x3D;\&quot;false\&quot;&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcn2aOU0q6yGesugQ09PpAxnb\&quot;&gt;撤销入口&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcnE0MScoswCKGMeGHXLD8Qye\&quot;&gt;0：隐藏&lt;/div&gt; &lt;div class&#x3D;\&quot;ace-line ace-line old-record-id-doxcn48I80aKgasaiekQXHlXKvh\&quot;&gt;1：展示（默认）&lt;/div&gt; &lt;/div&gt;
   * @return refund
  **/

  public Integer getRefund() {
    return refund;
  }

  public void setRefund(Integer refund) {
    this.refund = refund;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    PayWayInfo payWayInfo = (PayWayInfo) o;
    return ObjectUtils.equals(this.userScan, payWayInfo.userScan) &&
    ObjectUtils.equals(this.merchantScan, payWayInfo.merchantScan) &&
    ObjectUtils.equals(this.reverse, payWayInfo.reverse) &&
    ObjectUtils.equals(this.refund, payWayInfo.refund);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(userScan, merchantScan, reverse, refund);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayWayInfo {\n");

    sb.append("    userScan: ").append(toIndentedString(userScan)).append("\n");
    sb.append("    merchantScan: ").append(toIndentedString(merchantScan)).append("\n");
    sb.append("    reverse: ").append(toIndentedString(reverse)).append("\n");
    sb.append("    refund: ").append(toIndentedString(refund)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

