/*
 * 线下业务
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.sdk.service.offline.model;

import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.yeepay.yop.sdk.service.offline.model.YopQueryShopBindResponse;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * 所属绑机信息
 */
public class YopQueryShopBindRspDto implements Serializable{

  private static final long serialVersionUID = 1L;

  /**
   * &lt;p&gt;绑机信息&lt;/p&gt;
   */
  @JsonProperty("bindResponses")
  private List<YopQueryShopBindResponse> bindResponses = new ArrayList<>();

  /**
   * &lt;p&gt;返回码&lt;/p&gt;
   */
  @JsonProperty("retCode")
  private String retCode = null;

  /**
   * &lt;p&gt;返回信息&lt;/p&gt;
   */
  @JsonProperty("retMsg")
  private String retMsg = null;

  public YopQueryShopBindRspDto bindResponses(List<YopQueryShopBindResponse> bindResponses) {
    this.bindResponses = bindResponses;
    return this;
  }

  public YopQueryShopBindRspDto addBindResponsesItem(YopQueryShopBindResponse bindResponsesItem) {
    this.bindResponses.add(bindResponsesItem);
    return this;
  }

   /**
   * &lt;p&gt;绑机信息&lt;/p&gt;
   * @return bindResponses
  **/

  public List<YopQueryShopBindResponse> getBindResponses() {
    return bindResponses;
  }

  public void setBindResponses(List<YopQueryShopBindResponse> bindResponses) {
    this.bindResponses = bindResponses;
  }

  public YopQueryShopBindRspDto retCode(String retCode) {
    this.retCode = retCode;
    return this;
  }

   /**
   * &lt;p&gt;返回码&lt;/p&gt;
   * @return retCode
  **/

  public String getRetCode() {
    return retCode;
  }

  public void setRetCode(String retCode) {
    this.retCode = retCode;
  }

  public YopQueryShopBindRspDto retMsg(String retMsg) {
    this.retMsg = retMsg;
    return this;
  }

   /**
   * &lt;p&gt;返回信息&lt;/p&gt;
   * @return retMsg
  **/

  public String getRetMsg() {
    return retMsg;
  }

  public void setRetMsg(String retMsg) {
    this.retMsg = retMsg;
  }


  @Override
  public boolean equals(Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    YopQueryShopBindRspDto yopQueryShopBindRspDto = (YopQueryShopBindRspDto) o;
    return ObjectUtils.equals(this.bindResponses, yopQueryShopBindRspDto.bindResponses) &&
    ObjectUtils.equals(this.retCode, yopQueryShopBindRspDto.retCode) &&
    ObjectUtils.equals(this.retMsg, yopQueryShopBindRspDto.retMsg);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(bindResponses, retCode, retMsg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class YopQueryShopBindRspDto {\n");

    sb.append("    bindResponses: ").append(toIndentedString(bindResponses)).append("\n");
    sb.append("    retCode: ").append(toIndentedString(retCode)).append("\n");
    sb.append("    retMsg: ").append(toIndentedString(retMsg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

