/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.m_wallet.request;

import com.yeepay.yop.sdk.YopConstants;
import com.yeepay.yop.sdk.http.Headers;
import com.yeepay.yop.sdk.http.HttpMethodName;
import com.yeepay.yop.sdk.http.YopContentType;
import com.yeepay.yop.sdk.internal.DefaultRequest;
import com.yeepay.yop.sdk.internal.Request;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;
import com.yeepay.yop.sdk.protocol.marshaller.PrimitiveMarshallerUtils;
import java.util.Map;
import java.util.UUID;
import java.util.Iterator;
import org.apache.commons.lang3.BooleanUtils;


public class AccountOpenNotifyRequestMarshaller implements RequestMarshaller<AccountOpenNotifyRequest> {
    private final String serviceName = "MWallet";

    private final String resourcePath = "/rest/v1.0/m-wallet/account/open/notify";

    private final String contentType = "application/x-www-form-urlencoded";

    private final HttpMethodName httpMethodName = HttpMethodName.POST;


    @Override
    public Request<AccountOpenNotifyRequest> marshall(AccountOpenNotifyRequest request) {
        Request<AccountOpenNotifyRequest> internalRequest = new DefaultRequest<AccountOpenNotifyRequest>(request, serviceName);
        internalRequest.setResourcePath(resourcePath);
        internalRequest.setHttpMethod(httpMethodName);
        if (!internalRequest.getHeaders().containsKey(Headers.YOP_REQUEST_ID)) {
            String requestId = UUID.randomUUID().toString();
            internalRequest.addHeader(Headers.YOP_REQUEST_ID, requestId);
        }
        Map<String, String> customerHeaders = request.getHeaders();
        if (customerHeaders != null) {
            for (String key : customerHeaders.keySet()) {
                internalRequest.addHeader(key, customerHeaders.get(key));
            }
        }
        if (request.getMerchantNo() != null) {
            internalRequest.addParameter("merchantNo", PrimitiveMarshallerUtils.marshalling(request.getMerchantNo(), "String"));
        }
        if (request.getMerchantUserNo() != null) {
            internalRequest.addParameter("merchantUserNo", PrimitiveMarshallerUtils.marshalling(request.getMerchantUserNo(), "String"));
        }
        if (request.getWalletUserNo() != null) {
            internalRequest.addParameter("walletUserNo", PrimitiveMarshallerUtils.marshalling(request.getWalletUserNo(), "String"));
        }
        if (request.getNotifyUrl() != null) {
            internalRequest.addParameter("notifyUrl", PrimitiveMarshallerUtils.marshalling(request.getNotifyUrl(), "String"));
        }
        if (request.getRequestNo() != null) {
            internalRequest.addParameter("requestNo", PrimitiveMarshallerUtils.marshalling(request.getRequestNo(), "String"));
        }
        if (request.getBusinessNo() != null) {
            internalRequest.addParameter("businessNo", PrimitiveMarshallerUtils.marshalling(request.getBusinessNo(), "String"));
        }
        internalRequest.setContentType(YopContentType.FORM_URL_ENCODE);
        internalRequest.addHeader(Headers.CONTENT_TYPE, internalRequest.getContentType().getValue());
        return internalRequest;
    }


    private static class CacheInstanceHolder {
        public static AccountOpenNotifyRequestMarshaller INSTANCE = new AccountOpenNotifyRequestMarshaller();

        private CacheInstanceHolder() {
        }
    }

    public static AccountOpenNotifyRequestMarshaller getInstance() {
        return CacheInstanceHolder.INSTANCE;
    }
}
