/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.m_wallet.request;

import com.yeepay.yop.sdk.model.BaseRequest;
public class BankAccountUpdateKeyWordsRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String operateType;

    private String keyWordStrs;

    private String parentMerchantNo;

    private String merchantNo;


    /**
     * Get operateType
     * @return operateType
     **/
    
    public String getOperateType() {
        return operateType;
    }

    public void setOperateType(String operateType) {
        this.operateType = operateType;
    }

    /**
     * Get keyWordStrs
     * @return keyWordStrs
     **/
    
    public String getKeyWordStrs() {
        return keyWordStrs;
    }

    public void setKeyWordStrs(String keyWordStrs) {
        this.keyWordStrs = keyWordStrs;
    }

    /**
     * Get parentMerchantNo
     * @return parentMerchantNo
     **/
    
    public String getParentMerchantNo() {
        return parentMerchantNo;
    }

    public void setParentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
    }

    /**
     * Get merchantNo
     * @return merchantNo
     **/
    
    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    @Override
    public String getOperationId() {
        return "bankAccountUpdateKeyWords";
    }
}
