/*
 * 会员钱包
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.sdk.service.m_wallet.request;

import com.yeepay.yop.sdk.YopConstants;
import com.yeepay.yop.sdk.http.Headers;
import com.yeepay.yop.sdk.http.HttpMethodName;
import com.yeepay.yop.sdk.http.YopContentType;
import com.yeepay.yop.sdk.internal.DefaultRequest;
import com.yeepay.yop.sdk.internal.Request;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;
import com.yeepay.yop.sdk.protocol.marshaller.PrimitiveMarshallerUtils;
import java.util.Map;
import java.util.UUID;
import java.util.Iterator;
import org.apache.commons.lang3.BooleanUtils;


public class TransferB2cInitiateRequestMarshaller implements RequestMarshaller<TransferB2cInitiateRequest> {
    private final String serviceName = "MWallet";

    private final String resourcePath = "/rest/v1.0/m-wallet/transfer/b2c/initiate";

    private final String contentType = "application/x-www-form-urlencoded";

    private final HttpMethodName httpMethodName = HttpMethodName.POST;


    @Override
    public Request<TransferB2cInitiateRequest> marshall(TransferB2cInitiateRequest request) {
        Request<TransferB2cInitiateRequest> internalRequest = new DefaultRequest<TransferB2cInitiateRequest>(request, serviceName);
        internalRequest.setResourcePath(resourcePath);
        internalRequest.setHttpMethod(httpMethodName);
        if (!internalRequest.getHeaders().containsKey(Headers.YOP_REQUEST_ID)) {
            String requestId = UUID.randomUUID().toString();
            internalRequest.addHeader(Headers.YOP_REQUEST_ID, requestId);
        }
        Map<String, String> customerHeaders = request.getHeaders();
        if (customerHeaders != null) {
            for (String key : customerHeaders.keySet()) {
                internalRequest.addHeader(key, customerHeaders.get(key));
            }
        }
        if (request.getParentMerchantNo() != null) {
            internalRequest.addParameter("parentMerchantNo", PrimitiveMarshallerUtils.marshalling(request.getParentMerchantNo(), "String"));
        }
        if (request.getFromMerchantNo() != null) {
            internalRequest.addParameter("fromMerchantNo", PrimitiveMarshallerUtils.marshalling(request.getFromMerchantNo(), "String"));
        }
        if (request.getToMerchantNo() != null) {
            internalRequest.addParameter("toMerchantNo", PrimitiveMarshallerUtils.marshalling(request.getToMerchantNo(), "String"));
        }
        if (request.getToMerchantUserNo() != null) {
            internalRequest.addParameter("toMerchantUserNo", PrimitiveMarshallerUtils.marshalling(request.getToMerchantUserNo(), "String"));
        }
        if (request.getRequestNo() != null) {
            internalRequest.addParameter("requestNo", PrimitiveMarshallerUtils.marshalling(request.getRequestNo(), "String"));
        }
        if (request.getOrderAmount() != null) {
            internalRequest.addParameter("orderAmount", PrimitiveMarshallerUtils.marshalling(request.getOrderAmount(), "String"));
        }
        if (request.getFeeChargeSide() != null) {
            internalRequest.addParameter("feeChargeSide", PrimitiveMarshallerUtils.marshalling(request.getFeeChargeSide(), "String"));
        }
        if (request.getNotifyUrl() != null) {
            internalRequest.addParameter("notifyUrl", PrimitiveMarshallerUtils.marshalling(request.getNotifyUrl(), "String"));
        }
        internalRequest.setContentType(YopContentType.FORM_URL_ENCODE);
        internalRequest.addHeader(Headers.CONTENT_TYPE, internalRequest.getContentType().getValue());
        return internalRequest;
    }


    private static class CacheInstanceHolder {
        public static TransferB2cInitiateRequestMarshaller INSTANCE = new TransferB2cInitiateRequestMarshaller();

        private CacheInstanceHolder() {
        }
    }

    public static TransferB2cInitiateRequestMarshaller getInstance() {
        return CacheInstanceHolder.INSTANCE;
    }
}
